### ISSUE TITLE
Can't open .txt file in Zip folder opened from Chrome Downloads

### ISSUE THREAD

**Issue by zhuowei** [TeamAmaze/AmazeFileManager#1030]
Steps to reproduce:

- Download a .zip in Chrome
- Choose "open" from Chrome
- tap on a .txt file in the zip

Expected: txt file extracts
Actual: a toast saying "error" shows up, and I get this in the logcat:

```
02-19 23:58:07.630 13772 14534 E amaze   : Error while extracting file /downloads/ass2.zip
02-19 23:58:07.630 13772 14534 E amaze   : java.io.FileNotFoundException: File doesn't exist: /downloads/ass2.zip
02-19 23:58:07.630 13772 14534 E amaze   :      at java.util.zip.ZipFile.<init>(ZipFile.java:212)
02-19 23:58:07.630 13772 14534 E amaze   :      at java.util.zip.ZipFile.<init>(ZipFile.java:149)
02-19 23:58:07.630 13772 14534 E amaze   :      at java.util.zip.ZipFile.<init>(ZipFile.java:163)
02-19 23:58:07.630 13772 14534 E amaze   :      at com.amaze.filemanager.services.ExtractService$DoWork.extract(ExtractService.java:343)
02-19 23:58:07.630 13772 14534 E amaze   :      at com.amaze.filemanager.services.ExtractService$DoWork.doInBackground(ExtractService.java:610)
02-19 23:58:07.630 13772 14534 E amaze   :      at com.amaze.filemanager.services.ExtractService$DoWork.doInBackground(ExtractService.java:214)
02-19 23:58:07.630 13772 14534 E amaze   :      at android.os.AsyncTask$2.call(AsyncTask.java:333)
02-19 23:58:07.630 13772 14534 E amaze   :      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-19 23:58:07.630 13772 14534 E amaze   :      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
02-19 23:58:07.630 13772 14534 E amaze   :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-19 23:58:07.630 13772 14534 E amaze   :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-19 23:58:07.630 13772 14534 E amaze   :      at java.lang.Thread.run(Thread.java:764)
02-19 23:58:07.630 13772 14534 I Amaze   : Almost Completed
```

It seems that the zip extraction code can't deal with content providers? The .zip is actually in /sdcard/Downloads/ass2.zip, so it seems the extraction code got the wrong location.

**Comment by EmmanuelMess** [comment]
No beta yet, and we have to test if this can be reproduced in master branch.

**Comment by zhuowei** [comment]
@EmmanuelMess The URL that Chrome gave was `content://com.android.chrome.FileProvider/downloads/ass2.zip`, by the way.

Do you need me to build master then to test this, or is there a prebuilt APK I can install?

**Comment by EmmanuelMess** [comment]
Don't worry, I'll test.

**Comment by zhuowei** [comment]
Thanks!
