### ISSUE TITLE
Crash app on exit after enabling root explorer

### ISSUE THREAD

**Issue by TranceLove** [TeamAmaze/AmazeFileManager#1098]
Found on rooted Oneplus One running Slim7 (7.1.2) and rooted Samsung Galaxy S2 (GT-I9100) running Slimsaber (5.1.1).

Steps to reproduce:

1. Fresh install
2. Enable root explorer in Settings
3. Keep tap back button until exit app
4. App crash dialog popped up

Relevant logcat
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.HandlerThread.quitSafely()' on a null object reference
at com.amaze.filemanager.activities.MainActivity.closeInteractiveShell(MainActivity.java:1159)
at com.amaze.filemanager.activities.MainActivity.onDestroy(MainActivity.java:1136)
at android.app.Activity.performDestroy(Activity.java:6886)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4242)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4273) 
at android.app.ActivityThread.-wrap6(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6229) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 
```

**Comment by VishalNehra** [comment]
Related to issue #1078
