### ISSUE TITLE
Crash when opening app after being paused

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1101]
```
com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
                                        Process: com.amaze.filemanager, PID: 12228
                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.design.widget.NavigationView$SavedState
                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                            at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                            at android.os.Looper.loop(Looper.java:148)
                                            at android.app.ActivityThread.main(ActivityThread.java:5443)
                                            at java.lang.reflect.Method.invoke(Native Method)
                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                         Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.design.widget.NavigationView$SavedState
                                            at android.os.Parcel.readParcelableCreator(Parcel.java:2432)
                                            at android.os.Parcel.readParcelable(Parcel.java:2358)
                                            at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
                                            at android.view.View$BaseSavedState.<init>(View.java:21467)
                                            at com.amaze.filemanager.ui.views.drawer.CustomNavigationView$SavedState.<init>(CustomNavigationView.java:0)
                                            at com.amaze.filemanager.ui.views.drawer.CustomNavigationView$SavedState.<init>(CustomNavigationView.java:0)
                                            at com.amaze.filemanager.ui.views.drawer.CustomNavigationView$SavedState$1.createFromParcel(CustomNavigationView.java:116)
                                            at com.amaze.filemanager.ui.views.drawer.CustomNavigationView$SavedState$1.createFromParcel(CustomNavigationView.java:114)
                                            at android.os.Parcel.readParcelable(Parcel.java:2367)
                                            at android.os.Parcel.readValue(Parcel.java:2264)
                                            at android.os.Parcel.readSparseArrayInternal(Parcel.java:2675)
                                            at android.os.Parcel.readSparseArray(Parcel.java:1967)
                                            at android.os.Parcel.readValue(Parcel.java:2321)
                                            at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                            at android.os.Bundle.getSparseParcelableArray(Bundle.java:856)
                                            at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2033)
                                            at android.app.Activity.onRestoreInstanceState(Activity.java:1008)
                                            at android.app.Activity.performRestoreInstanceState(Activity.java:963)
                                            at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1186)
                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2399)
                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                            at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                            at android.os.Looper.loop(Looper.java:148) 
                                            at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                            at java.lang.reflect.Method.invoke(Native Method) 
                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

**Comment by EmmanuelMess** [comment]
Ok, no, this seems to be caused by Proguard.

**Comment by EmmanuelMess** [comment]
Ok, these seems to happen on master.

**Comment by EmmanuelMess** [comment]
Maybe it's dependent on the Android version?

**Comment by VishalNehra** [comment]
What Android version do you use?

**Comment by EmmanuelMess** [comment]
Android 6.0

**Comment by VishalNehra** [comment]
Does this happen everyone you pause the app?

**Comment by EmmanuelMess** [comment]
It depends on the amount of time since last use. If you restart imminently it doesn't seem to crash, sometime after and it crashes.

**Comment by EmmanuelMess** [comment]
I believe this could be a bug in the Support Library.
