### ISSUE TITLE
Crash on move

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1129]
Moving 133MB file from internal to SD in Android 6.0 got (when the copy ended, original file wasn't deleted) (seems to not happen always):

```
W/System.err: java.nio.BufferUnderflowException
W/System.err:     at java.nio.Buffer.checkGetBounds(Buffer.java:171)
W/System.err:     at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:113)
                  at java.nio.ByteBuffer.get(ByteBuffer.java:376)
W/System.err:     at com.amaze.filemanager.utils.files.GenericCopyUtil.copyFile(GenericCopyUtil.java:343)
                  at com.amaze.filemanager.utils.files.GenericCopyUtil.startCopy(GenericCopyUtil.java:242)
W/System.err:     at com.amaze.filemanager.utils.files.GenericCopyUtil.copy(GenericCopyUtil.java:283)
                  at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.copyFiles(CopyService.java:457)
                  at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.execute(CopyService.java:357)
                  at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:227)
                  at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:191)
                  at android.os.AsyncTask$2.call(AsyncTask.java:295)
                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                  at java.lang.Thread.run(Thread.java:818)
```

**Comment by EmmanuelMess** [comment]
@VishalNehra this should be retested.
