### ISSUE TITLE
First time app is opened in API 15 it crashes

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1135]
Crash on first start in API 15:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.NullPointerException
                      at java.io.File.fixSlashes(File.java:185)
                      at java.io.File.<init>(File.java:134)
                      at com.amaze.filemanager.utils.files.FileUtils.isPathAccesible(FileUtils.java:939)
                      at com.amaze.filemanager.database.models.Tab.getOriginalPath(Tab.java:42)
                      at com.amaze.filemanager.fragments.TabFragment.addTab(TabFragment.java:353)
                      at com.amaze.filemanager.fragments.TabFragment.addNewTab(TabFragment.java:343)
                      at com.amaze.filemanager.fragments.TabFragment.onCreateView(TabFragment.java:126)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                      at android.os.Handler.handleCallback(Handler.java:605)
                      at android.os.Handler.dispatchMessage(Handler.java:92)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:4424)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
                      at dalvik.system.NativeStart.main(Native Method)
```

**Comment by TranceLove** [comment]
I tried with Android emulator, Nexus 4 with API 15, and I couldn't reproduce the problem. Is there any specific settings on the emulator for the problem to occur?

**Comment by TranceLove** [comment]
Able to reproduce problem on Nexus One API 15, but with ARM emulator. x86 emulator is still working for me.

**Comment by EmmanuelMess** [comment]
This one is weird…
