### ISSUE TITLE
Crash on master after selecting 'videos' item

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1149]
API 15 (emulator)
```gradle
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                  java.lang.RuntimeException: An error occured while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:278)
                      at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
                      at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                      at java.lang.Thread.run(Thread.java:856)
                   Caused by: java.lang.NullPointerException
                      at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listVideos(LoadFilesListTask.java:284)
                      at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:142)
                      at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:62)
                      at android.os.AsyncTask$2.call(AsyncTask.java:264)
                      at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
                      at java.lang.Thread.run(Thread.java:856) 
I/System: Failed to destroy process 2793
I/System: libcore.io.ErrnoException: kill failed: ESRCH (No such process)
              at libcore.io.Posix.kill(Native Method)
              at libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
              at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:257)
              at eu.chainfire.libsuperuser.Shell$Interactive.close(Shell.java:1645)
              at com.amaze.filemanager.activities.MainActivity.closeInteractiveShell(MainActivity.java:1161)
              at com.amaze.filemanager.activities.MainActivity.onDestroy(MainActivity.java:1136)
              at android.app.Activity.performDestroy(Activity.java:4630)
              at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1079)
              at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3099)
              at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3130)
              at android.app.ActivityThread.access$1200(ActivityThread.java:123)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1180)
              at android.os.Handler.dispatchMessage(Handler.java:99)
              at android.os.Looper.loop(Looper.java:137)
              at android.app.ActivityThread.main(ActivityThread.java:4424)
              at java.lang.reflect.Method.invokeNative(Native Method)
              at java.lang.reflect.Method.invoke(Method.java:511)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
              at dalvik.system.NativeStart.main(Native Method)
```

**Comment by TranceLove** [comment]
Is there any special settings (e.g. no external SD card, device model, etc.) required for the emulator? I tried using Pixel 1 with API 15 (4.0.3 with Google APIs) and external 100MB SD card, and wasn't able to reproduce the problem.

https://github.com/TeamAmaze/AmazeFileManager/blob/5244911c1fe4dec78c44db32e3a08a93fd4dd346/app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java#L284

Null cursor implies error in query; but why would the `Cursor` is null?

**Comment by EmmanuelMess** [comment]
> Returns
> --
> Cursor | A Cursor object, which is positioned before the first entry, or null

--[Dev Reference](https://developer.android.com/reference/android/content/ContentResolver.html#query(android.net.Uri,%20java.lang.String[],%20java.lang.String,%20java.lang.String[],%20java.lang.String))

**Comment by VishalNehra** [comment]
But we're moving the cursor to first item, it shouldn't return null.

**Comment by EmmanuelMess** [comment]
Tell that to the guy who made the code, not me...
