### ISSUE TITLE
Crash after opening a text file on API 15

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1160]
Crash after opening a text file on API 15, `getExternalCacheDir()` is null. 
```gradle
com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NullPointerException
        at com.amaze.filemanager.activities.TextEditorActivity.lambda$load$4$TextEditorActivity(TextEditorActivity.java:296)
        at com.amaze.filemanager.activities.TextEditorActivity$$Lambda$3.onAsyncTaskFinished(Unknown Source)
        at com.amaze.filemanager.asynchronous.asynctasks.ReadFileTask.onPostExecute(ReadFileTask.java:125)
        at com.amaze.filemanager.asynchronous.asynctasks.ReadFileTask.onPostExecute(ReadFileTask.java:27)
        at android.os.AsyncTask.finish(AsyncTask.java:602)
        at android.os.AsyncTask.access$600(AsyncTask.java:156)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4424)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by TranceLove** [comment]
Reproducible with ICS emulator, Nexus One x86/ARM.

`Context.getExternalCacheDir()` returned `null`. On the other hand, I also found `EditText.getTypeface()` would return null.

Meanwhile, I also found I couldn't create file, even on its advertised internal storage (/mnt/sdcard), no matter I specified Studio-managed SD card or one made with `mksdcard`. I began to wonder there is actually some problems with such combination itself?
