### ISSUE TITLE
Starting MainAcitivity from Robolectric crashes

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1271]
Running MainActivity like this:

```java
MainActivity activity = Robolectric.buildActivity(MainActivity.class)
                .create().start().visible().get();
```

Throws:
```
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.amaze.filemanager.utils.files.FileUtils.isPathAccessible(FileUtils.java:933)
	at com.amaze.filemanager.database.models.Tab.getOriginalPath(Tab.java:42)
	at com.amaze.filemanager.fragments.TabFragment.addTab(TabFragment.java:356)
	at com.amaze.filemanager.fragments.TabFragment.addNewTab(TabFragment.java:346)
	at com.amaze.filemanager.fragments.TabFragment.onCreateView(TabFragment.java:125)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
	at android.app.Activity.performStart(Activity.java:6992)
	at org.robolectric.util.ReflectionHelpers$7.run(ReflectionHelpers.java:216)
	at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:360)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:210)
	at org.robolectric.android.controller.ComponentController$1.run(ComponentController.java:53)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:365)
	at org.robolectric.android.controller.ComponentController.invokeWhilePaused(ComponentController.java:50)
	at org.robolectric.android.controller.ActivityController.start(ActivityController.java:74)
	at com.amaze.filemanager.connectivity.usb.UsbOtgTest.usbConnectionTest(UsbOtgTest.java:38)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:568)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

**Comment by EmmanuelMess** [comment]
Nevermind, was fixed
