### ISSUE TITLE
Encrypting zip files crashes or doesn't start

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1309]
Encryption of zip (60MB) crashes, but I suppose that might be a master issue:
```
06-22 09:06:49.075 com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amaze.filemanager, PID: 11281
    java.lang.RuntimeException: Unable to start service com.amaze.filemanager.asynchronous.services.EncryptService@dfa13ac with null: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.content.Intent.getParcelableExtra(java.lang.String)' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3045)
        at android.app.ActivityThread.-wrap17(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.content.Intent.getParcelableExtra(java.lang.String)' on a null object reference
        at com.amaze.filemanager.asynchronous.services.EncryptService.onStartCommand(EncryptService.java:75)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3028)
        at android.app.ActivityThread.-wrap17(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5443) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```
Or doesn't even start, but after I select encrypt again, it says "waiting for other task to finish".

**Comment by VishalNehra** [comment]
Works fine for me. @TranceLove please confirm.

**Comment by TranceLove** [comment]
Still working. Tested with Oneplus One running Slim7 (7.1.2) and Galaxy S2 running SlimLP (5.1.1).

Test archive is from [arilamstein/choroplethrZip](https://github.com/arilamstein/choroplethrZip), a [source code release](https://github.com/arilamstein/choroplethrZip/archive/v1.5.0.zip) which weighs 64MB.

**Comment by EmmanuelMess** [comment]
I'm testing, and it seems that `EncryptService` is actually called a few times because `ServiceWatcherUtil.postWaiting()` doesn't remove the intent from `pendingIntents` the first time it is run.

Also `FileUtil.checkFolder(baseFile.getPath(), context) == 1` seems to return false, causing `EncryptService.BackgroundTask.doInBackground()` to end returning null, with no error shown whatsoever. `FileUtil.checkFolder()` calls `!folder.isDirectory()` with `folder` being the zip file, that returns false.
