### ISSUE TITLE
Disable ActionMode on FTP fragment causes crash

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1314]
To replicate:
1. Select file
2. Go to FTP fragment
3. Press back

```
06-24 12:28:05.562 com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amaze.filemanager, PID: 6500
    java.lang.NullPointerException: Attempt to read from field 'com.amaze.filemanager.ui.views.DisablableViewPager com.amaze.filemanager.fragments.TabFragment.mViewPager' on a null object reference
        at com.amaze.filemanager.activities.MainActivity.setPagingEnabled(MainActivity.java:1266)
        at com.amaze.filemanager.fragments.MainFragment$3.onDestroyActionMode(MainFragment.java:757)
        at android.support.v7.app.AppCompatDelegateImplV9$ActionModeCallbackWrapperV9.onDestroyActionMode(AppCompatDelegateImplV9.java:1815)
        at android.support.v7.view.StandaloneActionMode.finish(StandaloneActionMode.java:110)
        at android.support.v7.widget.ActionBarContextView$1.onClick(ActionBarContextView.java:172)
        at android.view.View.performClick(View.java:5201)
        at android.view.View$PerformClick.run(View.java:21163)
        at android.os.Handler.handleCallback(Handler.java:746)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by VishalNehra** [comment]
Missed this one. 
How can we select a file and go to ftp fragment. AFAIK selection disables side drawer. 
Are specifically talking about table layout devices?

**Comment by EmmanuelMess** [comment]
> AFAIK selection disables side drawer.

Nope, swipe right and drawer opens.

**Comment by VishalNehra** [comment]
I noticed it does open for some API. It's not supposed to.. so the bug also lies there.. and this crash should also be fixed. I can only work on this crash. Can you check the drawer opening code for your API?
