### ISSUE TITLE
CalledFromWrongThreadException

### ISSUE THREAD

**Issue by tianxiaogu** [TeamAmaze/AmazeFileManager#1346]
v3.2.2 from F-Droid

This should be a trivial bug. GUI should not be updated from a background thread.

```
android.view.ViewRootImpl$CalledFromWrongThreadException
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6556)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:907)
	at android.view.View.requestLayout(View.java:18728)
	at android.view.View.requestLayout(View.java:18728)
	at android.view.View.requestLayout(View.java:18728)
	at android.view.View.requestLayout(View.java:18728)
	at android.view.View.requestLayout(View.java:18728)
	at android.view.View.requestLayout(View.java:18728)
	at android.support.v4.widget.DrawerLayout.requestLayout(DrawerLayout.java:1265)
	at android.view.View.requestLayout(View.java:18728)
	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
	at android.view.View.requestLayout(View.java:18728)
	at android.widget.AbsListView.requestLayout(AbsListView.java:1975)
	at android.widget.ListView.setAdapter(ListView.java:519)
	at com.amaze.filemanager.activities.MainActivity.refreshDrawer(MainActivity.java:1519)
	at com.amaze.filemanager.activities.MainActivity.onBookAdded(MainActivity.java:2188)
	at com.amaze.filemanager.utils.DataUtils$1.run(DataUtils.java:210)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by VishalNehra** [comment]
More details please. What operation were you trying to perform?
Just checked with the code, this shouldn't be a problem in current master or v.3.3.0

**Comment by EmmanuelMess** [comment]
v3.2.2 is in neither.

**Comment by tianxiaogu** [comment]
Thanks for your reply! We found this crash via our automated testing tool. Since it seems to relate to some concurrent/asynchronous tasks, we cannot manage to reproduce it with steps we recorded.

By analyzing the source code in the master branch, `MainActivity` implements the interface `DataChangeListener`. `DataUtils` has a call to `onBookAdded`. If `AppConfig.runInBackground` starts another thread, the GUI may be updated in that thread.

<https://github.com/TeamAmaze/AmazeFileManager/blob/42d80856501fa916e361224223fa37f9669dcd60/app/src/main/java/com/amaze/filemanager/utils/DataUtils.java#L247>

**Comment by VishalNehra** [comment]
Checked with the code, nice catch; this should be fixed.
