### ISSUE TITLE
Copy failure

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1381]
API 27
AVD Pixel 2

Copy 5MB file.

Logcat:
```
07-31 13:02:50.841 com.amaze.filemanager W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.support.v4.provider.DocumentFile.getUri()' on a null object reference
        at com.amaze.filemanager.utils.files.GenericCopyUtil.startCopy(GenericCopyUtil.java:256)
07-31 13:02:50.842 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.utils.files.GenericCopyUtil.copy(GenericCopyUtil.java:320)
        at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.copyFiles(CopyService.java:486)
        at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.execute(CopyService.java:387)
        at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:260)
        at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:224)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
07-31 13:02:59.356 com.amaze.filemanager E/CopyService: Got exception checkout: /storage/emulated/0/Download/a.tar
```

**Comment by VishalNehra** [comment]
Already fixed this with #1376

**Comment by EmmanuelMess** [comment]
#1376 is an open issue for file editing, typo? Alos, the error is in master, it isn't fixed by definition.

**Comment by VishalNehra** [comment]
I'm yet to push the commits.

**Comment by EmmanuelMess** [comment]
Will wait for the PR then :).

**Comment by EmmanuelMess** [comment]
Still replicable in master.

**Comment by VishalNehra** [comment]
What are the source and target paths?

**Comment by EmmanuelMess** [comment]
`/storage/emulated/0/Photoshop.zip` to `/storage/emulated/0/Ringtones/Photoshop.zip`.

**Comment by VishalNehra** [comment]
````2018-10-19 09:06:00.769 4768-5600/com.amaze.filemanager W/System.err: java.io.FileNotFoundException: null/Samsung QLED TV – Son fulfills father’s unfinished dream.mp4 (No such file or directory)
2018-10-19 09:06:00.769 4768-5600/com.amaze.filemanager W/System.err:     at java.io.FileOutputStream.open0(Native Method)
2018-10-19 09:06:00.769 4768-5600/com.amaze.filemanager W/System.err:     at java.io.FileOutputStream.open(FileOutputStream.java:287)
2018-10-19 09:06:00.769 4768-5600/com.amaze.filemanager W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
2018-10-19 09:06:00.769 4768-5600/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.filesystem.FileUtil.isWritable(FileUtil.java:668)
2018-10-19 09:06:00.770 4768-5600/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.utils.files.GenericCopyUtil.startCopy(GenericCopyUtil.java:250)
2018-10-19 09:06:00.770 4768-5600/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.utils.files.GenericCopyUtil.copy(GenericCopyUtil.java:333)
2018-10-19 09:06:00.770 4768-5600/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.copyFiles(CopyService.java:489)
2018-10-19 09:06:00.780 4768-5600/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.execute(CopyService.java:393)
2018-10-19 09:06:00.780 4768-5600/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:266)
2018-10-19 09:06:00.780 4768-5600/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:231)
2018-10-19 09:06:00.783 4768-5600/com.amaze.filemanager W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2018-10-19 09:06:00.798 4768-5600/com.amaze.filemanager W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-10-19 09:06:00.798 4768-5600/com.amaze.filemanager W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2018-10-19 09:06:00.798 4768-5600/com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2018-10-19 09:06:00.798 4768-5600/com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2018-10-19 09:06:00.798 4768-5600/com.amaze.filemanager W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-10-19 09:06:00.814 4768-5600/com.amaze.filemanager W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.support.v4.provider.DocumentFile.getUri()' on a null object reference
2018-10-19 09:06:00.814 4768-5600/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.utils.files.GenericCopyUtil.startCopy(GenericCopyUtil.java:265)
2018-10-19 09:06:00.814 4768-5600/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.utils.files.GenericCopyUtil.copy(GenericCopyUtil.java:333)
2018-10-19 09:06:00.814 4768-5600/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.copyFiles(CopyService.java:489)
2018-10-19 09:06:00.815 4768-5600/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.execute(CopyService.java:393)
2018-10-19 09:06:00.815 4768-5600/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:266)
2018-10-19 09:06:00.815 4768-5600/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:231)````

This is the full log, I tried this on several emulators on several APIs all have the same problem. I can't imagine why the path is something like ````null/*````
Even when target is SD Card in emulator, we have a concrete path, not like a ````null/*```` still it fails.
However, copy seems to be working fine on live devices (no reports from beta users).
