### ISSUE TITLE
Crash when changing rapidly between items in drawer

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1453]
Go to "FTP Server"->"APKs"->"FTP Server"->"Internal Storage"->repeat
After 5 or 6 of drawer presses the app will crash.
```gradle
10-01 10:55:23.063 com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.amaze.filemanager, PID: 3642
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
        at java.io.File.fixSlashes(File.java:183)
        at java.io.File.<init>(File.java:130)
        at com.amaze.filemanager.filesystem.RootHelper.getFiles(RootHelper.java:314)
        at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:193)
        at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:62)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by VishalNehra** [comment]
Switching among fragments so fast will definitely have negative effects.

**Comment by EmmanuelMess** [comment]
> Switching among fragments so fast will definitely have negative effects.

It shouldn't, it is fixable, probably.
