### ISSUE TITLE
UNIQUE paths in database is causing exceptions

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1468]
I'm getting a lot of:

```
2018-10-13 00:49:22.978 com.amaze.filemanager E/SQLiteDatabase: Error inserting path=/storage/emulated/0/Ringtones
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: history.path (code 2067)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1548)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1417)
        at com.amaze.filemanager.database.UtilsHandler.setPath(UtilsHandler.java:526)
        at com.amaze.filemanager.database.UtilsHandler.lambda$saveToDatabase$0$UtilsHandler(UtilsHandler.java:185)
        at com.amaze.filemanager.database.UtilsHandler$$Lambda$0.run(Unknown Source:20)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by TranceLove** [comment]
I remember I read a SO question saying it's non-fatal (that it won't crash app), just ugly.

[SQLiteDatabase.insertOrThrow()](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#insertOrThrow(java.lang.String,%20java.lang.String,%20android.content.ContentValues)) is guaranteed to throw exceptions that you must catch however.
