### ISSUE TITLE
Opening settings crashes the app

### ISSUE THREAD

**Issue by kraxarn** [TeamAmaze/AmazeFileManager#1528]
Opening the settings in the app crashes it (Nexus 6, Android 8.1).
To see if there was something obvious, I tried opening `adb logcat` and found this:
```
11-25 21:26:07.506 23545 23545 E AndroidRuntime: FATAL EXCEPTION: main
11-25 21:26:07.506 23545 23545 E AndroidRuntime: Process: com.amaze.filemanager, PID: 23545
11-25 21:26:07.506 23545 23545 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.activities.PreferencesActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.hardware.fingerprint.FingerprintManager.isHardwareDetected()' on a null object reference
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2779)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2857)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6499)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
11-25 21:26:07.506 23545 23545 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.hardware.fingerprint.FingerprintManager.isHardwareDetected()' on a null object reference
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at com.amaze.filemanager.fragments.preference_fragments.PrefFrag.onCreate(PrefFrag.java:114)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.Fragment.performCreate(Fragment.java:2489)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1237)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2407)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3032)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2979)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7015)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7000)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2732)
11-25 21:26:07.506 23545 23545 E AndroidRuntime:        ... 9 more
11-25 21:26:07.508   757  1999 W ActivityManager:   Force finishing activity com.amaze.filemanager/.activities.PreferencesActivity
```
Seems to be some issue with detecting a fingerprint reader, which this device is missing.

**Comment by RP-RISING-STAR** [comment]
Already fixed in #1510, but not published to Play Market yet.
