### ISSUE TITLE
Crash on Extract

### ISSUE THREAD

**Issue by JavaCafe01** [TeamAmaze/AmazeFileManager#1537]
## Description
Once I try to extract a zip file, the app crashes.

## Device Info
Device: Oneplus 5

OS: Android 9.0

## Steps to Reproduce
- Find zip file
- Click on three dot icon
- Click extract

**Comment by TranceLove** [comment]
Confirmed symptom on Pixel 2 emulator running Android 9.0 + Google Play.

Logcat said
```
2018-12-05 22:58:20.356 6687-6687/com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amaze.filemanager, PID: 6687
    java.lang.RuntimeException: Unable to start service com.amaze.filemanager.asynchronous.services.ExtractService@112d85 with Intent { cmp=com.amaze.filemanager/.asynchronous.services.ExtractService (has extras) }: java.lang.SecurityException: Permission Denial: startForeground from pid=6687, uid=10085 requires android.permission.FOREGROUND_SERVICE
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3686)
        at android.app.ActivityThread.access$1600(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=6687, uid=10085 requires android.permission.FOREGROUND_SERVICE
        at android.os.Parcel.createException(Parcel.java:1942)
        at android.os.Parcel.readException(Parcel.java:1910)
        at android.os.Parcel.readException(Parcel.java:1860)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5198)
        at android.app.Service.startForeground(Service.java:695)
        at com.amaze.filemanager.asynchronous.services.ExtractService.onStartCommand(ExtractService.java:123)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3667)
        at android.app.ActivityThread.access$1600(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:9189)
        at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1189)
        at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:870)
        at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:20437)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:976)
```
