### ISSUE TITLE
App manager causes crash

### ISSUE THREAD

**Issue by kriztan** [TeamAmaze/AmazeFileManager#1604]
Im using a rooted OnePlus 3 with Android Pie (LineageOS 16) and starting the app manager causes amaze to crash with the following error:

```
FATAL EXCEPTION: ModernAsyncTask #1
Process: com.amaze.filemanager, PID: 27309
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(File.java:283)
	at com.amaze.filemanager.asynchronous.loaders.AppListLoader.loadInBackground(AppListLoader.java:58)
	at com.amaze.filemanager.asynchronous.loaders.AppListLoader.loadInBackground(AppListLoader.java:26)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**Comment by TakuyaSama** [comment]
**OnePlus One rooted** (su-addon by LineageOS Community too) running **Android Pie 9 (LineageOS 16)**, starting the **app manager** both with and without root access granted on Amaze, causes the crash and restart of the app.

**Comment by sorryusernameisalreadytaken** [comment]
Had the same issue on AndroidTV 9 (pie) on a nvidia ShieldTV.
Here is my logcat:
[logcat_amaze_appmanager_crash.txt](https://github.com/TeamAmaze/AmazeFileManager/files/4282068/logcat_amaze_appmanager_crash.txt)
