### ISSUE TITLE
amaze crashes when searching for file in large directory

### ISSUE THREAD

**Issue by TjrGithub** [TeamAmaze/AmazeFileManager#1616]
steps to reproduce:
* install lineageos-with-microg 15.1 as of 2019-04-10 with addon_root on a Mido
* install xposed and xprivacylua, restrict nothing important
* install amaze 3.3.2 from fdroid
* install oandbackup, backup all app data into internal SD (into folder /storage/emulated/0/oandbackups). There should be lots of subdirectories, including com.android.provider.contacts
* open amaze, go to /storage/emulated/0/oandbackups
* tap header bar to search, enter "provider"
* watch crash, write this bug report

[logcat_04-15-2019_13-35-38-amaze-crash-searching-for-provider-in-oandbackup.txt](https://github.com/TeamAmaze/AmazeFileManager/files/3079974/logcat_04-15-2019_13-35-38-amaze-crash-searching-for-provider-in-oandbackup.txt)

**Comment by TjrGithub** [comment]
java.lang.IndexOutOfBoundsException: Index: 4, Size: 3
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.amaze.filemanager.adapters.glide.RecyclerPreloadModelProvider.getPreloadItems(RecyclerPreloadModelProvider.java:38)
	at com.bumptech.glide.ListPreloader.preload(ListPreloader.java:173)
	at com.bumptech.glide.ListPreloader.preload(ListPreloader.java:154)
	at com.bumptech.glide.ListPreloader.onScroll(ListPreloader.java:142)
	at com.bumptech.glide.integration.recyclerview.RecyclerToListViewScrollListener.onScrolled(RecyclerToListViewScrollListener.java:58)
	at com.bumptech.glide.integration.recyclerview.RecyclerViewPreloader.onScrolled(RecyclerViewPreloader.java:96)
	at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4844)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3909)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:894)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by sdtqwe4ty** [comment]
same issue 3.3.2 android version 4.4.2

**Comment by VishalNehra** [comment]
Issue is fixed in my local. Will merge once I finalize the changes.

**Comment by TjrGithub** [comment]
Thank you for the fix. I feel great when developers read my bug reports.

**Comment by guessit-dev** [comment]
@VishalNehra Are you still working on that fix locally?
I wasn't able to find it in history or a PR.

**Comment by EmmanuelMess** [comment]
Dupe #1549
