### ISSUE TITLE
amaze crashes when denied root privileges if root explorer is still enabled

### ISSUE THREAD

**Issue by TjrGithub** [TeamAmaze/AmazeFileManager#1618]
steps to reproduce:
* fresh install lineageos-with-microg 15.1 as of 2019-04-10 with addon_root on a wiped Mido
* install xposed and xprivacylua, restrict nothing important
* install amaze 3.3.2 from fdroid
* open amaze, enable root explorer, grant root access once-only, go to /storage/EB... (i.e. somewhere "safe"), close app
* open amaze again, deny root access, watch it crash

actual behavor: crash
expected behavior: root explorer should get deactivated (silently or with a message), then proceed as if it had never been activated

[logcat_04-15-2019_13-29-38_amaze-crashes-when-denied-root-privilege.txt](https://github.com/TeamAmaze/AmazeFileManager/files/3079998/logcat_04-15-2019_13-29-38_amaze-crashes-when-denied-root-privilege.txt)

**Comment by TranceLove** [comment]
Interesting error in log

```
[04-15 13:29:23.717 2690:2745 E/AndroidRuntime]
FATAL EXCEPTION: AsyncTask #4
Process: com.amaze.filemanager, PID: 2690
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:537)
	at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:526)
	at com.amaze.filemanager.database.SortHandler.getSortType(SortHandler.java:37)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:200)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:62)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

Does it still happen in 3.5 series? As far as I tested on Fairphone 3 running LineageOS 16.0 (9.0) with Magisk, the second time Amaze is launched, Magisk's root permission dialog still pops up without crashing Amaze.

**Comment by VishalNehra** [comment]
@TranceLove Yes I think this should've been fixed.

**Comment by TjrGithub** [comment]
In 3.5.2 IzzyDroid-Version, it doesn't crash anymore, it simply asks for root permission.

However, the actual root explorer has become useless - all directories are shown as empty (and with a mangled name).
![Uploading Screenshot_20210106-174433_Amaze.png…]()

**Comment by EmmanuelMess** [comment]
Please open another issue about the empty dirs.
