### ISSUE TITLE
amaze crashes when going directly from inside a zip file to the apk manager (via side panel)

### ISSUE THREAD

**Issue by TjrGithub** [TeamAmaze/AmazeFileManager#1620]
steps to reproduce:

* fresh install lineageos-with-microg 15.1 as of 2019-04-10 with addon_root on a wiped Mido
* install xposed and xprivacylua, restrict nothing important
* install amaze 3.3.2 from fdroid
* open amaze
* tap on a .zip file
* choose explore
* swipe to open material-design-left-sidebar
* tap on apk explorer
* watch crash, write this bug report

actual behavior: crash

expected behavior: as if I had closed the zip file before opening material-design-left-sidebar

[logcat_04-15-2019_12-42-27-amaze-crash-when-going-directly-from-zip-explorer-to-apk-explorer.txt](https://github.com/TeamAmaze/AmazeFileManager/files/3080022/logcat_04-15-2019_12-42-27-amaze-crash-when-going-directly-from-zip-explorer-to-apk-explorer.txt)

**Comment by VishalNehra** [comment]
@TranceLove could you try to reproduce this? I'm unable to..

**Comment by VishalNehra** [comment]
@TjrGithub please see if you can reproduce this after setting Amaze as default file manager to open zip files.

**Comment by TranceLove** [comment]
I could reproduce the symptom, but with an extra step.

1. Open Amaze
2. Open an archive within Amaze
3. Open sidebar, open apk explorer
4. No apks showed up, and the window title was not `Apk` but `4`
5. Press back
6. Amaze crashed

```
2019-06-22 18:47:36.186 3420-4764/com.amaze.filemanager.debug E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
    Process: com.amaze.filemanager.debug, PID: 3420
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:325)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.NullPointerException
        at java.io.File.<init>(File.java:262)
        at com.amaze.filemanager.filesystem.RootHelper.getFiles(RootHelper.java:327)
        at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:196)
        at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:63)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```

Tested on Oneplus 2 running Slim7 (7.1.2).

**Comment by TjrGithub** [comment]
A new twist on this issue (with updated versions as in #1621):

When I tap on a zip file and select open-this-time-with-amaze, it just doesn't open the zip at all. When I choose open-always-with-amaze, still nothing happens, but on the next tap, I get the menu extract/view/abort.

From then on, everything happens as described by @TranceLove.

The crash, as captured by scoop:
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:353)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException
at java.io.File.<init>(File.java:282)
at com.amaze.filemanager.filesystem.RootHelper.getFiles(RootHelper.java:319)
at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:191)
at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:62)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 3 more

**Comment by archibishop** [comment]
@TranceLove I have taken up this issue and will raise a bug fix pr for it

**Comment by TjrGithub** [comment]
Thank you :-)
