### ISSUE TITLE
amaze text editor crashes when opening non-text file inside a .zip

### ISSUE THREAD

**Issue by TjrGithub** [TeamAmaze/AmazeFileManager#1621]
steps to reproduce:

* fresh install lineageos-with-microg 15.1 as of 2019-04-10 with addon_root on a wiped Mido
* install xposed and xprivacylua, restrict nothing important
* install amaze 3.3.2 from fdroid
* transfer the LineageOS zip file to external SD (https://download.lineage.microg.org/mido/lineage-15.1-20190410-microG-mido.zip)
* open amaze
* tap on that .zip file
* choose explore
* tap on file vendor.new.dat.br
* open as text, in Amaze Text Editor
* within moments, the OS will display a popup that Amaze was killed, giving me the option to restart it or disable it until reboot.
[logcat_04-15-2019_13-01-51_amaze-crashes-when-nontext-editor-in-zip.txt](https://github.com/TeamAmaze/AmazeFileManager/files/3080040/logcat_04-15-2019_13-01-51_amaze-crashes-when-nontext-editor-in-zip.txt)

**Comment by TjrGithub** [comment]
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:353)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 225968136 byte allocation with 25165824 free bytes and 142MB until OOM, max allowed footprint 144096808, growth limit 268435456
at java.util.Arrays.copyOf(Arrays.java:3260)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:451)
at java.lang.StringBuilder.append(StringBuilder.java:137)
at com.amaze.filemanager.asynchronous.asynctasks.ReadFileTask.doInBackground(ReadFileTask.java:105)
at com.amaze.filemanager.asynchronous.asynctasks.ReadFileTask.doInBackground(ReadFileTask.java:27)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more

**Comment by VishalNehra** [comment]
@TjrGithub please see if you can reproduce this after setting Amaze as default file manager to open zip files.

**Comment by TjrGithub** [comment]
Yes, it still crashes. I made it the default zip handler in the middle of the test run.
New version numbers due to wipe and reinstall: LineageOS 15.1-20190607-microG-mido, Amaze 3.3.2 FDroid, Magsik 19.3 with module Xposed v90-beta3 with modules scoop 1.6.4 and xprivacylua 1.25.

The crash itself:
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:353)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 314572808 byte allocation with 25165824 free bytes and 100MB until OOM, max allowed footprint 188461664, growth limit 268435456
at java.util.Arrays.copyOf(Arrays.java:3260)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:451)
at java.lang.StringBuilder.append(StringBuilder.java:137)
at com.amaze.filemanager.asynchronous.asynctasks.ReadFileTask.doInBackground(ReadFileTask.java:105)
at com.amaze.filemanager.asynchronous.asynctasks.ReadFileTask.doInBackground(ReadFileTask.java:27)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more

A log of the complete test run is attached, filtered for the keyword amaze.
[logcat_06-23-2019_13-11-34__amaze1621.txt](https://github.com/TeamAmaze/AmazeFileManager/files/3317768/logcat_06-23-2019_13-11-34__amaze1621.txt)

**Comment by EmmanuelMess** [comment]
This shouldn't be a problem anymore.
