### ISSUE TITLE
amaze crashes when sharing a file with target save as

### ISSUE THREAD

**Issue by TjrGithub** [TeamAmaze/AmazeFileManager#1623]
steps to reproduce:
* open FDroid, select an app
* share the apk file, with target "save as" from Amaze
* in Amaze, push the blue button on the lower right to confirm where to put it

expected behavior
* the app's apk file should be copied to the selected directory

observer behavior
* crash

versions:
Amaze 3.3.2 FDroid
FRdoid client 1.5.1 Fdroid
LineageOS 15.1-20190410-microG-mido

logcat:

java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:353)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: uri
at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:128)
at android.content.ContentResolver.openInputStream(ContentResolver.java:950)
at com.amaze.filemanager.filesystem.FileUtil$1.doInBackground(FileUtil.java:209)
at com.amaze.filemanager.filesystem.FileUtil$1.doInBackground(FileUtil.java:198)
at com.amaze.filemanager.utils.application.AppConfig$1.doInBackground(AppConfig.java:122)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 3 more

**Comment by VishalNehra** [comment]
This should be fixed with 3.5.0
Please reopen if not fixed.

**Comment by TjrGithub** [comment]
The most recent version available on FDroid is 3.1.2, so the bug is still present.

**Comment by EmmanuelMess** [comment]
I am temporarily reopening this, have you tested with 3.5?
