### ISSUE TITLE
crash when opening a .zip file directly from k9mail

### ISSUE THREAD

**Issue by TjrGithub** [TeamAmaze/AmazeFileManager#1631]
==steps to reproduce==
* get an email with a .zip file attached
* open the attachment direcly from K9-mail

==expected result==
Amaze should display the same popup as when I open a locally stored .zip file

==observed behavior==
Amaze crashes.

==versions==
* lineageos-with-microg 15.1 as of 2019-04-10 with addon_root
* Hardware: Mido
* current xposed 90beta3 and xprivacylua from Fdroid, restrict nothing important
* amaze 3.3.2 from fdroid
* K9mail from fdroid

==logs (collected with Scoop)==

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1975)
at com.amaze.filemanager.fragments.CompressedExplorerFragment.onActivityCreated(CompressedExplorerFragment.java:208)
at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2355)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1451)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by TranceLove** [comment]
Need a way to handle intents like this to solve the issue.

```
2019-07-06 14:27:24.152 773-5478/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=content://com.fsck.k9.tempfileprovider/temp/8654b7c2bdaf6861f636502c927e6e742d0bf0b0?mime_type=application/zip typ=application/zip flg=0x10080001 cmp=com.amaze.filemanager.debug/com.amaze.filemanager.activities.MainActivity} from uid 10165
```
