### ISSUE TITLE
Crash after renaming a file name

### ISSUE THREAD

**Issue by arthur-star** [TeamAmaze/AmazeFileManager#1656]
## steps to reproduce
Using a picture as an example.

1. Go to a folder and open any picture
2. Go to **Quick access**, rename the picture which just opened. (observed that the file cannot be renamed)
3. Go to folder, rename the picture. (observed that the file can be renamed)
4. Go to **Quick access**, Amaze is likely to crash.

## expected result

* The picture should renamed successfully at step 2.

## observed behavior

* The picture cannot rename at step 2.
* Amaze crashes at step 4.

## versions

    Hardware: HUAWEI MATE 10
    amaze 3.3.2 from Google Play

## logs (collected with logcat)
```
2019-07-31 20:16:18.667 24607-24607/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amaze.filemanager, PID: 24607
    java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:2036)
        at com.amaze.filemanager.utils.files.FileUtils.getPathsInPath(FileUtils.java:745)
        at com.amaze.filemanager.ui.views.appbar.BottomBar.showButtons(BottomBar.java:206)
        at com.amaze.filemanager.ui.views.appbar.BottomBar.updatePath(BottomBar.java:477)
        at com.amaze.filemanager.fragments.TabFragment.updatepaths(TabFragment.java:221)
        at com.amaze.filemanager.activities.MainActivity.updatePaths(MainActivity.java:1219)
        at com.amaze.filemanager.fragments.MainFragment.reloadListElements(MainFragment.java:1140)
        at com.amaze.filemanager.fragments.MainFragment.setListElements(MainFragment.java:1063)
        at com.amaze.filemanager.fragments.MainFragment.lambda$loadlist$3$MainFragment(MainFragment.java:1021)
        at com.amaze.filemanager.fragments.MainFragment$$Lambda$3.onAsyncTaskFinished(Unknown Source:8)
        at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:219)
        at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:62)
        at android.os.AsyncTask.finish(AsyncTask.java:696)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:713)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by VishalNehra** [comment]
Please test with v3.5.0
