### ISSUE TITLE
Crash not first datapoint

### ISSUE THREAD

**Issue by anlalalu** [TeamAmaze/AmazeFileManager#1793]
**Describe the bug**
crash when extracting zip file

**To Reproduce**
1. select a zip file and a dialog appears
2. tap 'veiw'
3. tap the zip file again
4. tap 'EXTRACT'
5. tap the file again and a dialog 'Please Wait' appears
6. keep tapping the file for several times

**Screenshots**
![Screen Shot](https://user-images.githubusercontent.com/46981872/71403550-0e360980-266b-11ea-83a1-e3cc3b54500d.png)

**Smartphone (please complete the following information):**
 - Device: emulator
 - OS: Android 4.4.4
 - Rooted: No
 - Version: 3.3.2

**Additional context**

Stack Trace:

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
                                                   Process: com.amaze.filemanager, PID: 20416
                                                   java.lang.RuntimeException: An error occured while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:841)
                                                    Caused by: java.lang.IllegalStateException: This is not the first datapoint!
                                                       at com.amaze.filemanager.asynchronous.services.AbstractProgressiveService.addFirstDatapoint(AbstractProgressiveService.java:212)
                                                       at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork$1.onStart(ExtractService.java:257)
                                                       at com.amaze.filemanager.filesystem.compressed.extractcontents.helpers.ZipExtractor.extractWithFilter(ZipExtractor.java:70)
                                                       at com.amaze.filemanager.filesystem.compressed.extractcontents.Extractor.extractFiles(Extractor.java:57)
                                                       at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:286)
                                                       at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:208)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                       at

**Comment by anlalalu** [comment]
Do you judge this as a defect?

**Comment by TranceLove** [comment]
Tried to reproduce the symptom on Galaxy Nexus emulator running 4.4.4, but seems the steps to reproduce wasn't clear enough.

> 1. select a zip file and a dialog appears
> 2. tap 'view'
> 3. tap the zip file again
Up to step 3, after tapping view, we should be looking inside the archive, but not able to list the zip. Do I need to tap back, or you are meaning to tap a file inside the archive?
> 4. tap 'EXTRACT'
> 5. tap the file again and a dialog 'Please Wait' appears
> 6. keep tapping the file for several times
Does it mean trying to extract the same file inside the archive?

**Comment by anlalalu** [comment]
In my case, the android1.zip file contains another zip file which is named Android22.zip

**Comment by anlalalu** [comment]
Does the information above help? Can you reproduce the issue now?

**Comment by TranceLove** [comment]
> Does the information above help? Can you reproduce the issue now?

My steps to reproduce:

1. Create a zip (a.zip) which contains another zip file (b.zip)
2. Upload the a.zip created in 1 to Android emulator running 4.4.4
3. Open the a.zip file in Amaze
4. Tap View
5. Contents of the zip file (i.e. the zip file inside the zip created in 1) is displayed
6. Tap b.zip
7. Tap extract
8. Seems nothing happened
9. Tap b.zip a few more times
10. Amaze crash with exception thrown as mentioned by @anlalalu

**Comment by VishalNehra** [comment]
@TranceLove request you to please test this again on release/3.5

**Comment by TranceLove** [comment]
Still reproducible. ExtractService said it would extract b.zip to Amaze's own cache directory, but nothing can be found after extract is done.

**Comment by VishalNehra** [comment]
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:354)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: This is not the first datapoint!
at com.amaze.filemanager.asynchronous.services.AbstractProgressiveService.addFirstDatapoint(AbstractProgressiveService.java:244)
at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:259)
at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:232)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more
```

**Comment by VishalNehra** [comment]
Honestly, i think this check can safely be removed for now instead of crashing the app. The worst that can happen is the progress might be wrong. This is probably a race condition somewhere.

**Comment by EmmanuelMess** [comment]
Ok, please add a Log.e though.
