### ISSUE TITLE
Crash while opening database only accessible via root

### ISSUE THREAD

**Issue by Unpublished** [TeamAmaze/AmazeFileManager#1817]
**Describe the bug**
```
java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/******/databases/*
	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
	at com.amaze.filemanager.utils.files.FileUtils.fileToContentUri(FileUtils.java:526)
	at com.amaze.filemanager.utils.files.FileUtils.lambda$openWith$3(FileUtils.java:589)
	at com.amaze.filemanager.utils.files.-$$Lambda$FileUtils$ZNqPUVGr6gxOE7yMIIq-q2qhmdI.onSelection(Unknown Source:10)
	at com.afollestad.materialdialogs.MaterialDialog.onItemSelected(MaterialDialog.java:193)
	at com.afollestad.materialdialogs.DefaultRvAdapter$DefaultVH.onClick(DefaultRvAdapter.java:203)
	at android.view.View.performClick(View.java:6608)
	at android.view.View.performClickInternal(View.java:6585)
	at android.view.View.access$3100(View.java:785)
	at android.view.View$PerformClick.run(View.java:25921)
```

**To Reproduce**
1. Try to open a database from /data/data/* as a database

**Smartphone (please complete the following information):**
 - Rooted: Yes
 - Version: master

**Comment by TranceLove** [comment]
Same things would happen too, when attempting to open files accessible via root, using the file's popup menu.
