### ISSUE TITLE
 ClassNotFoundException when unmarshalling: NavigationView$SavedState

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#1844]
AVD API 29 Pixel 3. Also AVD API 15.

This happend when opening a PDF and returning to the app via recents with "immediatly kill activites":
```
    Process: com.amaze.filemanager.debug, PID: 8790
    android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.material.navigation.NavigationView$SavedState
        at android.os.Parcel.readParcelableCreator(Parcel.java:3042)
        at android.os.Parcel.readParcelable(Parcel.java:2964)
        at android.view.AbsSavedState.<init>(AbsSavedState.java:67)
        at android.view.View$BaseSavedState.<init>(View.java:27709)
        at android.view.View$BaseSavedState.<init>(View.java:27698)
        at com.amaze.filemanager.ui.views.drawer.CustomNavigationView$SavedState.<init>(CustomNavigationView.java:128)
        at com.amaze.filemanager.ui.views.drawer.CustomNavigationView$SavedState.<init>(CustomNavigationView.java:120)
        at com.amaze.filemanager.ui.views.drawer.CustomNavigationView$SavedState$1.createFromParcel(CustomNavigationView.java:142)
        at com.amaze.filemanager.ui.views.drawer.CustomNavigationView$SavedState$1.createFromParcel(CustomNavigationView.java:140)
        at android.os.Parcel.readParcelable(Parcel.java:2973)
        at android.os.Parcel.readValue(Parcel.java:2866)
        at android.os.Parcel.readSparseArrayInternal(Parcel.java:3327)
        at android.os.Parcel.readSparseArray(Parcel.java:2484)
        at android.os.Parcel.readValue(Parcel.java:2923)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.Bundle.getSparseParcelableArray(Bundle.java:1029)
        at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2156)
        at android.app.Activity.onRestoreInstanceState(Activity.java:1563)
        at android.app.Activity.performRestoreInstanceState(Activity.java:1518)
        at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1346)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3310)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by VishalNehra** [comment]
This is the most reported issue on play console's crash reports (have been for past quite a lot of releases). Proposed fix was in #1533 apparently it didn't fix the issue.
