### ISSUE TITLE
Properties of folders or volumes results in crash on some devices

### ISSUE THREAD

**Issue by yxo-6o6uka** [TeamAmaze/AmazeFileManager#1847]
Version 3.4.3

Clicking on Properties of folders or volumes crashes Amaze on the following devices:
- Samsung Tab A 8.0 SM-T350, rooted Samsung ROM 7.1.1
- Samsung Tab Pro 8.4 SM-T320, rooted LineageOS 13

The same works fine (no issues) on the following devices
- Samsung S10+, stock ROM 10
- Samsung J7, stock ROM 8.1
- Samsung S7, stock ROM 8.0

**To Reproduce**
Open Side bar, click on properties icon next to "Internal Storage"
or
For any local folder, click on 3 dots menu, then Properties

**Comment by EmmanuelMess** [comment]
Do you have the logcat?

**Comment by yxo-6o6uka** [comment]
I should've included logcat from get go, apologies for the delay.
Attached is from Samsung Tab A 8.0 SM-T350, rooted Samsung ROM 7.1.1.
I don't have access to the SM-T320 now but will get its logcat if important, pls lmk. Guessing it maybe the same since all symptoms are identical.

Thank you for looking into this.

[logcat.zip](https://github.com/TeamAmaze/AmazeFileManager/files/4377611/logcat.zip)

**Comment by TranceLove** [comment]
Exception worth looking inside attached logcat

```
03-24 15:53:53.174 30181 30181 E AndroidRuntime: FATAL EXCEPTION: main
03-24 15:53:53.174 30181 30181 E AndroidRuntime: Process: com.amaze.filemanager, PID: 30181
03-24 15:53:53.174 30181 30181 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at com.amaze.filemanager.ui.dialogs.GeneralDialogCreation.showPropertiesDialog(GeneralDialogCreation.java:419)
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at com.amaze.filemanager.ui.dialogs.GeneralDialogCreation.showPropertiesDialogForStorage(GeneralDialogCreation.java:368)
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at com.amaze.filemanager.ui.views.drawer.Drawer.onNavigationItemActionClick(Drawer.java:612)
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at com.amaze.filemanager.ui.views.drawer.Drawer.lambda$addNewItem$5$Drawer(Drawer.java:494)
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at com.amaze.filemanager.ui.views.drawer.-$$Lambda$Drawer$TyDDeLc-_x13qNEdHDAqZC9YtAQ.onClick(lambda)
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at android.view.View.performClick(View.java:6308)
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:23969)
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6823)
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
03-24 15:53:53.174 30181 30181 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

**Comment by VishalNehra** [comment]
This is already fixed. Please test 3.5.x beta series from play store.
