### ISSUE TITLE
force close on "save as" option 

### ISSUE THREAD

**Issue by disdagithubacc** [TeamAmaze/AmazeFileManager#1856]
**Describe the bug**
the "save as" option among android share options cause the app to break.

**To Reproduce**
1. Go to 'Firefox> Share'
2. Click on 'Save as...'
4. amaze file launches. as i select the floating button, it force closes.

**Expected behavior**
maybe amaze could've downloaded the content

**Smartphone (please complete the following information):**
 - Device: LG G4 H818P
 - OS: nougat
 - Rooted: no
 - Version: 3.4.3

**Additional context**
thanks for the app though.

**Comment by boghicieusebiu** [comment]
I've experienced the same crash by saving from another app. I've noticed that it crashes if receives an intent with action `ACTION_SEND` and type `text/plain` and with no extra on `EXTRA_STREAM` key. Those intents that Firefox/Chrome sends are using `EXTRA_TEXT` for passing the information (in this case the link).

**Comment by pcsaunak** [comment]
I went to a random site and tried to save it using the Save as option, from the share button and I got the below error

`2020-07-26 08:59:02.373 18710-18745/com.amaze.filemanager.debug D/EGL_emulation: eglMakeCurrent: 0xdf2c7320: ver 3 0 (tinfo 0xea489a00)
2020-07-26 08:59:06.567 18710-18755/com.amaze.filemanager.debug E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.amaze.filemanager.debug, PID: 18710
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NullPointerException: uri
        at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:133)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1170)
        at com.amaze.filemanager.filesystem.FileUtil$1.doInBackground(FileUtil.java:213)
        at com.amaze.filemanager.filesystem.FileUtil$1.doInBackground(FileUtil.java:202)
        at com.amaze.filemanager.application.AppConfig$1.doInBackground(AppConfig.java:135)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2020-07-26 08:59:08.155 18710-18745/com.amaze.filemanager.debug D/EGL_emulation: eglMakeCurrent: 0xdf2c7320: ver 3 0 (tinfo 0xea489a00)`

**Comment by pcsaunak** [comment]
@EmmanuelMess In this case we are getting an intent of type text/plain, because of which we do not have any URI present and hence the app crashes. Any suggestions how do we want to proceed here. Do we want to create a text file with the URL and the subject line and than allow that to be saved ?

**Comment by EmmanuelMess** [comment]
We probably want to create a text file with the url, yes
