### ISSUE TITLE
App crashes when trying to decrypt file

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#1883]
**Describe the bug**
App is crashing when I try to open an encrypted file directly (by pressing on it, can be tried with images).
Edit: bug is there for opening any file not just encrypted file, on my device.

**To Reproduce**
1. Encrypte an image
2. After encrypted, press on encrypted file and fill password.
3. Let it decrypt, openFile will throw NPE

**Expected behavior**
File should successfully open

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Oneplus 6t
 - OS: Android 10
 - Rooted: No
 - Version: master

**Additional context**
Stacktrace 
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=decrypt_broadcast flg=0x10 (has extras) } in com.amaze.filemanager.fragments.MainFragment$5@8fd63cb
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1575)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7643)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.amaze.filemanager
        at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
        at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
        at com.amaze.filemanager.utils.files.FileUtils.openWith(FileUtils.java:457)
        at com.amaze.filemanager.utils.files.FileUtils.openFile(FileUtils.java:630)
        at com.amaze.filemanager.fragments.MainFragment$5.onReceive(MainFragment.java:832)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
```

**Comment by TranceLove** [comment]
Should be related to faulty merge at #1860. #1875 should help.
