### ISSUE TITLE
Amaze unable to open files on master 

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#1892]
**Describe the bug**
After the fix in #1875 Amaze is still unable to open files on my device.

**To Reproduce**
Try to open any file it'll say 'No app found to open this file'

**Expected behavior**
Amaze should open the file.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**
Stacktrace:
```2020-05-22 01:30:37.351 1290-2606/? D/OemSceneCallBlock: isCallBlockedWithUidIntent { act=android.intent.action.VIEW dat=content://com.amaze.filemanager/storage_root/storage/emulated/0/New Doc 2020-01-24 10.22.02_1.jpg typ=image/jpeg flg=0x1 cmp=android/com.android.internal.app.ResolverActivity }, ResolveInfo{4c8b8c3 android/com.android.internal.app.ResolverActivity m=0x0}, false
2020-05-22 01:30:37.352 1290-2606/? W/System.err: android.provider.Settings$SettingNotFoundException: driving_mode_state
2020-05-22 01:30:37.352 1290-2606/? W/System.err:     at android.provider.Settings$Secure.getIntForUser(Settings.java:6111)
2020-05-22 01:30:37.352 1290-2606/? W/System.err:     at android.provider.Settings$Secure.getInt(Settings.java:6101)
2020-05-22 01:30:37.352 1290-2606/? W/System.err:     at com.oneplus.android.server.scene.OemSceneCallBlock$zta.tsu(Unknown Source:10)
2020-05-22 01:30:37.352 1290-2606/? W/System.err:     at com.oneplus.android.server.scene.OemSceneCallBlock.blockerEnabled(Unknown Source:234)
2020-05-22 01:30:37.352 1290-2606/? W/System.err:     at com.oneplus.android.server.scene.OemSceneCallBlock.isCallBlockedOnForUser(Unknown Source:16)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at com.oneplus.android.server.scene.OemSceneCallBlock.isCallBlockedOnForUser(Unknown Source:1)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at com.oneplus.android.server.scene.OemSceneCallBlock.isCallBlocked(Unknown Source:105)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at com.oneplus.android.server.scene.OemSceneCallBlock.isCallBlockedWithUid(Unknown Source:43)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at com.oneplus.android.server.scene.OnePlusSceneCallBlockService.isCallBlockedWithUid(Unknown Source:15)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at mab.mab.xne.gwy.mab.isCallBlockedWithUid(Unknown Source:12)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at com.oneplus.android.scene.OnePlusSceneCallBlockManagerInjector.isCallBlockedWithUid(OnePlusSceneCallBlockManagerInjector.java:38)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:778)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:628)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1493)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:553)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1121)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1095)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1072)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1505)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at android.os.Binder.execTransactInternal(Binder.java:1032)
2020-05-22 01:30:37.353 1290-2606/? W/System.err:     at android.os.Binder.execTransact(Binder.java:1005)```

**Comment by VishalNehra** [comment]
Ping @TranceLove

**Comment by VishalNehra** [comment]
Wasn't on master while testing, my bad sorry.
