### ISSUE TITLE
Crash on double tap to open Amaze from system launcher app drawer

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#1923]
**Describe the bug**
From system launcher, when try to open Amaze, only this time quickly tap again (meaning double tap). There's a sweet spot which is easily reproducable, crashing the app.

**Expected behavior**
No crash

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Oneplus 6t
 - OS: Android 10
 - Rooted: [e.g. No]
 - Version: Release/3.5

**Additional context**
Stacktrack

```
2020-07-11 00:27:15.384 30064-30064/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amaze.filemanager.debug, PID: 30064
    java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
        at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1071)
        at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:685)
        at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:380)
        at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:896)
        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(FrameworkSQLiteStatement.java:46)
        at com.amaze.filemanager.database.daos.TabDao_Impl.clear(TabDao_Impl.java:74)
        at com.amaze.filemanager.database.TabHandler.clear(TabHandler.java:52)
        at com.amaze.filemanager.fragments.TabFragment.updatepaths(TabFragment.java:235)
        at com.amaze.filemanager.activities.MainActivity.updatePaths(MainActivity.java:1356)
        at com.amaze.filemanager.fragments.MainFragment.reloadListElements(MainFragment.java:1156)
        at com.amaze.filemanager.fragments.MainFragment.setListElements(MainFragment.java:1070)
        at com.amaze.filemanager.fragments.MainFragment.lambda$loadlist$3$MainFragment(MainFragment.java:1022)
        at com.amaze.filemanager.fragments.-$$Lambda$MainFragment$5iCPYPa3nmIESNLXGobBukohEfc.onAsyncTaskFinished(Unknown Source:8)
        at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:258)
        at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:64)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7643)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2020-07-11 00:27:15.384 30064-30126/? E/SQLiteLog: (1) no such table: room_table_modification_log
2020-07-11 00:27:15.385 30064-30125/? E/SQLiteLog: (1) no such table: room_table_modification_log
2020-07-11 00:27:15.385 30064-30102/? E/AndroidRuntime: FATAL EXCEPTION: app_background
    Process: com.amaze.filemanager.debug, PID: 30064
    java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
        at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1071)
        at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:685)
        at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:380)
        at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:896)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
        at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:64)
        at com.amaze.filemanager.database.daos.HistoryEntryDao_Impl.insert(HistoryEntryDao_Impl.java:85)
        at com.amaze.filemanager.database.UtilsHandler.lambda$saveToDatabase$0$UtilsHandler(UtilsHandler.java:88)
        at com.amaze.filemanager.database.-$$Lambda$UtilsHandler$ml9ekUPc6VOrF_Xuy2ToA61Mmxc.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2020-07-11 00:27:15.386 30064-30126/? E/ROOM: Cannot run invalidation tracker. Is the db closed?
    android.database.sqlite.SQLiteException: no such table: room_table_modification_log (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM room_table_modification_log WHERE invalidated = 1;
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1469)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1433)
        at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:161)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:328)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:311)
        at androidx.room.InvalidationTracker$1.checkUpdatedTable(InvalidationTracker.java:414)
        at androidx.room.InvalidationTracker$1.run(InvalidationTracker.java:388)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-07-11 00:27:15.386 30064-30125/? E/ROOM: Cannot run invalidation tracker. Is the db closed?
    android.database.sqlite.SQLiteException: no such table: room_table_modification_log (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM room_table_modification_log WHERE invalidated = 1;
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1469)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1433)
        at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:161)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:328)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:311)
        at androidx.room.InvalidationTracker$1.checkUpdatedTable(InvalidationTracker.java:414)
        at androidx.room.InvalidationTracker$1.run(InvalidationTracker.java:388)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-07-11 00:27:15.387 30064-30102/? I/Process: Sending signal. PID: 30064 SIG: 9
```

**Comment by VishalNehra** [comment]
Seem to be fixed with #1927
