### ISSUE TITLE
Crash on display of properties dialog in landscape

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#1937]
**Describe the bug**
Amaze crash on properties dialog. Try to view dialog in landscape mode.

**Additional context**
Stacktrace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.CheckBox.setVisibility(int)' on a null object reference
        at com.amaze.filemanager.ui.dialogs.GeneralDialogCreation.showPropertiesDialog(GeneralDialogCreation.java:459)
        at com.amaze.filemanager.ui.dialogs.GeneralDialogCreation.showPropertiesDialogWithPermissions(GeneralDialogCreation.java:392)
        at com.amaze.filemanager.ui.ItemPopupMenu.onMenuItemClick(ItemPopupMenu.java:92)
        at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:108)
        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:787)
        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:151)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
        at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1257)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3265)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7643)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by TranceLove** [comment]
Confirmed same symptom in Fairphone 3 running LineageOS 16.0 GSI (9.0).

**Comment by pcsaunak** [comment]
@TranceLove @VishalNehra Can you guys help me reproduce this ? I tried but it happened once not sure if I am on the same page as you guys are.

**Comment by dev-arpit** [comment]
I have found the bug and would like to work on this issue.
