### ISSUE TITLE
Copy and paste on remote server crashes Amaze

### ISSUE THREAD

**Issue by TranceLove** [TeamAmaze/AmazeFileManager#1942]
**Describe the bug**
Copy and paste on SSH/SMB server crashes Amaze

**To Reproduce**
1. Create a SFTP/SMB connection in Amaze
2. Click on the the created connection from the drawer
3. Go to folder where you want to copy files from on the server
4. Select some files
5. Tap copy
6. Crash

**Expected behavior**
Should have no crash at all, but the files to copy goes to clipboard, which user should be able to paste afterwards

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Fairphone 3
 - OS: LineageOS 16.0 (community build, date marked 20200625) (9.0)
 - Rooted: Yes
 - Version: 3.5 beta 1

**Comment by TranceLove** [comment]
Logcat when press copy and crashes Amaze:

```
07-26 17:41:30.143 12986 12986 E SshClientUtils: Error executing template method
07-26 17:41:30.143 12986 12986 E SshClientUtils: android.os.NetworkOnMainThreadException
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at net.schmizz.sshj.transport.TransportImpl.write(TransportImpl.java:451)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at net.schmizz.sshj.connection.channel.direct.AbstractDirectChannel.open(AbstractDirectChannel.java:57)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at net.schmizz.sshj.SSHClient.startSession(SSHClient.java:742)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at net.schmizz.sshj.sftp.SFTPEngine.<init>(SFTPEngine.java:65)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at net.schmizz.sshj.sftp.SFTPEngine.<init>(SFTPEngine.java:60)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at net.schmizz.sshj.SSHClient.newSFTPClient(SSHClient.java:713)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at com.amaze.filemanager.filesystem.ssh.SshClientUtils$2.execute(SshClientUtils.java:132)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at com.amaze.filemanager.filesystem.ssh.SshClientUtils.execute(SshClientUtils.java:72)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at com.amaze.filemanager.filesystem.ssh.SshClientUtils.execute(SshClientUtils.java:125)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at com.amaze.filemanager.filesystem.HybridFile.isDirectory(HybridFile.java:508)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at com.amaze.filemanager.filesystem.PasteHelper.getSnackbarContent(PasteHelper.java:166)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at com.amaze.filemanager.filesystem.PasteHelper.showSnackbar(PasteHelper.java:135)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at com.amaze.filemanager.filesystem.PasteHelper.<init>(PasteHelper.java:59)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at com.amaze.filemanager.ui.fragments.MainFragment$3.onActionItemClicked(MainFragment.java:748)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:2452)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at androidx.appcompat.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:141)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at android.view.View.performClick(View.java:6597)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at android.view.View.performClickInternal(View.java:6574)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at android.view.View.access$3100(View.java:778)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at android.view.View$PerformClick.run(View.java:25906)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at android.os.Handler.handleCallback(Handler.java:873)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at android.os.Looper.loop(Looper.java:193)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-26 17:41:30.143 12986 12986 E SshClientUtils: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-26 17:41:30.144 12986 12986 D AndroidRuntime: Shutting down VM
07-26 17:41:30.146 12986 12986 E AndroidRuntime: FATAL EXCEPTION: main
07-26 17:41:30.146 12986 12986 E AndroidRuntime: Process: com.amaze.filemanager.debug, PID: 12986
07-26 17:41:30.146 12986 12986 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at com.amaze.filemanager.filesystem.HybridFile.isDirectory(HybridFile.java:508)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at com.amaze.filemanager.filesystem.PasteHelper.getSnackbarContent(PasteHelper.java:166)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at com.amaze.filemanager.filesystem.PasteHelper.showSnackbar(PasteHelper.java:135)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at com.amaze.filemanager.filesystem.PasteHelper.<init>(PasteHelper.java:59)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at com.amaze.filemanager.ui.fragments.MainFragment$3.onActionItemClicked(MainFragment.java:748)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:2452)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at androidx.appcompat.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:141)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at android.view.View.performClick(View.java:6597)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6574)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at android.view.View.access$3100(View.java:778)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25906)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-26 17:41:30.146 12986 12986 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-26 17:41:30.150  1154  7288 W ActivityManager:   Force finishing activity com.amaze.filemanager.debug/com.amaze.filemanager.ui.activities.MainActivity
```

I wonder what happened that caused SSH connection to run on main thread? Current code was working before #1928.

**Comment by TranceLove** [comment]
Same problem happened on SMB connections too:

```
07-26 17:51:57.266 14729 14729 E AndroidRuntime: Process: com.amaze.filemanager.debug, PID: 14729
07-26 17:51:57.266 14729 14729 E AndroidRuntime: android.os.NetworkOnMainThreadException
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbTransportImpl.doSend(SmbTransportImpl.java:910)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.util.transport.Transport.doSend(Transport.java:276)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.util.transport.Transport.sendrecv(Transport.java:215)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1021)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1539)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:404)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:318)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:298)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbFile.withOpen(SmbFile.java:1741)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbFile.withOpen(SmbFile.java:1710)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbFile.withOpen(SmbFile.java:1704)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbFile.queryPath(SmbFile.java:770)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbFile.exists(SmbFile.java:851)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at jcifs.smb.SmbFile.isDirectory(SmbFile.java:1063)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at com.amaze.filemanager.filesystem.HybridFile.isDirectory(HybridFile.java:524)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at com.amaze.filemanager.filesystem.PasteHelper.getSnackbarContent(PasteHelper.java:166)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at com.amaze.filemanager.filesystem.PasteHelper.showSnackbar(PasteHelper.java:135)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at com.amaze.filemanager.filesystem.PasteHelper.<init>(PasteHelper.java:59)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at com.amaze.filemanager.ui.fragments.MainFragment$3.onActionItemClicked(MainFragment.java:748)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:2452)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at androidx.appcompat.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:141)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at android.view.View.performClick(View.java:6597)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6574)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at android.view.View.access$3100(View.java:778)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25906)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-26 17:51:57.266 14729 14729 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
