### ISSUE TITLE
Unable to open files when folder has too much content

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2002]
**Describe the bug**
Unable to image files through gallery

**To Reproduce**
Had over 8k images in a folder and try to open an image throwing a crash.

**Smartphone (please complete the following information):**
 - Device: Oneplus 6t
 - OS: Android 10
 - Rooted: No
 - Version: 3.5.3

**Additional context**

Stacktrace 

```
2020-10-08 20:54:52.768 28345-28345/com.amaze.filemanager.debug E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 6622424)
2020-10-08 20:54:52.769 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo: Bundle stats:
2020-10-08 20:54:52.772 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo:   android:viewHierarchyState [size=7120]
2020-10-08 20:54:52.774 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo:     android:views [size=7072]
2020-10-08 20:54:52.775 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo:       0x7f09017e [size=2864]
2020-10-08 20:54:53.310 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo:   android:support:fragments [size=6614472]
2020-10-08 20:54:53.311 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo: PersistableBundle stats:
2020-10-08 20:54:53.311 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo:   [null]
2020-10-08 20:54:53.311 28345-28345/com.amaze.filemanager.debug D/AndroidRuntime: Shutting down VM
2020-10-08 20:54:53.316 28345-28345/com.amaze.filemanager.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amaze.filemanager.debug, PID: 28345
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 6622424 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7643)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.os.TransactionTooLargeException: data parcel size 6622424 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:550)
        at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4564)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7643) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
2020-10-08 20:54:53.358 28345-28345/com.amaze.filemanager.debug I/Process: Sending signal. PID: 28345 SIG: 9

```

**Comment by EmmanuelMess** [comment]
Related https://github.com/TeamAmaze/FilePreloaderLibrary.
