### ISSUE TITLE
Crash on return from settings

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2065]
Open settings, enable root explorer, crash.

Logcat:
```
03-16 12:24:37.150 1776-1776/com.amaze.filemanager.debug W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4155d908)
03-16 12:24:37.155 1776-1776/com.amaze.filemanager.debug E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NullPointerException
        at com.amaze.filemanager.ui.activities.PreferencesActivity.onOptionsItemSelected(PreferencesActivity.java:139)
        at android.app.Activity.onMenuItemSelected(Activity.java:2546)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
        at android.view.View.performClick(View.java:4091)
        at android.view.View$PerformClick.run(View.java:17081)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:153)
        at android.app.ActivityThread.main(ActivityThread.java:4987)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
        at dalvik.system.NativeStart.main(Native Method)
```

Android 4.1.2

**Comment by EmmanuelMess** [comment]
Nvm this only happens on #2063 it seems.

**Comment by EmmanuelMess** [comment]
This crash seems probabilistic.

**Comment by A248** [comment]
I encountered the same issue. The stacktrace is very similar:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.preference.PreferenceFragment.onOptionsItemSelected(android.view.MenuItem)' on a null object reference
	at com.amaze.filemanager.ui.activities.PreferencesActivity.onOptionsItemSelected(PreferencesActivity.java:137)
	at android.app.Activity.onMenuItemSelected(Activity.java:4156)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27896)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

```
