### ISSUE TITLE
Crash on open root properites

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2066]
Android 4.1.2
Open properties of a folder in root.

```
03-16 12:50:36.679 2525-2525/com.amaze.filemanager.debug E/AndroidRuntime: FATAL EXCEPTION: main
    android.content.res.Resources$NotFoundException: Resource ID #0x7f050003
        at android.content.res.Resources.getValue(Resources.java:1035)
        at android.content.res.Resources.getBoolean(Resources.java:817)
        at com.amaze.filemanager.ui.dialogs.GeneralDialogCreation.showPropertiesDialog(GeneralDialogCreation.java:531)
        at com.amaze.filemanager.ui.dialogs.GeneralDialogCreation.showPropertiesDialogWithPermissions(GeneralDialogCreation.java:393)
        at com.amaze.filemanager.ui.ItemPopupMenu.onMenuItemClick(ItemPopupMenu.java:92)
        at android.widget.PopupMenu.onMenuItemSelected(PopupMenu.java:142)
        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
        at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:175)
        at android.widget.AdapterView.performItemClick(AdapterView.java:298)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1118)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3058)
        at android.widget.AbsListView$1.run(AbsListView.java:3816)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:153)
        at android.app.ActivityThread.main(ActivityThread.java:4987)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by VishalNehra** [comment]
Please check with v3.5.0 this should be fixed

**Comment by EmmanuelMess** [comment]
this also happens with non root folders.

**Comment by VishalNehra** [comment]
We need to take this to priority then.
