### ISSUE TITLE
Crash when super su open its dialog

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2067]
Enable root explorer and renter the app:

```
03-16 12:53:06.853 3239-3239/com.amaze.filemanager.debug E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.IllegalStateException: Fragment MainFragment{41c2e260 (cd0cd7db-9ff0-4e8a-9bcd-bc02c17ef477)} is not currently in the FragmentManager
        at androidx.fragment.app.FragmentManagerImpl.putFragment(FragmentManagerImpl.java:350)
        at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:226)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2766)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2289)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2348)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:151)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:513)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:533)
        at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1194)
        at android.app.Activity.performSaveInstanceState(Activity.java:1137)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1221)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3112)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3171)
        at android.app.ActivityThread.access$900(ActivityThread.java:149)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:153)
        at android.app.ActivityThread.main(ActivityThread.java:4987)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by VishalNehra** [comment]
dupe #1555
