### ISSUE TITLE
Crash on compression

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2108]
## Exception
* User Action: UI Error
* Request: Application crash
* Version: 3.5.2
* OS: Linux Android 11 - 30
* Device: raphaelin
* Model: Redmi K20 Pro
* Product: evolution_raphael
<details><summary><b>Crash log </b></summary><p>

java.lang.RuntimeException: Unable to start service com.amaze.filemanager.asynchronous.services.ExtractService@7593294 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4338)
 at android.app.ActivityThread.access$1800(ActivityThread.java:237)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7661)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
 at com.amaze.filemanager.asynchronous.services.ExtractService.onStartCommand(ExtractService.java:96)
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4320)
 ... 8 more

</details>
<hr>

**Comment by TranceLove** [comment]
Apparently an null `Intent` was sent to `ExtractService`. But how would it happen?

I shall insert a null check into `ExtractService.onStartCommand()` anyway and return START_NOT_STICKY, but it would be nice if end user can provide us the details.

**Comment by EmmanuelMess** [comment]
Intent is null when the service is restarted as far as I remember.

**Comment by TranceLove** [comment]
So should it return `START_NOT_STICKY` so it won't be restarted or `START_REDELIVER_INTENT` so it will be restarted with the intent?

**Comment by EmmanuelMess** [comment]
An Android service is implemented so it will be always on, recieving info and processing it. The Amaze implemetation creates a new Service each time a new thing needs to be done, which is wrong AFAIK.

We have to check why the service is being restarted, if it has already finished it shouldn't be restarted, but if it left something half done it should continue.

AFAIK there is no real way for a service to run forever until the task is completed, we should have a restarting mechanism.
