### ISSUE TITLE
Crash on files list back while selecting

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2123]
## Exception
* User Action: UI Error
* Request: Application crash
* Version: 3.5.1
* OS: Linux Android 10 - 29
* Device: Nord
* Model: AC2003
* Product: Nord_EEA
<details><summary><b>Crash log </b></summary><p>

```java.lang.NullPointerException: Attempt to read from field 'boolean com.amaze.filemanager.adapters.data.LayoutElementParcelable.isBack' on a null object reference
 at com.amaze.filemanager.adapters.RecyclerAdapter.setItems(RecyclerAdapter.java:387)
 at com.amaze.filemanager.adapters.RecyclerAdapter.setItems(RecyclerAdapter.java:370)
 at com.amaze.filemanager.asynchronous.handlers.FileHandler.handleMessage(FileHandler.java:91)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7711)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by VishalNehra** [comment]
#2224  dupe
