### ISSUE TITLE
Crash on AppListLoader

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2127]
**Smartphone:**
- Device: mata
- OS: Linux Android 10 - 29
- Rooted: Maybe
- Version: 3.5.1
### Stack traces:
**Trace:**
```java
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(File.java:283)
	at com.amaze.filemanager.asynchronous.loaders.AppListLoader.loadInBackground(AppListLoader.java:78)
	at com.amaze.filemanager.asynchronous.loaders.AppListLoader.loadInBackground(AppListLoader.java:46)
	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
	at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```
<details><summary><b>Raw mail</b></summary><p>
```json
{
  "request": "Application crash",
  "user_action": "UI Error",
  "product": "mata",
  "package": "com.amaze.filemanager",
  "os": "Linux Android 10 - 29",
  "model": "PH-1",
  "time": "2020-12-09 16:14",
  "version": "3.5.1",
  "device": "mata",
  "exceptions": "[java.lang.RuntimeException: An error occurred while executing doInBackground()\n\tat androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)\n\tat java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)\n\tat java.util.concurrent.FutureTask.setException(FutureTask.java:252)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:271)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:919)\nCaused by: java.lang.NullPointerException\n\tat java.io.File.<init>(File.java:283)\n\tat com.amaze.filemanager.asynchronous.loaders.AppListLoader.loadInBackground(AppListLoader.java:78)\n\tat com.amaze.filemanager.asynchronous.loaders.AppListLoader.loadInBackground(AppListLoader.java:46)\n\tat androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)\n\tat androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)\n\tat androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)\n\tat androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\t... 3 more\n]",
  "user_comment": ""
}
```

**Comment by TranceLove** [comment]
Related to #2116?
