### ISSUE TITLE
Crash on opening a compressed file

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2136]
## Exception
* User Action: UI Error
* Request: Application crash
* Version: 3.5.1
* OS: Linux Android 11 - 30
* Device: blueline
* Model: Pixel 3
* Product: blueline
* Comment - 
<details><summary><b>Crash log </b></summary><p>

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
 at java.lang.String.substring(String.java:2064)
 at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.onActivityCreated(CompressedExplorerFragment.java:211)
 at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2619)
 at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
 at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
 at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
 at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
 at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
 at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
 at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
 at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
 at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7656)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

</details>
<hr>

**Comment by EmmanuelMess** [comment]
Updated #2650
