### ISSUE TITLE
Crash on search results

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2137]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.2
* __OS:__ Linux Android 10 - 29
* __Device:__ raphael
* __Model:__ Mi 9T Pro
* __Product:__ raphael_eea
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: Unexpected failure to classify SearchResult: SearchResult{key=/storage/emulated/0/Pictures/Infinity/interestingasfuck-mb7.jpg, nodeFound=Node{edge=/storage/emulated/0/Pictures/Infinity/halo-kbewb0.mp4, value=-, edges=[]}, charsMatched=38, charsMatchedInNodeFound=38, parentNode=Node{edge=, value=null, edges=[Node{edge=/storage/emulated/0/Pictures/Infinity/halo-kbewb0.mp4, value=-, edges=[]}]}, parentNodesParent=null, classification=null}
at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree$SearchResult.classify(ConcurrentRadixTree.java:989)
at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree$SearchResult.<init>(ConcurrentRadixTree.java:969)
at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree.searchTree(ConcurrentRadixTree.java:932)
at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree.getValueForExactKey(ConcurrentRadixTree.java:102)
at com.amaze.filemanager.utils.DataUtils.isFileHidden(DataUtils.java:359)
at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.createListParcelables(LoadFilesListTask.java:273)
at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.lambda$doInBackground$4(LoadFilesListTask.java:231)
at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.lambda$doInBackground$4$LoadFilesListTask(Unknown Source:0)
at com.amaze.filemanager.asynchronous.asynctasks.-$$Lambda$LoadFilesListTask$UXzmWslcH0cfZfAA6Y9hqkVwFiA.invoke(Unknown Source:6)
at com.amaze.filemanager.filesystem.root.ListFilesCommand.getFilesList(ListFilesCommand.kt:173)
at com.amaze.filemanager.filesystem.root.ListFilesCommand.listFiles(ListFilesCommand.kt:67)
at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:222)
at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:67)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 3 more

```
</details>
<hr>

**Comment by VishalNehra** [comment]
Duplicate to #2106
