### ISSUE TITLE
Crash on list files command

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2140]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.2
* __OS:__ Linux Android 11 - 30
* __Device:__ redfin
* __Model:__ Pixel 5
* __Product:__ redfin
Crash log

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:415)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter path
at com.amaze.filemanager.filesystem.root.ListFilesCommand.listFiles(Unknown Source:2)
at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:222)
at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:67)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 3 more

```

**Comment by gre0j** [comment]
The crash ist from me :)

Some weeks ago i changed my phone from Huawei P20pro to Google Pixel 5. So most of the apps on the Pixel 5 where installed automatically by PlayStore.


Now everytime after the start of Amaze on the Pixel 5 i see an empty folder…
![Screenshot_20201213-232931.png](https://user-images.githubusercontent.com/23266409/102026845-9774ad80-3da0-11eb-9eb3-a94fee676779.png)

The crash occurs when i tab on one of those…
![Screenshot_20201213-233032-01.jpeg](https://user-images.githubusercontent.com/23266409/102026855-a5c2c980-3da0-11eb-8f8a-44fd87baa471.jpeg)
![Screenshot_20201213-233617-01.jpeg](https://user-images.githubusercontent.com/23266409/102026972-79f41380-3da1-11eb-9706-9b4a2a311571.jpeg)


I will try to reset Amaze and clear all the App related user data…

![Screenshot_20201214-001904.png](https://user-images.githubusercontent.com/23266409/102027118-6b5a2c00-3da2-11eb-95ee-90311dbe18ae.png)


This seems to work! ✨

**Comment by gre0j** [comment]
Amaze is working fine now…so ist seems there was a problem with the backup/change from old to new phone. 
Maybe Google also copied the 'old' user data and settings and these files did not work in the new place.
