### ISSUE TITLE
Transaction too large

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2147]
## Exception 
* __User Action:__ UI Error
* __Request:__ Application crash 
* __Version:__ 3.5.2 
* __OS:__ Linux Android 8.1.0 - 27 
* __Device:__ U3A_PLUS_4G 
* __Model:__ 5033J 
* __Product:__ 5033J Crash log

``` 
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 813752 bytes
 at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4109)
 at android.os.Handler.handleCallback(Handler.java:790)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6666) 
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
 Caused by: android.os.TransactionTooLargeException: data parcel size 813752 bytes
 at android.os.BinderProxy.transactNative(Native Method)
 at android.os.BinderProxy.transact(Binder.java:766)
 at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4716)
 at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4093) 
... 7 more 
```

**Comment by VishalNehra** [comment]
This shouldn't be happening on 3.5.2 as we're not sending data through transactions anymore 🤔 
Maybe in AppManager? Can we confirm this?

**Comment by EmmanuelMess** [comment]
> This shouldn't be happening on 3.5.2 as we're not sending data through transactions anymore thinking
> Maybe in AppManager? Can we confirm this?

I would close this until it gets reported with more info.
