### ISSUE TITLE
Id nonexistent on MainFragment

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2149]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.2
* __OS:__ Linux Nokia/Plate2_00WW/PL2_sprout:10/QKQ1.190828.002/00WW_4_16B:user/release-keys 10 - 29
* __Device:__ PL2_sprout
* __Model:__ Nokia 6.1
* __Product:__ Plate2_00WW
Crash log

```
java.lang.IllegalArgumentException: No view found for id 0x7f0901b9 (com.amaze.filemanager:id/pager) for fragment MainFragment{7e4d7b (9857c5b7-4bd9-4211-976f-de8b30d15daf) id=0x7f0901b9}
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:875)
at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1426)
at android.app.Activity.performStart(Activity.java:7825)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3295)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7397)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

```

**Comment by VishalNehra** [comment]
Is app not even able to start? 
We should start asking people to follow the issues and respond here. 
Maybe bump up the priority to 3.5?

**Comment by EmmanuelMess** [comment]
> Is app not even able to start?
> We should start asking people to follow the issues and respond here.

I always send a link to track the issue. 

> Maybe bump up the priority to 3.5?

Do we have enough info to fix it?

**Comment by EmmanuelMess** [comment]
This happens when rotating device on AppsListFragment.

**Comment by TranceLove** [comment]
Perhaps related: https://stackoverflow.com/questions/36775564/no-view-found-for-id-xxx-when-trying-to-change-device-configuration

**Comment by VishalNehra** [comment]
@TranceLove Yep this is the issue, already working on it.
