### ISSUE TITLE
Amaze crashes when trying to extract .zip file

### ISSUE THREAD

**Issue by tegutistgut** [TeamAmaze/AmazeFileManager#2184]
**Steps to reproduce:**
_Just try to extract any .zip file. (My file was in my internal storage)_

## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.2
* __OS:__ Linux Android 10 - 29
* __Device:__ a51
* __Model:__ SM-A515F
* __Product:__ a51nseea
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
	at net.lingala.zip4j.util.Raw.readShortLittleEndian(Raw.java:57)
	at net.lingala.zip4j.core.HeaderReader.readExtraDataRecords(HeaderReader.java:471)
	at net.lingala.zip4j.core.HeaderReader.readAndSaveExtraDataRecord(HeaderReader.java:420)
	at net.lingala.zip4j.core.HeaderReader.readCentralDirectory(HeaderReader.java:338)
	at net.lingala.zip4j.core.HeaderReader.readAllHeaders(HeaderReader.java:94)
	at net.lingala.zip4j.core.ZipFile.readZipInfo(ZipFile.java:425)
	at net.lingala.zip4j.core.ZipFile.getFileHeaders(ZipFile.java:688)
	at com.amaze.filemanager.filesystem.compressed.extractcontents.helpers.ZipExtractor.extractWithFilter(ZipExtractor.java:66)
	at com.amaze.filemanager.filesystem.compressed.extractcontents.Extractor.extractEverything(Extractor.java:77)
	at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:315)
	at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:225)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

```
</details>
<hr>

**Comment by TranceLove** [comment]
Upgrade the old zip4j may work. Imply pushing #2134 to 3.5 too.
