### ISSUE TITLE
Crash stacktrace at SMB file copy 

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2189]
Getting following stacktrace at log level if I try to copy file in SMB

```
2021-01-05 10:51:44.390 26559-26559/com.amaze.filemanager.debug W/System.err: java.io.FileNotFoundException: smb:/workgroup%3Bvishalnehra:Vishal%40123@192.168.0.126/vishalnehra/Downloads/DummyFile: open failed: ENOENT (No such file or directory)
2021-01-05 10:51:44.393 26559-26559/com.amaze.filemanager.debug W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:496)
2021-01-05 10:51:44.393 26559-26559/com.amaze.filemanager.debug W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
2021-01-05 10:51:44.393 26559-26559/com.amaze.filemanager.debug W/System.err:     at com.amaze.filemanager.filesystem.FileUtil.isWritable(FileUtil.java:754)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at com.amaze.filemanager.utils.MainActivityHelper.checkFolder(MainActivityHelper.java:420)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.finishCopying(PrepareCopyTask.java:325)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.onEndDialog(PrepareCopyTask.java:275)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.onEndDialog(PrepareCopyTask.java:269)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.onPostExecute(PrepareCopyTask.java:186)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.onPostExecute(PrepareCopyTask.java:64)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:755)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at android.os.AsyncTask.access$900(AsyncTask.java:192)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at android.os.Looper.loop(Looper.java:214)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7643)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
2021-01-05 10:51:44.394 26559-26559/com.amaze.filemanager.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2021-01-05 10:51:44.399 26559-26559/com.amaze.filemanager.debug W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
```

**Comment by TranceLove** [comment]
Happened when copying a folder from device to SMB server.

**Comment by VishalNehra** [comment]
@TranceLove Yes.. it's a silent stack, but a problem nonetheless 🤔
