### ISSUE TITLE
NPE when trying to list files

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2200]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.2
* __OS:__ Linux HUAWEI/AGS2-W09EEA/HWAGS2:8.0.0/HUAWEIAGS2-W09/310(OCEC431):user/release-keys 8.0.0 - 26
* __Device:__ HWAGS2
* __Model:__ AGS2-W09
* __Product:__ AGS2-W09EEA
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:365)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.NullPointerException: pathFile.listFiles() must not be null
at com.amaze.filemanager.filesystem.root.ListFilesCommand.getFilesList(ListFilesCommand.kt:155)
at com.amaze.filemanager.filesystem.root.ListFilesCommand.listFiles(ListFilesCommand.kt:67)
at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:222)
at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:67)
at android.os.AsyncTask$2.call(AsyncTask.java:345)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 3 more

```
</details>
<hr>

PLEASE HELP. My computer doesn't recognise my external hard drive.

**Comment by VishalNehra** [comment]
@VishalNehra @TranceLove can you check this one when you get time?

**Comment by TranceLove** [comment]
So it's accessing the external hard drive without through OTG...

I used this workaround and this worked without crashing Amaze.

1. Connect hard drive to device
2. Status bar showing USB icon, indicating USB device plugged in
3. Pull down and tap the notification, opens Android's own DocumentsUI
4. Open Amaze, OTG device shows up at side bar
5. Tap the OTG entry at Amaze's side bar
6. SAF dialog triggered, prompt you to select the root of the hard drive
7. Amaze can then browse the external hard drive over OTG without problem

And for the exception itself... can do a null check.
