### ISSUE TITLE
Can't play video in VLC from samba

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#2206]
Opening a video from Amaze smb into vlc doesn't play it.

**Comment by TranceLove** [comment]
@EmmanuelMess Like the case of #1839?

**Comment by EmmanuelMess** [comment]
> @EmmanuelMess Like the case of #1839?

Probably not, I am running 7.1.2, but will check logcat.

**Comment by EmmanuelMess** [comment]
Logcat:

```
com.amaze.filemanager.debug W/art: Throwing OutOfMemoryError "Failed to allocate a 12 byte allocation with 3008 free bytes and 3008B until OOM"
com.amaze.filemanager.debug W/art: Throwing OutOfMemoryError "Failed to allocate a 48 byte allocation with 3008 free bytes and 3008B until OOM"
com.amaze.filemanager.debug W/art: Throwing OutOfMemoryError "Failed to allocate a 70396 byte allocation with 3008 free bytes and 3008B until OOM" (recursive case)
com.amaze.filemanager.debug W/art: "main" prio=5 tid=1 Runnable
com.amaze.filemanager.debug W/art:   | group="main" sCount=0 dsCount=0 obj=0x74a66268 self=0xb0f84400
com.amaze.filemanager.debug W/art:   | sysTid=21558 nice=-10 cgrp=default sched=0/0 handle=0xb420b534
com.amaze.filemanager.debug W/art:   | state=R schedstat=( 37094039227 1026523399 9471 ) utm=3479 stm=229 core=5 HZ=100
com.amaze.filemanager.debug W/art:   | stack=0xbe277000-0xbe279000 stackSize=8MB
com.amaze.filemanager.debug W/art:   | held mutexes= "mutator lock"(shared held)
com.amaze.filemanager.debug W/art:   native: #00 pc 00351f85  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
com.amaze.filemanager.debug W/art:   native: #01 pc 00332661  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+308)
com.amaze.filemanager.debug W/art:   native: #02 pc 003308ad  /system/lib/libart.so (_ZN3art6Thread21ThrowOutOfMemoryErrorEPKc+176)
com.amaze.filemanager.debug W/art:   native: #03 pc 00189e15  /system/lib/libart.so (_ZN3art2gc4Heap21ThrowOutOfMemoryErrorEPNS_6ThreadEjNS0_13AllocatorTypeE+896)
com.amaze.filemanager.debug W/art:   native: #04 pc 001922b5  /system/lib/libart.so (_ZN3art2gc4Heap22AllocateInternalWithGcEPNS_6ThreadENS0_13AllocatorTypeEbjPjS5_S5_PPNS_6mirror5ClassE+21372)
com.amaze.filemanager.debug W/art:   native: #05 pc 0010163d  /system/lib/libart.so (_ZN3art2gc4Heap24AllocObjectWithAllocatorILb1ELb1ENS_6mirror16SetLengthVisitorEEEPNS3_6ObjectEPNS_6ThreadEPNS3_5ClassEjNS0_13AllocatorTypeERKT1_+2360)
com.amaze.filemanager.debug W/art:   native: #06 pc 000e1ea9  /system/lib/libart.so (_ZN3art6mirror14PrimitiveArrayIiE5AllocEPNS_6ThreadEj+72)
com.amaze.filemanager.debug W/art:   native: #07 pc 000e1d7d  /system/lib/libart.so (_ZN3art11ClassLinker17AllocPointerArrayEPNS_6ThreadEj+24)
com.amaze.filemanager.debug W/art:   native: #08 pc 0032df7f  /system/lib/libart.so (_ZN3art30BuildInternalStackTraceVisitorILb0EE4InitEi+138)
com.amaze.filemanager.debug W/art:   native: #09 pc 0032dea3  /system/lib/libart.so (_ZNK3art6Thread24CreateInternalStackTraceILb0EEEP8_jobjectRKNS_33ScopedObjectAccessAlreadyRunnableE+118)
com.amaze.filemanager.debug W/art:   native: #10 pc 002b4d91  /system/lib/libart.so (_ZN3artL32Throwable_nativeFillInStackTraceEP7_JNIEnvP7_jclass+28)
com.amaze.filemanager.debug W/art:   native: #11 pc 0000ca85  /system/framework/arm/boot.oat (Java_java_lang_Throwable_nativeFillInStackTrace__+72)
com.amaze.filemanager.debug W/art:     at java.lang.Throwable.nativeFillInStackTrace!(Native method)
com.amaze.filemanager.debug W/art:     at java.lang.Throwable.fillInStackTrace(Throwable.java:774)
com.amaze.filemanager.debug W/art:     at java.lang.Throwable.<init>(Throwable.java:257)
com.amaze.filemanager.debug W/art:     at java.lang.Error.<init>(Error.java:70)
com.amaze.filemanager.debug W/art:     at java.lang.VirtualMachineError.<init>(VirtualMachineError.java:53)
com.amaze.filemanager.debug W/art:     at java.lang.OutOfMemoryError.<init>(OutOfMemoryError.java:58)
com.amaze.filemanager.debug W/art:     at java.lang.Throwable.nativeFillInStackTrace!(Native method)
com.amaze.filemanager.debug W/art:     at java.lang.Throwable.fillInStackTrace(Throwable.java:774)
com.amaze.filemanager.debug W/art:     at java.lang.Throwable.<init>(Throwable.java:257)
com.amaze.filemanager.debug W/art:     at java.lang.Exception.<init>(Exception.java:66)
com.amaze.filemanager.debug W/art:     at java.io.IOException.<init>(IOException.java:58)
com.amaze.filemanager.debug W/art:     at java.net.SocketException.<init>(SocketException.java:48)
com.amaze.filemanager.debug W/art:     at java.net.BindException.<init>(BindException.java:48)
com.amaze.filemanager.debug W/art:     at java.net.PlainSocketImpl.socketBind(Native method)
com.amaze.filemanager.debug W/art:     at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:368)
com.amaze.filemanager.debug W/art:     at java.net.ServerSocket.bind(ServerSocket.java:377)
com.amaze.filemanager.debug W/art:     at java.net.ServerSocket.<init>(ServerSocket.java:237)
com.amaze.filemanager.debug W/art:     at java.net.ServerSocket.<init>(ServerSocket.java:128)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.smbstreamer.StreamServer.tryBind(StreamServer.java:204)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.smbstreamer.StreamServer.<init>(StreamServer.java:170)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.smbstreamer.Streamer.<init>(Streamer.java:53)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.smbstreamer.Streamer.getInstance(Streamer.java:59)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.cloud.CloudStreamServer.tryBind(CloudStreamServer.java:262)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.cloud.CloudStreamServer.<init>(CloudStreamServer.java:188)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.cloud.CloudStreamer.<init>(CloudStreamer.java:50)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.cloud.CloudStreamer.getInstance(CloudStreamer.java:56)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.smbstreamer.StreamServer.tryBind(StreamServer.java:206)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.smbstreamer.StreamServer.<init>(StreamServer.java:170)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.smbstreamer.Streamer.<init>(Streamer.java:53)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.smbstreamer.Streamer.getInstance(Streamer.java:59)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.cloud.CloudStreamServer.tryBind(CloudStreamServer.java:262)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.cloud.CloudStreamServer.<init>(CloudStreamServer.java:188)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.cloud.CloudStreamer.<init>(CloudStreamer.java:50)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.cloud.CloudStreamer.getInstance(CloudStreamer.java:56)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.smbstreamer.StreamServer.tryBind(StreamServer.java:206)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.smbstreamer.StreamServer.<init>(StreamServer.java:170)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.smbstreamer.Streamer.<init>(Streamer.java:53)
com.amaze.filemanager.debug W/art:     at com.amaze.filemanager.filesystem.smbstreamer.Streamer.getInstance(Streamer.java:59)
```
