### ISSUE TITLE
Crash report by Thewisem

### ISSUE THREAD

**Issue by Thewisem** [TeamAmaze/AmazeFileManager#2247]
**Describe the bug**
Basically my app crashed while moving to my usb connected via charging port

**To Reproduce**
1. Click copy for any file
2. Paste it onto a usb drive connected via charging port
3. Wait for some time.

**Expected behavior**
The file to reach inside my usb drive without crasing and doing it fast for small storage

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy Tab A
 - OS: Android 7 Nougat
 - Rooted: No
 - Version: Latest on fdroid

**Additional context**
It not only crashes but takes a very long time to move a 70mb folder. Even if it did, the file would be found corrupted.
Please help

**Comment by EmmanuelMess** [comment]
We need the log, you should have gotten the prompt to send us a mail or a message via telegram to report the issue.

**Comment by Thewisem** [comment]
![Imagepipe_3](https://user-images.githubusercontent.com/74511929/105771437-677b0700-5f15-11eb-86bd-40e3aae7b26b.jpg)
![Imagepipe_2](https://user-images.githubusercontent.com/74511929/105771443-6944ca80-5f15-11eb-8d32-40dc40f577fb.jpg)
Some examples before the crash

**Comment by Thewisem** [comment]
And No it isn't because my flash is dead. Quite contrary, my flash could have constant speed

**Comment by Thewisem** [comment]
:)

**Comment by Thewisem** [comment]
## Issue explanation (write below this line)



## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.3
* __OS:__ Linux Android 7.1.1 - 25
* __Device:__ gt5note10lte
* __Model:__ SM-P555
* __Product:__ gt5note10ltexx
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.ui.activities.MainActivity}: java.lang.IllegalArgumentException: No view found for id 0x7f0901b9 (com.amaze.filemanager:id/pager) for fragment MainFragment{9c68f5 (d76b326c-1c17-4321-a72c-bb96c9a6705d) id=0x7f0901b9}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3003)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5006)
	at android.app.ActivityThread.-wrap21(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1665)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.lang.IllegalArgumentException: No view found for id 0x7f0901b9 (com.amaze.filemanager:id/pager) for fragment MainFragment{9c68f5 (d76b326c-1c17-4321-a72c-bb96c9a6705d) id=0x7f0901b9}
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:875)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
	at android.app.Activity.performStart(Activity.java:6994)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2956)
	... 10 more

```
</details>
<hr>

**Comment by Thewisem** [comment]
The device is wrong I am using a tablet not a phone

**Comment by Thewisem** [comment]
![Imagepipe_4](https://user-images.githubusercontent.com/74511929/105774111-baef5400-5f19-11eb-8cf2-1433858c6df9.jpg)
Sometimes this happens as well but not all the time
Hope this helps :)
