### ISSUE TITLE
app/ui crash

### ISSUE THREAD

**Issue by liangxuliang** [TeamAmaze/AmazeFileManager#2316]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.3
* __OS:__ Linux realme/RMX2117/RMX2117CN:10/QP1A.190711.020/1607583523:user/release-keys 10 - 29
* __Device:__ RMX2117CN
* __Model:__ RMX2117
* __Product:__ RMX2117
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to resume activity {com.amaze.filemanager/com.amaze.filemanager.ui.activities.MainActivity}: java.lang.IllegalStateException: Unexpected failure to classify SearchResult: SearchResult{key=/storage/emulated/0/Download, nodeFound=Node{edge=/DCIM, value=1, edges=[]}, charsMatched=21, charsMatchedInNodeFound=2, parentNode=Node{edge=/storage/emulated/0, value=0, edges=[Node{edge=/DCIM, value=1, edges=[]}]}, parentNodesParent=Node{edge=, value=null, edges=[Node{edge=/storage/emulated/0, value=0, edges=[Node{edge=/DCIM, value=1, edges=[]}]}]}, classification=null}
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4561)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4600)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:192)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:113)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2259)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.IllegalStateException: Unexpected failure to classify SearchResult: SearchResult{key=/storage/emulated/0/Download, nodeFound=Node{edge=/DCIM, value=1, edges=[]}, charsMatched=21, charsMatchedInNodeFound=2, parentNode=Node{edge=/storage/emulated/0, value=0, edges=[Node{edge=/DCIM, value=1, edges=[]}]}, parentNodesParent=Node{edge=, value=null, edges=[Node{edge=/storage/emulated/0, value=0, edges=[Node{edge=/DCIM, value=1, edges=[]}]}]}, classification=null}
	at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree$SearchResult.classify(ConcurrentRadixTree.java:989)
	at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree$SearchResult.<init>(ConcurrentRadixTree.java:969)
	at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree.searchTree(ConcurrentRadixTree.java:932)
	at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree.putInternal(ConcurrentRadixTree.java:456)
	at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree.put(ConcurrentRadixTree.java:83)
	at com.googlecode.concurrenttrees.radixinverted.ConcurrentInvertedRadixTree.put(ConcurrentInvertedRadixTree.java:185)
	at com.amaze.filemanager.utils.DataUtils.putDrawerMetadata(DataUtils.java:422)
	at com.amaze.filemanager.ui.views.drawer.Drawer.addNewItem(Drawer.java:608)
	at com.amaze.filemanager.ui.views.drawer.Drawer.refreshDrawer(Drawer.java:405)
	at com.amaze.filemanager.ui.activities.MainActivity.onResume(MainActivity.java:1184)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
	at android.app.Activity.performResume(Activity.java:8143)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4551)
	... 11 more

```
</details>
<hr>

**Comment by TranceLove** [comment]
Possibly related to #2217, fixed by #2227.
