### ISSUE TITLE
Random crash when unlock screen

### ISSUE THREAD

**Issue by Bambooin** [TeamAmaze/AmazeFileManager#2435]
**Describe the bug**
Random crash when unlock screen.

**To Reproduce**
Can't reproduce.

**Expected behavior**
Amaze should work well.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 7 Pro]
 - OS: [LineageOS 16.0]
 -  Rooted: [No]
 - Version: [v3.6.0]

**Additional context**
```
java.lang.IllegalArgumentException: No view found for id 0x7f0901b9 (com.amaze.filemanager:id/pager) for fragment MainFragment{8894f54 (ebda2568-7caa-4753-abcb-0bae56070b43) id=0x7f0901b9}
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:875)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7165)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4782)
	at android.app.ActivityThread.access$3200(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1826)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by VishalNehra** [comment]
Duplicate to #2149
