### ISSUE TITLE
Crash on date parse for file listing

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2460]
## Exception
* User Action: UI Error
* Request: Application crash
* Version: 3.5.3
* OS: Linux Android 10 - 29
* Device: OnePlus7TPro
* Model: HD1913
* Product: OnePlus7TPro
<details><summary><b>Crash log </b></summary><p>

java.lang.RuntimeException: An error occurred while executing doInBackground()
 at android.os.AsyncTask$4.done(AsyncTask.java:399)
 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
 at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
 at java.util.concurrent.FutureTask.run(FutureTask.java:271)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NumberFormatException: For input string: "May"
 at java.lang.Long.parseLong(Long.java:594)
 at java.lang.Long.parseLong(Long.java:636)
 at com.amaze.filemanager.filesystem.files.FileUtils.parseName(FileUtils.java:756)
 at com.amaze.filemanager.filesystem.root.ListFilesCommand.parseStringForHybridFile(ListFilesCommand.kt:201)
 at com.amaze.filemanager.filesystem.root.ListFilesCommand.listFiles(ListFilesCommand.kt:59)
 at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:223)
 at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:67)
 at android.os.AsyncTask$3.call(AsyncTask.java:378)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 ... 3 more

</details>
<hr>

**Comment by VishalNehra** [comment]
Dupe #2635
