### ISSUE TITLE
When I connect my OTG with a mouse the application gave me this error 

### ISSUE THREAD

**Issue by jsbautista** [TeamAmaze/AmazeFileManager#2470]
## Issue explanation (write below this line)

when I connect my OTG with a mouse the app gave me this error

## Exception
* _User Action:_ UI Error
* _Request:_ Application crash
* _Version:_ 3.5.3
* _OS:_ Linux samsung/hero2ltexx/hero2lte:8.0.0/R16NW/G935FXXU3ERKH:user/release-keys 8.0.0 - 26
* _Device:_ hero2lte
* _Model:_ SM-G935F
* _Product:_ hero2ltexx
<details><summary><b>Crash log </b></summary><p>

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.hardware.usb.action.USB_DEVICE_ATTACHED flg=0x11000010 (has extras) } in com.amaze.filemanager.ui.activities.MainActivity$2@32bc61b
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52226(LoadedApk.java:1329)
	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(Unknown Source:4)
	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.amaze.filemanager.ui.activities.MainActivity$2.onReceive(MainActivity.java:1247)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52226(LoadedApk.java:1319)
	... 9 more

</details>
<hr>
## Issue explanation (write below this line)

when I connect my OTG with a mouse the app gave me this error

## Exception
* _User Action:_ UI Error
* _Request:_ Application crash
* _Version:_ 3.5.3
* _OS:_ Linux samsung/hero2ltexx/hero2lte:8.0.0/R16NW/G935FXXU3ERKH:user/release-keys 8.0.0 - 26
* _Device:_ hero2lte
* _Model:_ SM-G935F
* _Product:_ hero2ltexx
<details><summary><b>Crash log </b></summary><p>

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.hardware.usb.action.USB_DEVICE_ATTACHED flg=0x11000010 (has extras) } in com.amaze.filemanager.ui.activities.MainActivity$2@32bc61b
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52226(LoadedApk.java:1329)
	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(Unknown Source:4)
	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.amaze.filemanager.ui.activities.MainActivity$2.onReceive(MainActivity.java:1247)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52226(LoadedApk.java:1319)
	... 9 more

</details>
<hr>

**Comment by TranceLove** [comment]
Looks like the same as #2109.
