### ISSUE TITLE
Amaze crashed when viewing an apk

### ISSUE THREAD

**Issue by DarkShadowHunter** [TeamAmaze/AmazeFileManager#2471]
## Issue explanation
I was viewing an apk and amaze crashed.

## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.3
* __OS:__ Linux motorola/pettyl/pettyl:8.1.0/OPG28.54-53-8/55beb:user/release-keys 8.1.0 - 27
* __Device:__ pettyl
* __Model:__ moto e5 play
* __Product:__ pettyl
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at net.lingala.zip4j.util.Raw.readShortLittleEndian(Raw.java:57)
	at net.lingala.zip4j.core.HeaderReader.readExtraDataRecords(HeaderReader.java:468)
	at net.lingala.zip4j.core.HeaderReader.readAndSaveExtraDataRecord(HeaderReader.java:420)
	at net.lingala.zip4j.core.HeaderReader.readCentralDirectory(HeaderReader.java:338)
	at net.lingala.zip4j.core.HeaderReader.readAllHeaders(HeaderReader.java:94)
	at net.lingala.zip4j.core.ZipFile.readZipInfo(ZipFile.java:425)
	at net.lingala.zip4j.core.ZipFile.getFileHeaders(ZipFile.java:688)
	at com.amaze.filemanager.asynchronous.asynctasks.compress.ZipHelperTask.addElements(ZipHelperTask.java:77)
	at com.amaze.filemanager.asynchronous.asynctasks.compress.CompressedHelperTask.doInBackground(CompressedHelperTask.java:58)
	at com.amaze.filemanager.asynchronous.asynctasks.compress.CompressedHelperTask.doInBackground(CompressedHelperTask.java:37)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

```
</details>
<hr>

**Comment by EmmanuelMess** [comment]
90% sure this is a dupe
