### ISSUE TITLE
App crashes when list is loading and quickly open settings screen

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2514]
## Exception
* User Action: UI Error
* Request: Application crash
* Version: 3.5.3
* OS: Linux Android 8.1.0 - 27
* Device: TB-8704X
* Model: Lenovo TB-8704X
* Product: TB-8704X
<details><summary><b>Crash log </b></summary><p>

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.getColor(int)' on a null object reference
 at com.amaze.filemanager.utils.Utils.getColor(Utils.java:133)
 at com.amaze.filemanager.ui.fragments.MainFragment.initNoFileLayout(MainFragment.java:974)
 at com.amaze.filemanager.ui.fragments.MainFragment.reloadListElements(MainFragment.java:1108)
 at com.amaze.filemanager.ui.fragments.MainFragment.setListElements(MainFragment.java:1003)
 at com.amaze.filemanager.ui.fragments.MainFragment.lambda$loadlist$3(MainFragment.java:956)
 at com.amaze.filemanager.ui.fragments.MainFragment.lambda$loadlist$3$MainFragment(Unknown Source:0)
 at com.amaze.filemanager.ui.fragments.-$$Lambda$MainFragment$9qQv21X8JwPlLXi_cDXfu4p-_VI.onAsyncTaskFinished(Unknown Source:8)
 at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:270)
 at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:67)
 at android.os.AsyncTask.finish(AsyncTask.java:695)
 at android.os.AsyncTask.-wrap1(Unknown Source:0)
 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6518)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

</details>
<hr>

**Comment by Enugurupranava2002** [comment]
I want to work on this issue can I please get assigned
