### ISSUE TITLE
 Crash when unlock screen

### ISSUE THREAD

**Issue by Bambooin** [TeamAmaze/AmazeFileManager#2520]
**Describe the bug**
Last recent build crash.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.ui.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amaze.filemanager.ui.views.appbar.AppBar.setTitle(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amaze.filemanager.ui.views.appbar.AppBar.setTitle(int)' on a null object reference
	at com.amaze.filemanager.ui.fragments.FtpServerFragment.onCreate(FtpServerFragment.kt:122)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2936)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:472)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:120)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1636)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3112)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3045)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:272)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at com.amaze.filemanager.ui.activities.superclasses.PreferenceActivity.onCreate(PreferenceActivity.java:59)
	at com.amaze.filemanager.ui.activities.superclasses.ThemedActivity.onCreate(ThemedActivity.java:55)
	at com.amaze.filemanager.ui.activities.MainActivity.onCreate(MainActivity.java:309)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 11 more

```

**Comment by EmmanuelMess** [comment]
Was this fixed?

**Comment by Bambooin** [comment]
Not seen it for long time in my daily build

This exception maybe trigger by `Dark mode` switch of Android.
