### ISSUE TITLE
Crashes when trying to put MainFragments in savedInstanceState of TabFragment

### ISSUE THREAD

**Issue by Thewisem** [TeamAmaze/AmazeFileManager#2621]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.0
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 7.1.1 - 25
* __Device:__ gt5note10lte
* __Model:__ SM-P555
* __Product:__ gt5note10ltexx
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{47aff76} (f99a665c-5dc2-4c16-ac8b-3ef22c78bf18)} is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:937)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:243)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3138)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:680)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:646)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:177)
	at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:2641)
	at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:152)
	at androidx.fragment.app.FragmentActivity$1.saveState(FragmentActivity.java:133)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.java:227)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.java:74)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:324)
	at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:544)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1226)
	at android.app.Activity.performSaveInstanceState(Activity.java:1507)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1308)
	at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:5045)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4313)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4372)
	at android.app.ActivityThread.-wrap28(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1693)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

```
</details>
<hr>

**Comment by VishalNehra** [comment]
Duplicate #1555
