### ISSUE TITLE
Crash when extract .tar.gz file

### ISSUE THREAD

**Issue by Bambooin** [TeamAmaze/AmazeFileManager#2647]
**Describe the bug**
Crash when extract tar.gz file

An exmaple fie:
[gz.tar.gz](https://github.com/TeamAmaze/AmazeFileManager/files/6680325/gz.tar.gz)

**To Reproduce**
1. Click .tar.gz file
2. Click extract button
3. Amaze crash

**Expected behavior**
File is extracted.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Redmi]
 - OS: [Lineage OS 16.0]
 - Rooted: [No]
 - Version: [last commit build]

**Additional context**
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchMethodException: <init> [class java.io.InputStream]
	at java.lang.Class.getConstructor0(Class.java:2327)
	at java.lang.Class.getDeclaredConstructor(Class.java:2166)
	at com.amaze.filemanager.filesystem.compressed.extractcontents.helpers.AbstractCompressedTarArchiveExtractor.<init>(AbstractCompressedTarArchiveExtractor.kt:43)
	at com.amaze.filemanager.filesystem.compressed.extractcontents.helpers.GzipExtractor.<init>(GzipExtractor.kt:34)
	at com.amaze.filemanager.filesystem.compressed.CompressedHelper.getExtractorInstance(CompressedHelper.java:91)
	at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:274)
	at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:227)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

```

**Comment by Bambooin** [comment]
Similar issue #2642 

Amaze crashes when I extracted my package yesterday.

So I make an simple tar.gz file for test, and it still crash.

**Comment by Bambooin** [comment]
Thanks for your work.
