### ISSUE TITLE
Amaze file explorer 

### ISSUE THREAD

**Issue by Andrew4258** [TeamAmaze/AmazeFileManager#2670]
-------------------------------------
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=content://com.amaze.filemanager/storage_root/system/bin/xbin typ=*/* flg=0x1 cmp=com.android.apps.tag/.TagViewer } from ProcessRecord{cd7fde4 17588:com.amaze.filemanager/u0a538} (pid=17588, uid=10538) requires android.permission.NFC
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
	at android.os.Parcel.createException(Parcel.java:2369)
	at android.os.Parcel.readException(Parcel.java:2352)
	at android.os.Parcel.readException(Parcel.java:2294)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:4259)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1723)
	at android.app.Activity.startActivityForResult(Activity.java:5377)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:584)
	at android.app.Activity.startActivityForResult(Activity.java:5335)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:570)
	at android.app.Activity.startActivity(Activity.java:5721)
	at android.app.Activity.startActivity(Activity.java:5674)
	at com.amaze.filemanager.adapters.AppsAdapter.startActivityForRowItem(AppsAdapter.java:192)
	at com.amaze.filemanager.adapters.AppsAdapter.lambda$getView$0(AppsAdapter.java:166)
	at com.amaze.filemanager.adapters.AppsAdapter.lambda$getView$0$AppsAdapter(Unknown Source:0)
	at com.amaze.filemanager.adapters.-$$Lambda$AppsAdapter$O2jRE_NHwDMQ5NBArFexYNoqVHk.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:8160)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1336)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1260)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:894)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1710)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1560)

**Comment by VishalNehra** [comment]
Duplicate issue
