### ISSUE TITLE
can't open zip filea from LINE

### ISSUE THREAD

**Issue by azumukupoe** [TeamAmaze/AmazeFileManager#2683]
## Issue explanation (write below this line)

can't open zip files from LINE

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.1
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 9 - 28
* __Device:__ SC-03J
* __Model:__ SC-03J
* __Product:__ SC-03J
<details><summary><b>Crash log </b></summary><p>

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:2036)
	at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.onActivityCreated(CompressedExplorerFragment.java:221)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2983)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:577)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```
</details>
<hr>

**Comment by VishalNehra** [comment]
Dupe #2650
