### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by vondak007** [TeamAmaze/AmazeFileManager#2688]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.3
* __OS:__ Linux Android 10 - 29
* __Device:__ S6501LA
* __Model:__ S6501L
* __Product:__ G5
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'boolean com.amaze.filemanager.adapters.data.LayoutElementParcelable.isBack' on a null object reference
	at com.amaze.filemanager.adapters.RecyclerAdapter.setItems(RecyclerAdapter.java:387)
	at com.amaze.filemanager.adapters.RecyclerAdapter.setItems(RecyclerAdapter.java:370)
	at com.amaze.filemanager.asynchronous.handlers.FileHandler.handleMessage(FileHandler.java:91)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

```
</details>
<hr>

**Comment by VishalNehra** [comment]
Dupe #2224
