### ISSUE TITLE
Renaming in system folder crashes app

### ISSUE THREAD

**Issue by wolverine2k** [TeamAmaze/AmazeFileManager#2731]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.1
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 11 - 30
* __Device:__ o1s
* __Model:__ SM-G991B
* __Product:__ o1sxeea
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.amaze.filemanager.exceptions.ShellCommandInvalidException: mv "/system/priv-app/SamsungPass/SamsungPass.apk" "/system/priv-app/SamsungPass/SamsungPass.apj" , error code - 1
	at com.amaze.filemanager.filesystem.root.base.IRootCommand.runShellCommandToList(IRootCommand.kt:54)
	at com.amaze.filemanager.filesystem.root.RenameFileCommand.renameFile(RenameFileCommand.kt:41)
	at com.amaze.filemanager.filesystem.Operations$3.doInBackground(Operations.java:550)
	at com.amaze.filemanager.filesystem.Operations$3.doInBackground(Operations.java:381)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
</details>
<hr>

**Comment by VishalNehra** [comment]
Is this a one time error or is always happening while renaming any other file in root?

Also can you manually try to execute this command and give the error output from terminal?
mv "/system/priv-app/SamsungPass/SamsungPass.apk" "/system/priv-app/SamsungPass/SamsungPass.apj"

**Comment by EmmanuelMess** [comment]
Dupe #2238
