### ISSUE TITLE
Crease report

### ISSUE THREAD

**Issue by krunalpatel3** [TeamAmaze/AmazeFileManager#2763]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.9
* __OS:__ Linux Android 11 - 30
* __Device:__ generic_x86_arm
* __Model:__ sdk_gphone_x86
* __Product:__ sdk_gphone_x86
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalArgumentException: Volume external_primary not found
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
	at android.content.ContentResolver.query(ContentResolver.java:1183)
	at android.content.ContentResolver.query(ContentResolver.java:1115)
	at android.content.ContentResolver.query(ContentResolver.java:1071)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listApks(LoadFilesListTask.java:412)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:174)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:68)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
@krunalpatel3 Thanks for reporting!

But, that error report is not from the official app.

Get the official versions from here

Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases
