### ISSUE TITLE
 NPE when clicking properties on directory in SFTP mount

### ISSUE THREAD

**Issue by DuckDuckWhale** [TeamAmaze/AmazeFileManager#2779]
## Issue explanation

NPE when clicking properties on directory in SFTP mount

## Exception
* __App Name:__ Amaze 文件管理器
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.1
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 10 - 29
* __Device:__ HWELE
* __Model:__ ELE-AL00
* __Product:__ ELE-AL00
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:429)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at com.amaze.filemanager.filesystem.HybridFile.isDirectory(HybridFile.java:463)
	at com.amaze.filemanager.asynchronous.asynctasks.CountItemsOrAndSizeTask.doInBackground(CountItemsOrAndSizeTask.java:57)
	at com.amaze.filemanager.asynchronous.asynctasks.CountItemsOrAndSizeTask.doInBackground(CountItemsOrAndSizeTask.java:37)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
</details>
<hr>

**Comment by EmmanuelMess** [comment]
ping @TranceLove

**Comment by TranceLove** [comment]
It looks like the `stat()` call failed on the server, causing `IOException` that caused code to return `null` instead of `Boolean`.

https://github.com/TeamAmaze/AmazeFileManager/blob/f1433d0615bbad9f88a7131c737d45c3d102f3d8/app/src/main/java/com/amaze/filemanager/filesystem/HybridFile.java#L463-L480

https://github.com/TeamAmaze/AmazeFileManager/blob/f1433d0615bbad9f88a7131c737d45c3d102f3d8/app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshClientUtils.java#L86-L97

While I can make a band-it fix to trap the `IOException` instead of just `SFTPException`, it would be nice to know more about the crash, like
- what SSH server are you using, is it the de-facto OpenSSH, Dropbear, or the less common Bitvise, ssh.com, etc
- which folder you were looking at when the crash happened

**Comment by DuckDuckWhale** [comment]
I'm using just regular OpenSSH on Ubuntu 20.04 LTS (ARM) and opening a folder in a mount point of an external hard drive. SSHing and `ls` and `sftp` and `ls` both work (although the later output is something like `-rw-r--r--    ? 0        0               0 Sep 14 20:10 file`) so I'm not sure why it would fail in Amaze. Does a high latency (1-2s) play a role?

**Comment by VishalNehra** [comment]
> I'm using just regular OpenSSH on Ubuntu 20.04 LTS (ARM) and opening a folder in a mount point of an external hard drive. SSHing and `ls` and `sftp` and `ls` both work (although the later output is something like `-rw-r--r-- ? 0 0 0 Sep 14 20:10 file`) so I'm not sure why it would fail in Amaze. Does a high latency (1-2s) play a role?

Does this always fail on a directory or was just one time issue?

**Comment by DuckDuckWhale** [comment]
Upon further testing, this always fails when clicking property of any directory.

<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:429)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at com.amaze.filemanager.filesystem.HybridFile.getTotal(HybridFile.java:692)
	at com.amaze.filemanager.filesystem.files.FileUtils.getSpaces(FileUtils.java:550)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFolderSpaceDataTask.doInBackground(LoadFolderSpaceDataTask.java:85)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFolderSpaceDataTask.doInBackground(LoadFolderSpaceDataTask.java:53)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
</details>

I've also noticed that when I click into any directory the content is always empty, and upon refreshing a toast would pop up saying something like `Can't read directory: ssh://$address/ - null` (and the title address is `ssh://$address//dir` instead of `ssh://$address/dir` somehow, and if I then use the back gesture the app would crash. Should I file another bug report, or is this related in some way?

<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: The callable returned a null value
	at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```
</details>

**Comment by VishalNehra** [comment]
No need to create another bug. Thanks for testing. This helps a lot.

**Comment by VishalNehra** [comment]
> SSHing and `ls` and `sftp` and `ls` both work (although the later output is something like `-rw-r--r-- ? 0 0 0 Sep 14 20:10 file`)

Whatt's the output of `ls` and `stat` for directories?

**Comment by DuckDuckWhale** [comment]
SSH:

```
user@host:/$ ls -al usr
total 80
drwxr-xr-x  12 root root  4096 Apr 27 02:10 .
drwxr-xr-x  19 root root  4096 Aug 31 23:10 ..
drwxr-xr-x   2 root root 24576 Sep 15 06:20 bin
drwxr-xr-x   2 root root  4096 Aug 18 07:12 config
drwxr-xr-x   2 root root  4096 Apr 15  2020 games
drwxr-xr-x   7 root root  4096 Jun 11 04:18 include
drwxr-xr-x  84 root root  4096 Aug 31 01:49 lib
drwxr-xr-x   3 root root  4096 Jun 29  2020 libexec
drwxr-xr-x  10 root root  4096 Apr 23  2020 local
drwxr-xr-x   2 root root 12288 Sep  2 06:24 sbin
drwxr-xr-x 122 root root  4096 Aug 18 07:12 share
drwxr-xr-x   6 root root  4096 Aug 19 06:04 src
user@host:/$ stat usr
  File: usr
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: b302h/45826d    Inode: 1481        Links: 12
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-09-15 07:37:53.483052865 +0000
Modify: 2021-04-27 02:10:04.570335347 +0000
Change: 2021-04-27 02:10:04.570335347 +0000
 Birth: -
```

SFTP:
```
Connected to host.
sftp> cd /usr
sftp> ls -al
drwxr-xr-x   12 root     root         4096 Apr 27 02:10 .
drwxr-xr-x   19 root     root         4096 Aug 31 23:10 ..
drwxr-xr-x    2 root     root        24576 Sep 15 06:20 bin
drwxr-xr-x    2 root     root         4096 Aug 18 07:12 config
drwxr-xr-x    2 root     root         4096 Apr 15  2020 games
drwxr-xr-x    7 root     root         4096 Jun 11 04:18 include
drwxr-xr-x   84 root     root         4096 Aug 31 01:49 lib
drwxr-xr-x    3 root     root         4096 Jun 29  2020 libexec
drwxr-xr-x   10 root     root         4096 Apr 23  2020 local
drwxr-xr-x    2 root     root        12288 Sep  2 06:24 sbin
drwxr-xr-x  122 root     root         4096 Aug 18 07:12 share
drwxr-xr-x    6 root     root         4096 Aug 19 06:04 src
sftp> stat .
Invalid command
```

Don't remember how I got the `? 0 0 0` output but app crashes the same way.
