### ISSUE TITLE
UI Error, Application crash

### ISSUE THREAD

**Issue by fenilgmehta** [TeamAmaze/AmazeFileManager#2823]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.1
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 10 - 29
* __Device:__ santoni
* __Model:__ Redmi 4
* __Product:__ revengeos_santoni
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Unexpected failure to classify SearchResult: SearchResult{key=/storage/emulated/0, nodeFound=Node{edge=/storage/emulated/0, value=1, edges=[]}, charsMatched=19, charsMatchedInNodeFound=19, parentNode=Node{edge=, value=null, edges=[Node{edge=/storage/emulated/0, value=1, edges=[]}, Node{edge=0, value=1, edges=[]}]}, parentNodesParent=null, classification=null}
	at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree$SearchResult.classify(ConcurrentRadixTree.java:989)
	at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree$SearchResult.<init>(ConcurrentRadixTree.java:969)
	at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree.searchTree(ConcurrentRadixTree.java:932)
	at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree.putInternal(ConcurrentRadixTree.java:456)
	at com.googlecode.concurrenttrees.radix.ConcurrentRadixTree.put(ConcurrentRadixTree.java:83)
	at com.googlecode.concurrenttrees.radixinverted.ConcurrentInvertedRadixTree.put(ConcurrentInvertedRadixTree.java:185)
	at com.amaze.filemanager.utils.DataUtils.setPathAsGridOrList(DataUtils.java:384)
	at com.amaze.filemanager.ui.activities.MainActivity.lambda$onOptionsItemSelected$14(MainActivity.java:1176)
	at com.amaze.filemanager.ui.activities.MainActivity.lambda$onOptionsItemSelected$14$MainActivity(Unknown Source:0)
	at com.amaze.filemanager.ui.activities.-$$Lambda$MainActivity$U7QdcyrdxcTYMNcrSXdx4X5AJWU.apply(Unknown Source:6)
	at com.amaze.filemanager.ui.activities.MainActivity.executeWithMainFragment(MainActivity.java:2253)
	at com.amaze.filemanager.ui.activities.MainActivity.onOptionsItemSelected(MainActivity.java:1068)
	at android.app.Activity.onMenuItemSelected(Activity.java:4155)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:340)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1192)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3200)
	at android.widget.AbsListView$3.run(AbsListView.java:4118)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7357)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>
<hr>

**Comment by VishalNehra** [comment]
Dupe #2383
