### ISSUE TITLE
Crash when amaze cloud plugin is installed and migrate from v3.6.1 to v3.6.2

### ISSUE THREAD

**Issue by VishalNehra** [TeamAmaze/AmazeFileManager#2856]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 11 - 30
* __Device:__ OnePlus9R
* __Model:__ LE2101
* __Product:__ OnePlus9R_IND
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
 at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
 at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
 at java.util.concurrent.FutureTask.run(FutureTask.java:271)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalArgumentException: the bind value at index 2 is null
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
 at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
 at android.content.ContentResolver.query(ContentResolver.java:1202)
 at android.content.ContentResolver.query(ContentResolver.java:1126)
 at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
 at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
 at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:41)
 at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
 at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
 at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
 at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 ... 3 more

```
</details>
<hr>

**Comment by VishalNehra** [comment]
2021-09-30 22:20:47.829 13605-22343/? W/ContentProvider: Normalized content://com.amaze.cloud.provider//keys.db/secret_keys to content://com.amaze.cloud.provider/keys.db/secret_keys to avoid possible security issues
2021-09-30 22:20:47.831 13605-22343/? E/sqlite3_android: [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK

**Comment by VishalNehra** [comment]
@VishalNehra this one
