### ISSUE TITLE
Add support for WSA (Windows Subsystem for Android) 

### ISSUE THREAD

**Issue by richardnassour** [TeamAmaze/AmazeFileManager#2969]
## Issue explanation (write below this line)
I installed Amaze on WSA (Windows Subsystem for Android) and the app crashed on launch, showing me the error report below.

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 11 - 30
* __Device:__ redfin
* __Model:__ Pixel 5
* __Product:__ redfin
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to resume activity {com.amaze.filemanager/com.amaze.filemanager.ui.activities.MainActivity}: java.lang.NullPointerException: null cannot be cast to non-null type android.hardware.usb.UsbManager
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4438)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: null cannot be cast to non-null type android.hardware.usb.UsbManager
	at com.amaze.filemanager.utils.OTGUtil.getMassStorageDevicesConnected(OTGUtil.kt:198)
	at com.amaze.filemanager.ui.activities.MainActivity.updateUsbInformation(MainActivity.java:1290)
	at com.amaze.filemanager.ui.activities.MainActivity.onResume(MainActivity.java:1282)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
	at android.app.Activity.performResume(Activity.java:8129)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4428)
	... 11 more

```
</details>
<hr>

**Comment by EmmanuelMess** [comment]
Dupe #2955

**Comment by EmmanuelMess** [comment]
Can you please test an APK for us? [app-play-debug.zip](https://github.com/TeamAmaze/AmazeFileManager/files/7446577/app-play-debug.zip)

Please report if you keep finding this bug and if you find any others please create issues for them, thanks!

**Comment by richardnassour** [comment]
> @richardnassour Can you please test an APK for us? [app-play-debug.zip](https://github.com/TeamAmaze/AmazeFileManager/files/7446577/app-play-debug.zip)
> 
> Please report if you keep finding this bug and if you find any others please create issues for them, thanks!

It opened this time, but crashed again when I responded to the "**Grant SAF access**" prompt.
I recorded it on video.
https://user-images.githubusercontent.com/33163707/139574857-70d81701-5351-40f1-81c2-dc7bde1a96c9.mp4
Error report:
https://pastebin.com/yH7uNhYC

**Comment by VishalNehra** [comment]
Reopening this in response to adding support for this. Temporary bypassing the crash should be tracked with #2955

**Comment by EmmanuelMess** [comment]
> > @richardnassour Can you please test an APK for us? [app-play-debug.zip](https://github.com/TeamAmaze/AmazeFileManager/files/7446577/app-play-debug.zip)
> > Please report if you keep finding this bug and if you find any others please create issues for them, thanks!
> 
> It opened this time, but crashed again when I responded to the "**Grant SAF access**" prompt. I recorded it on video. [user-images.githubusercontent.com/33163707/139574857-70d81701-5351-40f1-81c2-dc7bde1a96c9.mp4](https://user-images.githubusercontent.com/33163707/139574857-70d81701-5351-40f1-81c2-dc7bde1a96c9.mp4) Error report: [pastebin.com/yH7uNhYC](https://pastebin.com/yH7uNhYC)

That error is already being tracked  #2876 and has a fixing PR.

I will however create a new issue for fixing the fact that there are no storages in WSA.
