### ISSUE TITLE
Fix emulator tests

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#3021]
It looks like emulator tests are now failing. These should be fixed so we can use emulator from Github Actions to test.

**Comment by EmmanuelMess** [comment]
These are broken again.

**Comment by EmmanuelMess** [comment]
>  error[E0463]: can't find crate for `core`
>   |
>   = note: the `armv7-linux-androideabi` target may not be installed
>   = help: consider downloading the target with `rustup target add armv7-linux-androideabi`

From the logs.

**Comment by EmmanuelMess** [comment]
The emulator issues is replicable on the same API version emulator on PC. It seems to be some issue with the swipe action from Espresso.

**Comment by EmmanuelMess** [comment]
It seems that the failure persists.

**Comment by EmmanuelMess** [comment]
Looks like the database isn't correctly saving the SFTP entries:
```
emulator-5554 - 9 Tests 1/35 completed. (0 skipped) (0 failed)
04-19 02:33:33.165  3164  3185 E TestRunner: failed: testEncodeEncryptUri1(com.amaze.filemanager.database.UtilsHandlerTest)
04-19 02:33:33.166  3164  3185 E TestRunner: ----- begin exception -----
04-19 02:33:33.166  3164  3185 E TestRunner: org.awaitility.core.ConditionTimeoutException: Condition com.amaze.filemanager.database.UtilsHandlerTest$$ExternalSyntheticLambda0 was not fulfilled within 10 seconds.
04-19 02:33:33.166  3164  3185 E TestRunner: 	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:145)
04-19 02:33:33.166  3164  3185 E TestRunner: 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:79)
04-19 02:33:33.166  3164  3185 E TestRunner: 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:27)
04-19 02:33:33.166  3164  3185 E TestRunner: 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:902)
04-19 02:33:33.166  3164  3185 E TestRunner: 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:860)
04-19 02:33:33.166  3164  3185 E TestRunner: 	at com.amaze.filemanager.database.UtilsHandlerTest.performEncryptUriTest(UtilsHandlerTest.java:132)
04-19 02:33:33.166  3164  3185 E TestRunner: 	at com.amaze.filemanager.database.UtilsHandlerTest.testEncodeEncryptUri1(UtilsHandlerTest.java:72)

```

`testEncodeEncryptUri1` to `testEncodeEncryptUri4` all fail similarly.
