### ISSUE TITLE
FTP server with SSL enabled not functioning on Android 4.4

### ISSUE THREAD

**Issue by TranceLove** [TeamAmaze/AmazeFileManager#3029]
Running on GPD XD running LegacyROM (4.4.4), connect to Amaze's FTP server using Filezilla failed. Logcat said

```
2021-11-20 16:58:30.419 2492-3009/com.amaze.filemanager.debug W/DefaultExceptionMonitor: Unexpected exception.
    org.apache.mina.core.filterchain.IoFilterLifeCycleException: onPreAdd(): sslFilter:SslFilter in (0x0000000A: nio socket, server, /192.168.191.191:60972 => /192.168.191.201:2211)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.register(DefaultIoFilterChain.java:383)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.addLast(DefaultIoFilterChain.java:189)
        at org.apache.mina.core.filterchain.DefaultIoFilterChainBuilder.buildFilterChain(DefaultIoFilterChainBuilder.java:496)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.addNow(AbstractPollingIoProcessor.java:512)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.handleNewSessions(AbstractPollingIoProcessor.java:487)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$400(AbstractPollingIoProcessor.java:68)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1111)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.IllegalArgumentException: TLS_ECDH_ECDSA_WITH_RC4_128_SHA is not supported.
        at com.android.org.conscrypt.SSLParametersImpl.setEnabledCipherSuites(SSLParametersImpl.java:237)
        at com.android.org.conscrypt.SSLEngineImpl.setEnabledCipherSuites(SSLEngineImpl.java:220)
        at org.apache.mina.filter.ssl.SslHandler.init(SslHandler.java:175)
        at org.apache.mina.filter.ssl.SslFilter.onPreAdd(SslFilter.java:445)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.register(DefaultIoFilterChain.java:381)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.addLast(DefaultIoFilterChain.java:189) 
        at org.apache.mina.core.filterchain.DefaultIoFilterChainBuilder.buildFilterChain(DefaultIoFilterChainBuilder.java:496) 
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.addNow(AbstractPollingIoProcessor.java:512) 
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.handleNewSessions(AbstractPollingIoProcessor.java:487) 
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$400(AbstractPollingIoProcessor.java:68) 
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1111) 
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841)
```

Not sure if it's custom ROM's problem or indeed Android 4.4's own problem though.

Reference: https://developer.android.com/reference/javax/net/ssl/SSLEngine?hl=en

**Comment by EmmanuelMess** [comment]
Does the ROM have bug tracker? We could cross report there.

**Comment by TranceLove** [comment]
The ROM had been obselete for long, as many should have been moved away from this silly (durable though) device towards newer generation devices.

And to me it's more like a Android version specific problem rather than a ROM specific problem.
