### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by PessahDerek** [TeamAmaze/AmazeFileManager#3094]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.95
* __OS:__ Linux OPPO/CPH1923/OP486C:9/PPR1.180610.011/2021020000:user/release-keys 9 - 28
* __Device:__ OP486C
* __Model:__ CPH1923
* __Product:__ CPH1923
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unknown error
	at android.os.Process.getProcessGroup(Native Method)
	at android.os.LooperMessageSuperviser.uploadLongTimeMessage(LooperMessageSuperviser.java:63)
	at android.os.LooperMessageSuperviser.endLooperMessage(LooperMessageSuperviser.java:101)
	at android.os.Looper.loop(Looper.java:290)
	at android.app.ActivityThread.main(ActivityThread.java:7212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```
</details>
<hr>

**Comment by THardi** [comment]
## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.7
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 9 - 28
* __Device:__ unknown
* __Model:__ unknown
* __Product:__ unknown
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.ui.activities.MainActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f08005d
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3090)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1820)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6758)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f08005d
	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
	at android.content.res.Resources.getDrawable(Resources.java:827)
	at android.content.Context.getDrawable(Context.java:637)
	at android.view.View.setBackgroundResource(View.java:21455)
	at com.amaze.filemanager.ui.views.drawer.Drawer.<init>(Drawer.java:216)
	at com.amaze.filemanager.ui.activities.MainActivity.initialiseViews(MainActivity.java:1648)
	at com.amaze.filemanager.ui.activities.MainActivity.onCreate(MainActivity.java:342)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2935)
	... 11 more

```
</details>
<hr>

**Comment by VishalNehra** [comment]
This crash is not from our official version. Please download from play store or github links. https://play.google.com/store/apps/details?id=com.amaze.filemanager
