### ISSUE TITLE
Crashed by Bidyut

### ISSUE THREAD

**Issue by Bidyut1154** [TeamAmaze/AmazeFileManager#3104]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.7
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 7.1.2 - 25
* __Device:__ rolex
* __Model:__ Redmi 4A
* __Product:__ rolex
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:325)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.IllegalStateException: This is not the first datapoint!
	at com.amaze.filemanager.asynchronous.services.AbstractProgressiveService.addFirstDatapoint(AbstractProgressiveService.java:244)
	at com.amaze.filemanager.asynchronous.services.DecryptService$BackgroundTask.doInBackground(DecryptService.java:169)
	at com.amaze.filemanager.asynchronous.services.DecryptService$BackgroundTask.doInBackground(DecryptService.java:152)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
Dupe #1793
