### ISSUE TITLE
Request languages here

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#3145]
Please request languages here before requesting on Transifex, please add a reason for the language request. Keep in mind that if the language was already accepted for another region, it is improbable that the request will be accepted, but if the languages are too different (Brazil and Portugal for Portuguese, or Latin America and Spain for Spanish) the request will be accepted.

**Comment by ehsan951** [comment]
>

**Comment by ehsan951** [comment]
[## Issue explanation (write below this line)    ## Exception * __App Name:__ فایل منیجر حیرت انگیز * __Package:__ com.tas.file.manager * __Version:__ 1.6 * __User Action:__ UI Error * __Request:__ Application crash * __OS:__ Linux Nokia/Ironman_00WW/IRM_sprout:11/RP1A.200720.011/00WW_3_310:user/release-keys 11 - 30 * __Device:__ IRM_sprout * __Model:__ Nokia 2.3 * __Product:__ Ironman_00WW <details><summary><b>Crash log </b></summary><p>  ``` java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference 	at com.tas.filemanager.ui.activities.MainActivity.lambda$saveExternalIntentExtras$6(MainActivity.java:735) 	at com.tas.filemanager.ui.activities.MainActivity.$r8$lambda$mnCsqTiHEb7nGG8DxYxjkB_mbQw(Unknown Source:0) 	at com.tas.filemanager.ui.activities.MainActivity$$ExternalSyntheticLambda5.apply(Unknown Source:4) 	at com.tas.filemanager.ui.activities.MainActivity.executeWithMainFragment(MainActivity.java:2656) 	at com.tas.filemanager.ui.activities.MainActivity.executeWithMainFragment(MainActivity.java:2648) 	at com.tas.filemanager.ui.activities.MainActivity.saveExternalIntentExtras(MainActivity.java:731) 	at com.tas.filemanager.ui.activities.MainActivity.lambda$saveExternalIntent$4(MainActivity.java:716) 	at com.tas.filemanager.ui.activities.MainActivity.$r8$lambda$_6JJrldk1y5KUyEp6Pt1gqnfuCI(Unknown Source:0) 	at com.tas.filemanager.ui.activities.MainActivity$$ExternalSyntheticLambda9.apply(Unknown Source:6) 	at com.tas.filemanager.ui.activities.MainActivity.executeWithMainFragment(MainActivity.java:2656) 	at com.tas.filemanager.ui.activities.MainActivity.executeWithMainFragment(MainActivity.java:2648) 	at com.tas.filemanager.ui.activities.MainActivity.saveExternalIntent(MainActivity.java:695) 	at com.tas.filemanager.ui.activities.MainActivity.lambda$initFabToSave$3(MainActivity.java:629) 	at com.tas.filemanager.ui.activities.MainActivity.$r8$lambda$RXX0JXHXN9FcG6wwSUZUSifz7ow(Unknown Source:0) 	at com.tas.filemanager.ui.activities.MainActivity$$ExternalSyntheticLambda22.run(Unknown Source:4) 	at com.tas.filemanager.utils.Utils.lambda$showThemedSnackbar$0(Utils.java:318) 	at com.tas.filemanager.utils.Utils.$r8$lambda$24zL2p-i1ZRnZyO58OKyt-0cWIM(Unknown Source:0) 	at com.tas.filemanager.utils.Utils$$ExternalSyntheticLambda0.onClick(Unknown Source:2) 	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:351) 	at android.view.View.performClick(View.java:7455) 	at android.view.View.performClickInternal(View.java:7428) 	at android.view.View.access$3600(View.java:813) 	at android.view.View$PerformClick.run(View.java:28495) 	at android.os.Handler.handleCallback(Handler.java:938) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loop(Looper.java:223) 	at android.app.ActivityThread.main(ActivityThread.java:7700) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)  ``` </details> <hr>]() #3264

**Comment by Vitahabtc** [comment]
It's crazy

**Comment by musa644** [comment]
?

**Comment by musa644** [comment]
> ## Issue explanation (write below this line)



## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 1,0
* __OS:__ Linux Android 11 - 30
* __Device:__ lime
* __Model:__ M2010J19SG
* __Product:__ lime_global
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.SecurityException: com.amaze.masters has no access to content://media/external/downloads/25714
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2010)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1825)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1502)
	at com.etochtosamolet.masters.asynchronous.asynctasks.ReadFileTask.doInBackground(ReadFileTask.java:95)
	at com.etochtosamolet.masters.asynchronous.asynctasks.ReadFileTask.doInBackground(ReadFileTask.java:47)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
@Jaford9669 dupe #2960

**Comment by byearthinc-com** [comment]
Close it already

**Comment by EmmanuelMess** [comment]
This should probably be moved to a section in the readme, as nobody uses this issue, and just request the languages  directly to transifex.
