### ISSUE TITLE
Crash when opening tar

### ISSUE THREAD

**Issue by knjmooney** [TeamAmaze/AmazeFileManager#3164]
## Issue explanation (write below this line)
* I downloaded the app from play store.
* Enabled file permissions.
* Found my tar file in my Downloads folder.
* Clicked extract, and the following was reported.

## Exception
* __App Name:__ File Manager
* __Package:__ com.mfa.filemanager
* __Version:__ 2.0.9
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux samsung/x1seea/x1s:12/SP1A.210812.016/G980FXXUCEUL6:user/release-keys 12 - 31
* __Device:__ x1s
* __Model:__ SM-G980F
* __Product:__ x1seea
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service com.mfa.filemanager.asynchronous.services.ExtractService@f064e02 with Intent { cmp=com.mfa.filemanager/.asynchronous.services.ExtractService (has extras) }: java.lang.IllegalArgumentException: com.mfa.filemanager: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5112)
	at android.app.ActivityThread.access$2200(ActivityThread.java:310)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2321)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8641)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
Caused by: java.lang.IllegalArgumentException: com.mfa.filemanager: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
	at android.app.PendingIntent.getActivity(PendingIntent.java:451)
	at android.app.PendingIntent.getActivity(PendingIntent.java:415)
	at com.mfa.filemanager.asynchronous.services.ExtractService.onStartCommand(ExtractService.java:114)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5094)
	... 9 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
@knjmooney Thanks for reporting!

But, that error report is not from the official app.

Get the official version from here

Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases
