### ISSUE TITLE
UI crash, why?

### ISSUE THREAD

**Issue by Busted1492** [TeamAmaze/AmazeFileManager#3196]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.95
* __OS:__ Linux Android 11 - 30
* __Device:__ a12u
* __Model:__ SM-S127DL
* __Product:__ a12utfn
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalArgumentException: Invalid token LIMIT
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
	at android.content.ContentResolver.query(ContentResolver.java:1193)
	at android.content.ContentResolver.query(ContentResolver.java:1125)
	at android.content.ContentResolver.query(ContentResolver.java:1081)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listRecentFiles(LoadFilesListTask.java:462)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:180)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:68)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
</details>
<hr>

**Comment by VishalNehra** [comment]
This is unofficial version, see our readme for official links, also this issue was already fixed in 3.6.7 #2993
