### ISSUE TITLE
App crashes when trying to open the root directory

### ISSUE THREAD

**Issue by nm17** [TeamAmaze/AmazeFileManager#3247]
## Issue explanation (write below this line)

App crashes when trying to open the root directory. I have proper root privileges on my phone using Magisk. Using the latest release from Github [v3.6.7](https://github.com/TeamAmaze/AmazeFileManager/releases/tag/v3.6.7). I can browse the sdcard just fine.

## Exception
* __App Name:__ Amaze
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.7
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 7.0 - 24
* __Device:__ M5Note
* __Model:__ M5 Note
* __Product:__ meizu_M5 Note
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:318)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.Long.parseLong(Long.java:455)
	at java.lang.Long.parseLong(Long.java:485)
	at com.amaze.filemanager.filesystem.files.FileUtils.parseName(FileUtils.java:828)
	at com.amaze.filemanager.filesystem.root.ListFilesCommand.parseStringForHybridFile(ListFilesCommand.kt:207)
	at com.amaze.filemanager.filesystem.root.ListFilesCommand.listFiles(ListFilesCommand.kt:60)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:250)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:75)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
@TranceLove Wasn't this fixed with #2894 🤔

**Comment by TranceLove** [comment]
I thought so. And with #2881 I thought everything should be covered, including stock `toybox` as seen in modern Android stock roms.

Would like to see the result of `stat -c '%A %h %G %U %B %Y %N' *` and `ls -l /` if you have access to rooted `adb shell`.

**Comment by nm17** [comment]
@TranceLove I'll try in a couple of days, don't have access to the phone right now, sorry!

**Comment by nm17** [comment]
@TranceLove  @VishnuSanal 
[log-stat-and-ls.txt](https://github.com/TeamAmaze/AmazeFileManager/files/8497298/log-stat-and-ls.txt)
