### ISSUE TITLE
SFTP conection became not working

### ISSUE THREAD

**Issue by aivanovski** [TeamAmaze/AmazeFileManager#3266]
**Describe the bug**
SFTP connection becomes not working if SFTP was turned off

**To Reproduce**
1. Setup SSH server via Termux (probably any other SSH/SFTP server should also work)
2. Create and save in AFM SFTP connection to server with username/password authentication
3. Connect to server and open several directories inside SFTP file structure
4. Turn off SSH/SFTP server
5. Press back several times in AFM ("No Files" should be displayed)
6. Start SSH/SFTP server
7. Restart AFM and open saved SFTP connection
8. Check "No Files" is displayed

**Expected behavior**
AFM should show files from SFTP server

**Additional context**
Here is stacktrace that has been occurred during step 5
```
2022-04-19 11:39:26.543 7970-8005/com.amaze.filemanager.debug W/System.err: [RxCachedThreadScheduler-1] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
2022-04-19 11:39:27.429 7970-8028/com.amaze.filemanager.debug W/System.err: [RxCachedThreadScheduler-3] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
2022-04-19 11:39:32.179 7970-8029/com.amaze.filemanager.debug W/System.err: [RxCachedThreadScheduler-4] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
2022-04-19 11:39:33.298 7970-8030/com.amaze.filemanager.debug W/System.err: [RxCachedThreadScheduler-5] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
2022-04-19 11:39:35.047 7970-8027/com.amaze.filemanager.debug W/System.err: [RxCachedThreadScheduler-2] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
2022-04-19 11:39:35.616 7970-8005/com.amaze.filemanager.debug W/System.err: [RxCachedThreadScheduler-1] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
2022-04-19 11:39:36.497 7970-8028/com.amaze.filemanager.debug W/System.err: [RxCachedThreadScheduler-3] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
2022-04-19 11:39:38.767 7970-8029/com.amaze.filemanager.debug W/System.err: [RxCachedThreadScheduler-4] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
2022-04-19 11:39:39.852 7970-8030/com.amaze.filemanager.debug W/System.err: [RxCachedThreadScheduler-5] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
2022-04-19 11:39:41.138 7970-8027/com.amaze.filemanager.debug W/System.err: [RxCachedThreadScheduler-2] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
2022-04-19 11:39:43.142 7970-8005/com.amaze.filemanager.debug W/System.err: [RxCachedThreadScheduler-1] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
2022-04-19 11:39:44.098 7970-8028/com.amaze.filemanager.debug W/System.err: [RxCachedThreadScheduler-3] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
2022-04-19 11:39:55.305 7970-8113/com.amaze.filemanager.debug W/System.err: [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Broken transport; encountered EOF
2022-04-19 11:39:55.305 7970-8113/com.amaze.filemanager.debug W/System.err: net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
2022-04-19 11:39:55.305 7970-8113/com.amaze.filemanager.debug W/System.err:     at net.schmizz.sshj.transport.Reader.run(Reader.java:58)
2022-04-19 11:39:55.305 7970-8113/com.amaze.filemanager.debug W/System.err: [reader] INFO net.schmizz.sshj.transport.TransportImpl - Disconnected - UNKNOWN
2022-04-19 11:40:02.595 7970-8062/com.amaze.filemanager.debug D/SshConnectionPool: Connection no longer usable. Reconnecting...
2022-04-19 11:40:02.622 7970-8062/com.amaze.filemanager.debug E/UtilsHandler: Error getting auth private key for URI [ssh://u0_a297:abc123@127.0.0.1:8022]
    androidx.room.EmptyResultSetException: Query returned empty result set: SELECT ssh_key FROM sftp WHERE path = ?
        at com.amaze.filemanager.database.daos.SftpEntryDao_Impl$14.call(SftpEntryDao_Impl.java:551)
        at com.amaze.filemanager.database.daos.SftpEntryDao_Impl$14.call(SftpEntryDao_Impl.java:535)
        at androidx.room.RxRoom$5.subscribe(RxRoom.java:229)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
2022-04-19 11:40:02.624 7970-8062/com.amaze.filemanager.debug E/UtilsHandler: Error getting public key for URI [ssh://u0_a297:abc123@127.0.0.1:8022]
    androidx.room.EmptyResultSetException: Query returned empty result set: SELECT pub_key FROM sftp WHERE path = ?
        at com.amaze.filemanager.database.daos.SftpEntryDao_Impl$12.call(SftpEntryDao_Impl.java:469)
        at com.amaze.filemanager.database.daos.SftpEntryDao_Impl$12.call(SftpEntryDao_Impl.java:453)
        at androidx.room.RxRoom$5.subscribe(RxRoom.java:229)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
2022-04-19 11:40:02.640 7970-8062/com.amaze.filemanager.debug E/UtilsHandler: Error getting auth private key for URI [ssh://u0_a297:abc123@127.0.0.1:8022/data/data/com.termux/files/home]
    androidx.room.EmptyResultSetException: Query returned empty result set: SELECT ssh_key FROM sftp WHERE path = ?
        at com.amaze.filemanager.database.daos.SftpEntryDao_Impl$14.call(SftpEntryDao_Impl.java:551)
        at com.amaze.filemanager.database.daos.SftpEntryDao_Impl$14.call(SftpEntryDao_Impl.java:535)
        at androidx.room.RxRoom$5.subscribe(RxRoom.java:229)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
2022-04-19 11:40:02.642 7970-8062/com.amaze.filemanager.debug E/UtilsHandler: Error getting public key for URI [ssh://u0_a297:abc123@127.0.0.1:8022/data/data/com.termux/files/home]
    androidx.room.EmptyResultSetException: Query returned empty result set: SELECT pub_key FROM sftp WHERE path = ?
        at com.amaze.filemanager.database.daos.SftpEntryDao_Impl$12.call(SftpEntryDao_Impl.java:469)
        at com.amaze.filemanager.database.daos.SftpEntryDao_Impl$12.call(SftpEntryDao_Impl.java:453)
        at androidx.room.RxRoom$5.subscribe(RxRoom.java:229)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

```

**Comment by marcin843** [comment]
_Wysłano z mojego QM152E za pomocą [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_
