### ISSUE TITLE
Why is the file manager crashing?

### ISSUE THREAD

**Issue by Lokeshmohanty490** [TeamAmaze/AmazeFileManager#3278]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.95
* __OS:__ Linux Android 10 - 29
* __Device:__ X606V
* __Model:__ Lenovo TB-X606V
* __Product:__ LenovoTB-X606V
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.CLOSE_SYSTEM_DIALOGS flg=0x50000010 (has extras) } in com.amaze.filemanager.Eapp$2@1a02592
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: java.lang.IllegalArgumentException: View=DecorView@80cf89[Eapp] not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:517)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:426)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:126)
	at android.app.Dialog.dismissDialog(Dialog.java:389)
	at android.app.Dialog.dismiss(Dialog.java:371)
	at com.amaze.filemanager.Eapp.fecharx(Eapp.java:338)
	at com.amaze.filemanager.Eapp$2.onReceive(Eapp.java:115)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1550)
	... 8 more

```
</details>
<hr>
Caused by: java.lang.IllegalArgumentException: View=DecorView@80cf89[Eapp] not attached to window manager

**Comment by VishnuSanal** [comment]
Thanks for reporting!

But, that error report is not from the official app.

Get the official version from here

Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases
