### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by TxFeather** [TeamAmaze/AmazeFileManager#3309]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.95
* __OS:__ Linux Android 11 - 30
* __Device:__ mh2lm
* __Model:__ LM-G850
* __Product:__ mh2lm
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.CLOSE_SYSTEM_DIALOGS flg=0x50000010 (has extras) } in com.amaze.filemanager.Eapp$2@a12b325
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1640)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7868)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
Caused by: java.lang.IllegalArgumentException: View=DecorView@3ec05f6[Eapp] not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:593)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:489)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:156)
	at android.app.Dialog.dismissDialog(Dialog.java:480)
	at android.app.Dialog.dismiss(Dialog.java:462)
	at com.amaze.filemanager.Eapp.fecharx(Eapp.java:338)
	at com.amaze.filemanager.Eapp$2.onReceive(Eapp.java:115)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1622)
	... 8 more

```
</details>
<hr>

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by VishnuSanal** [comment]
@TxFeather Thanks for reporting!

But, that error report is not from the official app.

Get the official version from here

Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases
