### ISSUE TITLE
Crash when looking through history

### ISSUE THREAD

**Issue by shelbyBuzz** [TeamAmaze/AmazeFileManager#3346]
## Issue explanation (write below this line)
When scrolling down in my history, at some point it reaches something it doesn't like

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.7.0
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 32
* __Device:__ coral
* __Model:__ Pixel 4 XL
* __Product:__ coral
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter rootUri
	at com.amaze.filemanager.utils.OTGUtil.getDocumentFile(Unknown Source:7)
	at com.amaze.filemanager.filesystem.HybridFile.getName(HybridFile.java:385)
	at com.amaze.filemanager.adapters.HiddenAdapter.onBindViewHolder(HiddenAdapter.kt:73)
	at com.amaze.filemanager.adapters.HiddenAdapter.onBindViewHolder(HiddenAdapter.kt:51)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1391)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1128)
	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1841)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5302)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:775)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
Dupe #2960
