### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by DomKing13** [TeamAmaze/AmazeFileManager#3367]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.95
* __OS:__ Linux motorola/borneo_a/borneo:10/QZB30.Q4-43-59/35bb5:user/release-keys 10 - 29
* __Device:__ borneo
* __Model:__ moto g power (2021)
* __Product:__ borneo_a
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.filemanager.lnapp/com.amaze.filemanager.ui.activities.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'androidx.swiperefreshlayout.widget.SwipeRefreshLayout com.amaze.filemanager.ui.fragments.MainFragment.mSwipeRefreshLayout' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3455)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3598)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2164)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: java.lang.NullPointerException: Attempt to read from field 'androidx.swiperefreshlayout.widget.SwipeRefreshLayout com.amaze.filemanager.ui.fragments.MainFragment.mSwipeRefreshLayout' on a null object reference
	at com.amaze.filemanager.ui.activities.MainActivity.onPreExecute(MainActivity.java:1960)
	at com.amaze.filemanager.asynchronous.asynctasks.SearchAsyncTask.onPreExecute(SearchAsyncTask.java:67)
	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:708)
	at android.os.AsyncTask.execute(AsyncTask.java:655)
	at com.amaze.filemanager.ui.fragments.SearchWorkerFragment.onCreate(SearchWorkerFragment.java:88)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at com.amaze.filemanager.ui.activities.superclasses.PreferenceActivity.onCreate(PreferenceActivity.java:58)
	at com.amaze.filemanager.ui.activities.superclasses.ThemedActivity.onCreate(ThemedActivity.java:55)
	at com.amaze.filemanager.ui.activities.MainActivity.onCreate(MainActivity.java:339)
	at android.app.Activity.performCreate(Activity.java:7822)
	at android.app.Activity.performCreate(Activity.java:7811)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1328)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
	... 11 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
@DomKing13 
Thanks for reporting!

But, that error report is not from the official app.

Get the official version from here

Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases
