### ISSUE TITLE
Crash after new installation in AmazeFileManager 3.7.2

### ISSUE THREAD

**Issue by XYIheng** [TeamAmaze/AmazeFileManager#3374]
**Describe the bug**
I used to use Amaze 3.5.3, However, after install the newest version 3.7.2, I find a crash which annoys me a lot.

After installation, rotate the device and accept storage permission, then Amaze crashes.
However, it behaves normally on Amaze 3.5.3

**To Reproduce**
1. install Amaze 3.7.2
2. open Amze
3. rotate device
4. click "Allow Amaze to access photos,media, and files on your divice"
5. see crash report

**Expected behavior**
I can still see my files and use AmazeFileManager normally

**Screenshots**

https://user-images.githubusercontent.com/31406320/176077657-7d361c4b-3b30-47c1-aef9-13a55b3ace4b.mp4

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.7.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 8.0.0 - 26
* __Device:__ generic_x86
* __Model:__ Android SDK built for x86
* __Product:__ sdk_gphone_x86
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment TabFragment{482657d} (0ab7c6c7-267f-4f7c-98ff-4de39ef40029) not attached to an activity.
	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:928)
	at com.amaze.filemanager.ui.fragments.TabFragment.requireMainActivity(TabFragment.java:497)
	at com.amaze.filemanager.ui.fragments.TabFragment.refactorDrawerStorages(TabFragment.java:346)
	at com.amaze.filemanager.ui.activities.MainActivity.lambda$onPermissionGranted$1(MainActivity.java:512)
	at com.amaze.filemanager.ui.activities.MainActivity.$r8$lambda$p7zQEtaqRSrFGunP-GdzA6cGHkk(Unknown Source:0)
	at com.amaze.filemanager.ui.activities.MainActivity$$ExternalSyntheticLambda17.run(Unknown Source:6)
	at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:53)
	at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:89)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```
</details>
<hr>

**Comment by tingsu** [comment]
I have encountered the same issue.

**Comment by r0wan** [comment]
Possibly related.  
Just list a smb / cloud dir.
Rotate the screen 90 degrees.
Crashes:

## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 15 - 35
* __Device:__ tokay
* __Model:__ Pixel 9
* __Product:__ tokay
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{2f69996} (4469e220-6675-4fb1-b761-f36fe7ef9764) is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:1013)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:250)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3288)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:681)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:647)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2382)
	at androidx.fragment.app.FragmentManager.lambda$attachController$4(FragmentManager.java:2660)
	at androidx.fragment.app.FragmentManager.$r8$lambda$sido8p6zuWx0PQxIkv4qM-BRiGM(Unknown Source:0)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda4.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.kt:247)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:383)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1325)
	at android.app.Activity.performSaveInstanceState(Activity.java:2435)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1756)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:6401)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5809)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6358)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6276)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:106)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:63)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2719)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8787)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)

```
</details>
<hr>

**Comment by r0wan** [comment]
After listing smb cloud dir, scroll down and long press a file to select it, then rotate 90 degrees.  That should crash.

## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 15 - 35
* __Device:__ tokay
* __Model:__ Pixel 9
* __Product:__ tokay
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{ce54c92} (52f04217-beb1-4762-9e87-93e6743d102f) is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:1013)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:250)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3288)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:681)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:647)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2382)
	at androidx.fragment.app.FragmentManager.lambda$attachController$4(FragmentManager.java:2660)
	at androidx.fragment.app.FragmentManager.$r8$lambda$sido8p6zuWx0PQxIkv4qM-BRiGM(Unknown Source:0)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda4.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.kt:247)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:383)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1325)
	at android.app.Activity.performSaveInstanceState(Activity.java:2435)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1756)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:6401)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5809)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6358)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6276)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:106)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:63)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2719)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8787)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
@r0wan dupe #1555
