### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Miala-python** [TeamAmaze/AmazeFileManager#3377]
Possibilité parfois d'ajuster un dossier dans le menu FTP 

## Exception
* __App Name:__ Amaze
* __Package:__ com.amaze.filemanager
* __Version:__ 3.7.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 11 - 30
* __Device:__ rosemary
* __Model:__ M2101K7BNY
* __Product:__ rosemary_eea
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ClassCastException: com.amaze.filemanager.ui.fragments.FtpServerFragment cannot be cast to com.amaze.filemanager.ui.fragments.TabFragment
	at com.amaze.filemanager.ui.activities.MainActivity$FabActionListener.onActionSelected(MainActivity.java:2320)
	at com.leinardi.android.speeddial.SpeedDialView$1.onActionSelected(SpeedDialView.java:108)
	at com.leinardi.android.speeddial.FabWithLabelView$2.onClick(FabWithLabelView.java:214)
	at android.view.View.performClick(View.java:7575)
	at android.view.View.performClickInternal(View.java:7548)
	at android.view.View.access$3600(View.java:837)
	at android.view.View$PerformClick.run(View.java:28902)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8031)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3162
