### ISSUE TITLE
UI Error- Guru meditation

### ISSUE THREAD

**Issue by MarkAdy** [TeamAmaze/AmazeFileManager#3379]
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.95
* __OS:__ Linux Android 9 - 28
* __Device:__ gts3lwifi
* __Model:__ SM-T820
* __Product:__ gts3lwifixx
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.CLOSE_SYSTEM_DIALOGS flg=0x10 (has extras) } in com.amaze.filemanager.Eapp$2@1fe129d
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1497)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7266)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: java.lang.IllegalArgumentException: View=DecorView@92e3b99[Eapp] not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:534)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:434)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
	at android.app.Dialog.dismissDialog(Dialog.java:518)
	at android.app.Dialog.dismiss(Dialog.java:501)
	at com.amaze.filemanager.Eapp.fecharx(Eapp.java:338)
	at com.amaze.filemanager.Eapp$2.onReceive(Eapp.java:115)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1487)
	... 8 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
@MarkAdy Thanks for reporting!

But, that error report is not from the official app.

Get the official version from here

Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases
