### ISSUE TITLE
App crashing when using the back button while accessing root.

### ISSUE THREAD

**Issue by FanboyStudios** [TeamAmaze/AmazeFileManager#3382]
## Issue explanation (write below this line)

The app crashes when hitting the back button when browsing the root or attempting to access root, after enabling the custom back button.

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.7.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 6.0.1 - 23
* __Device:__ surnia_cdma
* __Model:__ XT1526
* __Product:__ Moto E LTE (2nd gen)
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NumberFormatException: Invalid long: "root"
	at java.lang.Long.invalidLong(Long.java:124)
	at java.lang.Long.parse(Long.java:363)
	at java.lang.Long.parseLong(Long.java:353)
	at java.lang.Long.parseLong(Long.java:321)
	at com.amaze.filemanager.filesystem.files.FileUtils.parseName(FileUtils.java:896)
	at com.amaze.filemanager.filesystem.root.ListFilesCommand.parseStringForHybridFile(ListFilesCommand.kt:207)
	at com.amaze.filemanager.filesystem.root.ListFilesCommand.listFiles(ListFilesCommand.kt:60)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:252)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:77)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more

```
</details>
<hr>

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by VishnuSanal** [comment]
dupe #3359
