### ISSUE TITLE
Crash: Click to modify the directory name, rotate device, then app crashes

### ISSUE THREAD

**Issue by XYIheng** [TeamAmaze/AmazeFileManager#3395]
**Describe the bug**
Click to modify the directory name, rotate device, then app crashes

**To Reproduce**
1. Go to menu
2. Click to modify directory name
3. rotate device

**Expected behavior**
no crash

**Screenshots**

https://user-images.githubusercontent.com/31406320/178178079-8128a5c9-3ed7-4251-a037-60865612a6f0.mp4

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 2]
 - OS: [Android 8]
 - Rooted: [e.g. No]
 - Version: [3.7.2]

**Additional context**
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.7.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 8.0.0 - 26
* __Device:__ generic_x86
* __Model:__ Android SDK built for x86
* __Product:__ sdk_gphone_x86
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.ui.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Dialog.setOwnerActivity(android.app.Activity)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4754)
	at android.app.ActivityThread.-wrap18(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Dialog.setOwnerActivity(android.app.Activity)' on a null object reference
	at android.app.DialogFragment.onActivityCreated(DialogFragment.java:482)
	at android.app.Fragment.performActivityCreated(Fragment.java:2620)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1296)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1549)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1611)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3039)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2991)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
	at android.app.Activity.performCreateCommon(Activity.java:6969)
	at android.app.Activity.performCreate(Activity.java:6977)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
	... 10 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #2852
