### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by asdfjkl** [TeamAmaze/AmazeFileManager#3407]
## Exception
* __App Name:__ Amaze Dateimanager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.7.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux PPR1.180610.009 9 - 28
* __Device:__ trona
* __Model:__ KFTRPWI
* __Product:__ trona
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{bd5610f} (d97c96f6-3cad-4c43-812d-6d58f3375426) is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:937)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:243)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3151)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:683)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:649)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:177)
	at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:2655)
	at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:152)
	at androidx.fragment.app.FragmentActivity$1.saveState(FragmentActivity.java:133)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.java:227)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.java:74)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:338)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1270)
	at android.app.Activity.performSaveInstanceState(Activity.java:1562)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1443)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:4868)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4216)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4180)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4255)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1824)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6740)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #1555
