### ISSUE TITLE
On clicking dialog box to grant SAF permission app crashes 

### ISSUE THREAD

**Issue by mrtanush18** [TeamAmaze/AmazeFileManager#3408]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.7.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux OnePlus/DN2101IND/OP515BL1:12/SP1A.210812.016/R.202204021708:user/release-keys 12 - 31
* __Device:__ OP515BL1
* __Model:__ DN2101
* __Product:__ DN2101IND
<details><summary><b>Crash log </b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2108)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1768)
	at android.app.Activity.startActivityForResult(Activity.java:5473)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:237)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
	at androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at com.amaze.filemanager.ui.fragments.MainFragment.lambda$loadPathInQ$4(MainFragment.java:636)
	at com.amaze.filemanager.ui.fragments.MainFragment.$r8$lambda$ng_KSX_zdbQxLK4yA1LyDyL5O9Y(Unknown Source:0)
	at com.amaze.filemanager.ui.fragments.MainFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7498)
	at android.view.View.performClickInternal(View.java:7471)
	at android.view.View.access$3700(View.java:843)
	at android.view.View$PerformClick.run(View.java:29077)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8223)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #2417
