### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by sho-blackz** [TeamAmaze/AmazeFileManager#3444]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.7.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ pissarroin
* __Model:__ 21091116I
* __Product:__ pissarroin
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'boolean com.amaze.filemanager.adapters.data.LayoutElementParcelable.isBack' on a null object reference
	at com.amaze.filemanager.adapters.RecyclerAdapter.setItems(RecyclerAdapter.java:531)
	at com.amaze.filemanager.adapters.RecyclerAdapter.setItems(RecyclerAdapter.java:504)
	at com.amaze.filemanager.asynchronous.handlers.FileHandler.handleMessage(FileHandler.kt:98)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8295)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

```
</details>
<hr>

**Comment by FruSanchez** [comment]
Why did that happen??

**Comment by sho-blackz** [comment]
I was trasfering big files(12-15GB) to my pendrive from phone and left it for a while and after a while i saw is error.

**Comment by VishalNehra** [comment]
dupe #2224
