### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by TamojitSaha** [TeamAmaze/AmazeFileManager#3504]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.1
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux motorola/liber_retailg/liber:11/RPI31.Q2-42-25/3c7b55:user/release-keys 11 - 30
* __Device:__ liber
* __Model:__ motorola one fusion+
* __Product:__ liber_retailg
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.amaze.filemanager.exceptions.DocumentFileNotFoundException: Root uri: /tree/primary: and path content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fdata
	at com.amaze.filemanager.utils.OTGUtil.getDocumentFiles(OTGUtil.kt:119)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listDocumentFiles(LoadFilesListTask.java:664)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:215)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:78)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3038
