### ISSUE TITLE
Long Parse on folder size results in UI Error app crash

### ISSUE THREAD

**Issue by susch19** [TeamAmaze/AmazeFileManager#3541]
## Issue explanation (write below this line)

while trying to navigate to "/sys/class/power_supply/". batt_verify is a folder, so I don't know why you would parse the name as a long. does java have a try parse or should you just catch the exception? 

## Exception
* __App Name:__ Amaze Dateimanager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NumberFormatException: For input string: "batt_verify"
	at java.lang.Long.parseLong(Long.java:736)
	at java.lang.Long.parseLong(Long.java:861)
	at com.amaze.filemanager.filesystem.files.FileUtils.parseName(FileUtils.java:926)
	at com.amaze.filemanager.filesystem.root.ListFilesCommand.parseStringForHybridFile(ListFilesCommand.kt:222)
	at com.amaze.filemanager.filesystem.root.ListFilesCommand.listFiles(ListFilesCommand.kt:60)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:265)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:78)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

```
</details>
<hr>

**Comment by susch19** [comment]
I looked a bit into the code, the problem seems to be the size. 
Another file manager “simple file manager” can't display any sizes of files in this directory (everything displayed as 0B). Maybe that has something to do with it. If I should test something, I can do that

**Comment by TranceLove** [comment]
If doing from a Pixel 5 emulator running Android 13, I got these:

```sh
emu64xa:/ # ls -la /sys/class/power_supply                                                                                                                                                                                                                 
total 0
drwxr-xr-x  2 root root 0 2022-10-05 15:38 .
drwxr-xr-x 74 root root 0 2022-09-28 14:30 ..
lrwxrwxrwx  1 root root 0 2022-10-05 15:39 ac -> ../../devices/platform/GFSH0001:00/power_supply/ac
lrwxrwxrwx  1 root root 0 2022-10-05 15:38 battery -> ../../devices/platform/GFSH0001:00/power_supply/battery
```

```sh
emu64xa:/ # stat -c '%A %h %G %U %B %Y %N' /sys/class/power_supply/*
lrwxrwxrwx 1 root root 512 1664955558 /sys/class/power_supply/ac -> '../../devices/platform/GFSH0001:00/power_supply/ac'
lrwxrwxrwx 1 root root 512 1664955532 /sys/class/power_supply/battery -> '../../devices/platform/GFSH0001:00/power_supply/battery'
```

**Comment by susch19** [comment]
```bash
:/data/data/com.termux/files/home # ls -la /sys/class/power_supply
total 0
drwxr-xr-x   2 root root 0 2022-10-04 20:27 .
drwxr-xr-x 105 root root 0 1970-11-30 06:27 ..
lrwxrwxrwx   1 root root 0 2022-10-05 00:16 batt_verify -> ../../devices/platform/soc/soc:maxim_ds28e16/power_supply/batt_verify
lrwxrwxrwx   1 root root 0 2022-10-04 20:27 battery -> ../../devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:qcom,qpnp-smb5/power_supply/battery
lrwxrwxrwx   1 root root 0 2022-10-05 00:16 bms -> ../../devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:qpnp,fg/power_supply/bms
lrwxrwxrwx   1 root root 0 2022-10-05 00:16 bq2597x-standalone -> ../../devices/platform/soc/884000.i2c/i2c-3/3-0066/power_supply/bq2597x-standalone
lrwxrwxrwx   1 root root 0 2022-10-05 00:16 dc -> ../../devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:qcom,qpnp-smb5/power_supply/dc
lrwxrwxrwx   1 root root 0 2022-10-05 00:16 main -> ../../devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:qcom,qpnp-smb5/power_supply/main
lrwxrwxrwx   1 root root 0 2022-10-05 00:16 pc_port -> ../../devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:qcom,qpnp-smb5/power_supply/pc_port
lrwxrwxrwx   1 root root 0 2022-10-05 00:16 usb -> ../../devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:qcom,qpnp-smb5/power_supply/usb
```
```bash
:/data/data/com.termux/files/home # stat -c '%A %h %G %U %B %Y %N' /sys/class/power_supply/*
lrwxrwxrwx 1 root root 512 1664956626 /sys/class/power_supply/batt_verify -> '../../devices/platform/soc/soc:maxim_ds28e16/power_supply/batt_verify'
lrwxrwxrwx 1 root root 512 1664956626 /sys/class/power_supply/battery -> '../../devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:qcom,qpnp-smb5/power_supply/battery'
lrwxrwxrwx 1 root root 512 1664956626 /sys/class/power_supply/bms -> '../../devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:qpnp,fg/power_supply/bms'
lrwxrwxrwx 1 root root 512 1664956626 /sys/class/power_supply/bq2597x-standalone -> '../../devices/platform/soc/884000.i2c/i2c-3/3-0066/power_supply/bq2597x-standalone'
lrwxrwxrwx 1 root root 512 1664956626 /sys/class/power_supply/dc -> '../../devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:qcom,qpnp-smb5/power_supply/dc'
lrwxrwxrwx 1 root root 512 1664956626 /sys/class/power_supply/main -> '../../devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:qcom,qpnp-smb5/power_supply/main'
lrwxrwxrwx 1 root root 512 1664956626 /sys/class/power_supply/pc_port -> '../../devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:qcom,qpnp-smb5/power_supply/pc_port'
lrwxrwxrwx 1 root root 512 1664956626 /sys/class/power_supply/usb -> '../../devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pm8150b@2:qcom,qpnp-smb5/power_supply/usb'
```

This is what I get, didn't even occur to me to check with bash (used termux). So pretty similar to your output
