### ISSUE TITLE
`NumberFormatException` on `FileUtils#parseName`

### ISSUE THREAD

**Issue by hg13bs** [TeamAmaze/AmazeFileManager#3546]
## Issue explanation (write below this line)

hi,I was trying to open the /data system folder then it instantly crashed (I gave it su perms thru magisk popup)

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux samsung/treltexx/trelte:6.0.1/MMB29K/N910CXXU2DRA1:user/release-keys 6.0.1 - 23
* __Device:__ trelte
* __Model:__ SM-N910C
* __Product:__ treltexx
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NumberFormatException: Invalid long: "1665017109 | android:ui"
	at java.lang.Long.invalidLong(Long.java:124)
	at java.lang.Long.parse(Long.java:363)
	at java.lang.Long.parseLong(Long.java:353)
	at java.lang.Long.parseLong(Long.java:321)
	at com.amaze.filemanager.filesystem.files.FileUtils.parseName(FileUtils.java:942)
	at com.amaze.filemanager.filesystem.root.ListFilesCommand.parseStringForHybridFile(ListFilesCommand.kt:222)
	at com.amaze.filemanager.filesystem.root.ListFilesCommand.listFiles(ListFilesCommand.kt:60)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:265)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:78)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
@TranceLove dupe #3541?

**Comment by TranceLove** [comment]
@VishnuSanal Not exactly, but possibly the case I added in #3492 - not the part to fix su binary default to /data/data, but a case I discovered as I worked on that.

May split that PR to fix parsing issues including this... let me check.
