### ISSUE TITLE
Crash on opening a folder in /data

### ISSUE THREAD

**Issue by williamcll** [TeamAmaze/AmazeFileManager#3549]
## Issue explanation (write below this line)
I opened any folders within Android/data/ and it would crash. Notably, Amaze also takes a longer time to load /data compared do other file managers. Maybe it has something to do with #3032 ?

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 32
* __Device:__ ASUS_AI2202
* __Model:__ ASUS_AI2202
* __Product:__ WW_AI2202
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.amaze.filemanager.exceptions.DocumentFileNotFoundException: Root uri: /tree/primary:Android/data and path content://com.android.externalstorage.documents/tree/primary:Android/data/com.taobao.taobao
	at com.amaze.filemanager.utils.OTGUtil.getDocumentFiles(OTGUtil.kt:119)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listDocumentFiles(LoadFilesListTask.java:664)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:215)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:78)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3038 & fixed with #3534
