### ISSUE TITLE
crashed when open folder in storage/emulated/0/Android/data

### ISSUE THREAD

**Issue by ConnorWoodring** [TeamAmaze/AmazeFileManager#3551]
## Issue explanation (write below this line)

crashed when open folder in storage/emulated/0/Android/data

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 11 - 30
* __Device:__ nabu
* __Model:__ 21051182C
* __Product:__ nabu
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NullPointerException
	at com.amaze.filemanager.utils.OTGUtil.getDocumentFile(OTGUtil.kt:183)
	at com.amaze.filemanager.filesystem.HybridFile.getDocumentFile(HybridFile.java:274)
	at com.amaze.filemanager.filesystem.HybridFile.length(HybridFile.java:383)
	at com.amaze.filemanager.asynchronous.asynctasks.CountItemsOrAndSizeTask.doInBackground(CountItemsOrAndSizeTask.java:57)
	at com.amaze.filemanager.asynchronous.asynctasks.CountItemsOrAndSizeTask.doInBackground(CountItemsOrAndSizeTask.java:39)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
</details>
<hr>#3549

**Comment by VishnuSanal** [comment]
dupe #3038 & fixed with #3534
