### ISSUE TITLE
Any attempt to edit sftp connection causes a crash. 

### ISSUE THREAD

**Issue by vbwagner** [TeamAmaze/AmazeFileManager#3601]
## Issue explanation (write below this line)

Any attempt to edit sftp connection causes a crash. 

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 7.0 - 24
* __Device:__ M8
* __Model:__ M8
* __Product:__ M8
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
	at java.util.ArrayList.remove(ArrayList.java:480)
	at com.amaze.filemanager.utils.DataUtils.removeServer(DataUtils.java:224)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog.updateFtpConnection(SftpConnectDialog.kt:695)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog.authenticateAndSaveSetup(SftpConnectDialog.kt:620)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog.access$authenticateAndSaveSetup(SftpConnectDialog.kt:84)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog$createFirstConnectCallback$1.invoke$lambda-0(SftpConnectDialog.kt:416)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog$createFirstConnectCallback$1.$r8$lambda$4Ss-hGR5PFW2OckH5YdL_2Y6h0o(SftpConnectDialog.kt)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog$createFirstConnectCallback$1$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:169)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3085
