### ISSUE TITLE
Crash while deleting files on SD card

### ISSUE THREAD

**Issue by braoult** [TeamAmaze/AmazeFileManager#3614]
## Issue explanation (write below this line)

i tried to delete files on sd card (AugenDiagnoseDummyFile{1,2}). I believe these files were created by amaze itself

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 7.1.1 - 25
* __Device:__ X704F
* __Model:__ Lenovo TB-X704F
* __Product:__ LenovoTB-X704F
<details><summary><b>Crash log </b></summary><p>

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@40378a3 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
	at android.widget.Toast$TN.handleShow(Toast.java:459)
	at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #2698
