### ISSUE TITLE
saved ogg file to Android/data, app crashed with javascript error

### ISSUE THREAD

**Issue by LanceLVineY** [TeamAmaze/AmazeFileManager#3615]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 11 - 30
* __Device:__ Doha_TMO
* __Model:__ 5087Z
* __Product:__ 5087Z_BO
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.amaze.filemanager.exceptions.DocumentFileNotFoundException: Root uri: /tree/primary:Android/data and path content://com.android.externalstorage.documents/tree/primary:Android/data/com.github.axet.audiorecorder
	at com.amaze.filemanager.utils.OTGUtil.getDocumentFiles(OTGUtil.kt:119)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listDocumentFiles(LoadFilesListTask.java:664)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:215)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:78)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3038 & fixed with #3534
