### ISSUE TITLE
app/ui crashed when  connct to ftp server

### ISSUE THREAD

**Issue by Michaelmilk** [TeamAmaze/AmazeFileManager#3642]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.2
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux OnePlus/OnePlus8T_CH/OnePlus8T:12/SKQ1.210216.001/R.202112080214:user/release-keys 12 - 31
* __Device:__ OnePlus8T
* __Model:__ KB2000
* __Product:__ OnePlus8T_CH
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
	at java.util.ArrayList.remove(ArrayList.java:506)
	at com.amaze.filemanager.utils.DataUtils.removeServer(DataUtils.java:224)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog.updateFtpConnection(SftpConnectDialog.kt:695)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog.authenticateAndSaveSetup(SftpConnectDialog.kt:620)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog.authenticateAndSaveSetup$default(SftpConnectDialog.kt:603)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog.positiveButtonForFtp(SftpConnectDialog.kt:347)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog.handleOnPositiveButton$lambda-11(SftpConnectDialog.kt:339)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog.$r8$lambda$82hphGRYlLWtftUybxE6PGboOWc(Unknown Source:0)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog$$ExternalSyntheticLambda5.onClick(Unknown Source:4)
	at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:410)
	at android.view.View.performClick(View.java:7488)
	at android.view.View.performClickInternal(View.java:7464)
	at android.view.View.access$3700(View.java:841)
	at android.view.View$PerformClick.run(View.java:28911)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```
</details>
<hr>

<img src="https://user-images.githubusercontent.com/6982589/203827408-391440ec-bedf-480c-8d81-cbce182fb8a7.jpg" height="800" />

**Comment by VishnuSanal** [comment]
dupe #3085
