### ISSUE TITLE
App always crashes when opend

### ISSUE THREAD

**Issue by Dalmater** [TeamAmaze/AmazeFileManager#3645]
## Issue explanation (write below this line)

Since the last update the app always crashes as soon as i open the app. 

## Exception
* __App Name:__ Amaze Dateimanager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 9 - 28
* __Device:__ j7velte
* __Model:__ SM-J701F
* __Product:__ j7veltedx
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: the bind value at index 4 is null
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
	at android.content.ContentResolver.query(ContentResolver.java:809)
	at android.content.ContentResolver.query(ContentResolver.java:759)
	at androidx.core.content.ContentResolverCompat$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)
	at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
	at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
	at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:41)
	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
	at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
</details>
<hr>

**Comment by VishalNehra** [comment]
@TranceLove can you wrap these db calls for exception to clean table since we've tried multiple migrations, we're losing users.

**Comment by Dalmater** [comment]
I deleted all data and connected the clouds again. It works so far.
