### ISSUE TITLE
Adding cloud crash

### ISSUE THREAD

**Issue by quimsical** [TeamAmaze/AmazeFileManager#3677]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ c2q
* __Model:__ SM-N986U
* __Product:__ c2qsqw
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ClassCastException: com.amaze.filemanager.ui.fragments.FtpServerFragment cannot be cast to com.amaze.filemanager.ui.fragments.TabFragment
	at com.amaze.filemanager.ui.activities.MainActivity$FabActionListener.onActionSelected(MainActivity.java:2366)
	at com.leinardi.android.speeddial.SpeedDialView$1.onActionSelected(SpeedDialView.java:108)
	at com.leinardi.android.speeddial.FabWithLabelView$2.onClick(FabWithLabelView.java:214)
	at android.view.View.performClick(View.java:7881)
	at android.view.View.performClickInternal(View.java:7858)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30863)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3162
