### ISSUE TITLE
crash after trying to extract a password encrypted 7zip archive

### ISSUE THREAD

**Issue by bartoszluka** [TeamAmaze/AmazeFileManager#3689]
## Issue explanation (write below this line)

crash after trying to extract a password encrypted 7zip archive

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 32
* __Device:__ ASUS_AI2202
* __Model:__ ASUS_AI2202
* __Product:__ EU_AI2202
<details><summary><b>Crash log </b></summary><p>

```
com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
	at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:466)
	at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:2189)
	at com.amaze.filemanager.ui.dialogs.GeneralDialogCreation.showPasswordDialog(GeneralDialogCreation.java:789)
	at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.onProgressUpdate(ExtractService.java:390)
	at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.onProgressUpdate(ExtractService.java:230)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:241)
	at android.os.Looper.loop(Looper.java:358)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

```
</details>
<hr>

**Describe the bug**
After trying to extract a password encrypted 7zip archive, the app crashes.

**To Reproduce**
1. Click the 3 dots menu on a password encrypted 7zip archive
1. Choose "Extract"
1. See error

**Expected behavior**
An input field to insert password

**Comment by VishnuSanal** [comment]
dupe #3531 and fixed with #3650 - would be fixed with the next update

**Comment by Terkyz** [comment]
I know this is supposed to have been fixed a long time ago but I still have the same exact problem. I'm doing something wrong?

**Comment by VishnuSanal** [comment]
@Terkyz please install a progressive build APK from https://t.me/TeamAmaze & check whether these persists.

**Comment by Terkyz** [comment]
Is there any other place (repository) where can I download those APK? Sadly I don't use Telegram and I can not preview the channel.

**Comment by VishnuSanal** [comment]
@Terkyz [app.zip](https://github.com/TeamAmaze/AmazeFileManager/files/12908893/app.zip)

**Comment by Terkyz** [comment]
It works great! When are these changes likely to arrive in the stable version?

**Comment by VishnuSanal** [comment]
@Terkyz _"Very soon"_, atleast that's what we're planning!
