### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hsoftxl** [TeamAmaze/AmazeFileManager#3705]
## Exception
* __App Name:__ Amaze 文件管理器
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ PD2118
* __Model:__ V2118A
* __Product:__ PD2118
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:922)
Caused by: java.lang.NullPointerException: Attempt to read from field 'boolean com.amaze.filemanager.adapters.data.LayoutElementParcelable.isDirectory' on a null object reference
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.postListCustomPathProcess(LoadFilesListTask.java:268)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:193)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:85)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3673
