### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sarah2023** [TeamAmaze/AmazeFileManager#3715]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**
## Exception
* __App Name:__ File Manager
* __Package:__ com.ssands.file.manager
* __Version:__ 1.1
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux samsung/a03susq/a03su:12/SP1A.210812.016/A037USQU3BVK1:user/release-keys 12 - 31
* __Device:__ a03su
* __Model:__ SM-A037U
* __Product:__ a03susq
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at com.amaze.filemanager.ui.views.appbar.BottomBar$2.onLongPress(BottomBar.java:198)
	at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:986)
	at android.view.GestureDetector.access$400(GestureDetector.java:69)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:350)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
@sarah2023 Thanks for reporting!

But, that error report is not from the official app.

Get the official version from here

Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases
