### ISSUE TITLE
File's failing to extract and giving error.

### ISSUE THREAD

**Issue by SoniXperia** [TeamAmaze/AmazeFileManager#3717]
## Issue explanation (write below this line)
Every file I try to extract I get an error, in case you need to know what files I was extracting they're ".7z" files and they're 3ds ROMs (all the games I'm downloading are games that I already own and have paid for, just downloading them on mobile). Is it just not compatible with that file type? I can try with a different one.
This is my first time using this app and I don't know why it's happening. 

I've never done this before and don't know if I'm supposed to stick to some sort of format so I greatly apologize if this is the incorrect way or seems lazy but here's the error code.

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux motorola/odessa_retaile/odessa:11/RPA31.Q2-59-17-4-3/d278a:user/release-keys 11 - 30
* __Device:__ odessa
* __Model:__ moto g(9) plus
* __Product:__ odessa_retaile
<details><summary><b>Crash log </b></summary><p>

```
com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
	at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:466)
	at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:2189)
	at com.amaze.filemanager.ui.dialogs.GeneralDialogCreation.showPasswordDialog(GeneralDialogCreation.java:789)
	at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.onProgressUpdate(ExtractService.java:390)
	at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.onProgressUpdate(ExtractService.java:230)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7848)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
thanks for reporting, this is a duplicate to https://github.com/TeamAmaze/AmazeFileManager/issues/3531 and fixed with https://github.com/TeamAmaze/AmazeFileManager/pull/3650 - would be fixed with the next update

**Comment by yarons** [comment]
Apparently it was an encrypted archive, thanks.
