### ISSUE TITLE
`NPE` when going back from `/` in SFTP connection

### ISSUE THREAD

**Issue by chuckwagoncomputing** [TeamAmaze/AmazeFileManager#3738]
**Describe the bug**
If you try to go back from the root directory in an SFTP connection, it crashes.

**To Reproduce**
1. Connect to an SFTP server
2. Go back until you are at the root directory, then go back again.

**Expected behavior**
I think expected behaviour would be to either exit the SFTP connection, or display the "Press again to exit" prompt

**Smartphone (please complete the following information):**
 - Device: Oneplus 7T
 - OS: LineageOS 20
 - Rooted: No
 - Version: 3.8.5

**Additional context**
```
java.lang.NullPointerException: Attempt to read from null array
 at android.net.Uri$PathSegments.get(Uri.java:1029)
 at android.net.Uri$PathSegments.get(Uri.java:1011)
 at com.amaze.filemanager.filesystem.HybridFile.getParent(HybridFile.java:557)
 at com.amaze.filemanager.ui.fragments.MainFragment.goBack(MainFragment.java:1054)
 at com.amaze.filemanager.ui.activities.MainActivity.lambda$onBackPressed$6(MainActivity.java:909)
 at com.amaze.filemanager.ui.activities.MainActivity.$r8$lambda$fKbQXJTjmE3tEXFhvzq2Q8y2c_E(Unknown Source:0)
 at com.amaze.filemanager.ui.activities.MainActivity$$ExternalSyntheticLambda6.apply(Unknown Source:2)
 at com.amaze.filemanager.ui.activities.MainActivity.executeWithMainFragment(MainActivity.java:2518)
 at com.amaze.filemanager.ui.activities.MainActivity.executeWithMainFragment(MainActivity.java:2510)
 at com.amaze.filemanager.ui.activities.MainActivity.onBackPressed(MainActivity.java:907)
 at android.app.Activity.onKeyUp(Activity.java:3882)
 at android.view.KeyEvent.dispatch(KeyEvent.java:2935)
 at android.app.Activity.dispatchKeyEvent(Activity.java:4228)
 at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
 at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
 at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
 at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
 at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
 at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3090)
 at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:402)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6584)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6450)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5910)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6098)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5941)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6155)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5914)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5941)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5914)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6131)
 at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6311)
 at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3649)
 at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3169)
 at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3160)
 at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3626)
 at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
 at android.os.MessageQueue.nativePollOnce(Native Method)
 at android.os.MessageQueue.next(MessageQueue.java:335)
 at android.os.Looper.loopOnce(Looper.java:161)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7872)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by VishalNehra** [comment]
#3661 expecting this to be fixed in the pr. Please confirm @TranceLove
