### ISSUE TITLE
`ActivityNotFoundException` on `Utils#openURL`

### ISSUE THREAD

**Issue by lightningvr12** [TeamAmaze/AmazeFileManager#3756]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 10 - 29
* __Device:__ hollywood
* __Model:__ Quest
* __Product:__ hollywood
<details><summary><b>Crash log </b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.amaze.fileutilities }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5211)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at android.app.Activity.startActivityForResult(Activity.java:5169)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
	at android.app.Activity.startActivity(Activity.java:5540)
	at android.app.Activity.startActivity(Activity.java:5508)
	at com.amaze.filemanager.utils.Utils.openURL(Utils.java:380)
	at com.amaze.filemanager.ui.activities.UtilitiesAliasActivity.onCreate$lambda-0(UtilitiesAliasActivity.kt:46)
	at com.amaze.filemanager.ui.activities.UtilitiesAliasActivity.$r8$lambda$8quQpF0TkkkHRQu_61tXPbplAbc(Unknown Source:0)
	at com.amaze.filemanager.ui.activities.UtilitiesAliasActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:886)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7436)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```
</details>
<hr>

**Comment by lightningvr12** [comment]
this is the details.                 ## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 10 - 29
* __Device:__ hollywood
* __Model:__ Quest
* __Product:__ hollywood
<details><summary><b>Crash log </b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.amaze.fileutilities }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5211)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at android.app.Activity.startActivityForResult(Activity.java:5169)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
	at android.app.Activity.startActivity(Activity.java:5540)
	at android.app.Activity.startActivity(Activity.java:5508)
	at com.amaze.filemanager.utils.Utils.openURL(Utils.java:380)
	at com.amaze.filemanager.ui.activities.UtilitiesAliasActivity.onCreate$lambda-0(UtilitiesAliasActivity.kt:46)
	at com.amaze.filemanager.ui.activities.UtilitiesAliasActivity.$r8$lambda$8quQpF0TkkkHRQu_61tXPbplAbc(Unknown Source:0)
	at com.amaze.filemanager.ui.activities.UtilitiesAliasActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:886)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7436)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```
</details>
<hr>

**Comment by gustamor** [comment]
This `ActivityNotFoundException` actually affects 18 methods that use **Utils.openURL()** on non-browser-enabled systems.

Could I work on this issue?

**Comment by TranceLove** [comment]
@gustamor Yes sure. Just put up your pull request 😊
