### ISSUE TITLE
Application crash on UI Error when opening.

### ISSUE THREAD

**Issue by kaoliiny** [TeamAmaze/AmazeFileManager#3770]
**Describe the bug**
![Uploading Screenshot_20230327-092613.png…]()
## Exception
* __App Name:__ File Manager
* __Package:__ com.mfa.filemanager
* __Version:__ 2.1.12
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ redfin
* __Model:__ Pixel 5
* __Product:__ redfin
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Migration didn't properly handle: tab(com.mfa.filemanager.database.models.explorer.Tab).
 Expected:
TableInfo{name='tab', columns={tab_no=Column{name='tab_no', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, path=Column{name='path', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0, defaultValue='null'}, home=Column{name='home', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[], indices=[]}
 Found:
TableInfo{name='tab', columns={path=Column{name='path', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0, defaultValue='null'}, tab_no=Column{name='tab_no', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=1, defaultValue='null'}, home=Column{name='home', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[], indices=[]}
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:103)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:183)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:151)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:112)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:706)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:483)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:526)
	at androidx.room.util.DBUtil.query(DBUtil.java:86)
	at com.mfa.filemanager.database.daos.TabDao_Impl$7.call(TabDao_Impl.java:197)
	at com.mfa.filemanager.database.daos.TabDao_Impl$7.call(TabDao_Impl.java:194)
	at androidx.room.RxRoom$5.subscribe(RxRoom.java:229)
	at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to application icon
2. Click on to open it

**Expected behaviour**
Open the app

**Smartphone:**
 - Device: [Google Pixel 5]
 - OS: [Android 13]
 - Rooted: [No]
 - Version: [2.1.12]

**Additional context**
App crash when l open the app.

**Comment by VishnuSanal** [comment]
@kaoliiny Thanks for reporting!

But, that error report is not from the official app.

Get the official version from here

Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases
