### ISSUE TITLE
SMB related crash

### ISSUE THREAD

**Issue by seemebreakthis** [TeamAmaze/AmazeFileManager#3779]
**Describe the bug**
Crash when you open an smb connection, it shows the contents, then you hit the smb link up top, it shows the android icon inside a phone logo, and you hit that android logo, then it crashes everytime

**To Reproduce**
See above

**Expected behavior**
A change to the desired folder

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 11
 - OS: Android 12
 - Rooted: yes
 - Version: 3.8.4 (F-droid downloaded)

**Additional context**
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ venus
* __Model:__ M2011K2G
* __Product:__ venus_eea
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amaze.filemanager.filesystem.HybridFile.getPath()' on a null object reference
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listSmb(LoadFilesListTask.java:590)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:154)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:85)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
</details>
<hr>

**Comment by VishalNehra** [comment]
I think this was fixed with #3661
