### ISSUE TITLE
Amaze file maneger bug

### ISSUE THREAD

**Issue by jimbob000** [TeamAmaze/AmazeFileManager#3786]
i tried to open Amaze file Manager and it said there was a bugon my Oculus quest 2.

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 32
* __Device:__ hollywood
* __Model:__ Quest
* __Product:__ hollywood
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{b9c153b} (ae64de85-a538-48c0-a66d-32eb8ed97f61) is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:952)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:248)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3183)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:680)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:646)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2318)
	at androidx.fragment.app.FragmentManager.lambda$attachController$0(FragmentManager.java:2572)
	at androidx.fragment.app.FragmentManager.$r8$lambda$XfPeDpLzKWrJr916TDyhue4S3eM(Unknown Source:0)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda0.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.java:227)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.java:74)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:338)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1292)
	at android.app.Activity.performSaveInstanceState(Activity.java:2203)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1520)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5853)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5252)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5218)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5283)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2276)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:214)
	at android.os.Looper.loop(Looper.java:304)
	at android.app.ActivityThread.main(ActivityThread.java:7911)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1010)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #1555
