### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by shigetsune** [TeamAmaze/AmazeFileManager#3788]
## Issue explanation (write below this line)
It said me to report, I'm reporting 

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ vayu
* __Model:__ M2102J20SG
* __Product:__ vayu_global
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{f2ff17c} (37d6259a-7066-4f6b-bf92-cc6d62722be1) not attached to an activity.
	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:947)
	at com.amaze.filemanager.ui.fragments.MainFragment.requireMainActivity(MainFragment.java:1504)
	at com.amaze.filemanager.ui.fragments.MainFragment.lambda$reloadListElements$11(MainFragment.java:861)
	at com.amaze.filemanager.ui.fragments.MainFragment.$r8$lambda$qAri8iGrkP1Kp3pJkIpwLgJjNOk(Unknown Source:0)
	at com.amaze.filemanager.ui.fragments.MainFragment$$ExternalSyntheticLambda3.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3380
