### ISSUE TITLE
Crash when open directoy with @ sign

### ISSUE THREAD

**Issue by Offerel** [TeamAmaze/AmazeFileManager#3792]
**Describe the bug**
On my SFTP server, i have folders where the name of the folder contains an @ sign. If i open this folder with Amaze Filemanager, it crashes.

**To Reproduce**
1. Create SFTP connection
2. Open the connection
3. Open folder
4. Open folder with a @ sign in name
5. App crashes

**Expected behavior**
Folder can be opened

**Smartphone (please complete the following information):**
 - Device: Galaxy S23+
 - OS: Android 13
 - Rooted: [No]
 - Version: [3.8.4]

**Additional context**
If I create a symlink to the same folder, without the @ sign, i can open the folder. I don't know, if other signs are effected also.

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 104, end 10, length 115
	at java.lang.String.checkBoundsBeginEnd(String.java:3942)
	at java.lang.String.substring(String.java:2467)
	at com.amaze.filemanager.filesystem.ftp.NetCopyClientConnectionPool$ConnectionInfo.<init>(NetCopyClientConnectionPool.kt:406)
	at com.amaze.filemanager.filesystem.ftp.NetCopyClientConnectionPool.createSshClient(NetCopyClientConnectionPool.kt:252)
	at com.amaze.filemanager.filesystem.ftp.NetCopyClientConnectionPool.access$createSshClient(NetCopyClientConnectionPool.kt:48)
	at com.amaze.filemanager.filesystem.ftp.NetCopyClientConnectionPool$createNetCopyClient$1.invoke(NetCopyClientConnectionPool.kt:175)
	at com.amaze.filemanager.filesystem.ftp.NetCopyClientConnectionPool$createNetCopyClient$1.invoke(NetCopyClientConnectionPool.kt:173)
	at com.amaze.filemanager.filesystem.ftp.NetCopyClientConnectionPool.getConnection(NetCopyClientConnectionPool.kt:88)
	at com.amaze.filemanager.filesystem.ftp.NetCopyClientUtils.execute(NetCopyClientUtils.kt:83)
	at com.amaze.filemanager.filesystem.HybridFile.forEachChildrenFile(HybridFile.java:938)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listSftp(LoadFilesListTask.java:626)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:157)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:85)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

```

**Comment by Offerel** [comment]
Update: When i manually enter the directory name and us %40 instead of @, i can access the directory. But clicking such a directory leads to a crash. I have no skills in Java programming, but i assume, the filenames should properly urlencoded. Then it should work.

**Comment by TranceLove** [comment]
Should be fixed by #3661 for 4.0. Let's see it.

![device-2023-04-30-132251](https://user-images.githubusercontent.com/251819/235337265-fc96aee6-28fe-4fbd-8a69-4b908ea8b73c.gif)

**Comment by Offerel** [comment]
Is there any release or pre-release date or can be downloaded from github actions?

**Comment by VishalNehra** [comment]
> Is there any release or pre-release date or can be downloaded from github actions?

You can download from [this](https://github.com/TeamAmaze/AmazeFileManager/actions/runs/4865391945) github action. Release date isn't yet set.

**Comment by VishalNehra** [comment]
> Is there any release or pre-release date or can be downloaded from github actions?

You can also join our telegram channel for the apk. https://t.me/TeamAmaze

**Comment by Offerel** [comment]
Many thx. After testing, my issue with the @ sign is solved in this version. But a other dorectory is listed as empty. If I look at the server, this seems to be a bind mount. I'm not sure if this is responsible for not displaying the directory content. I will try to find the reason tomorrow.

Other file managers like Solid Explorer and Material Files can list the content of the directory. I will report if I find more info.

**Comment by VishalNehra** [comment]
> Many thx. After testing, my issue with the @ sign is solved in this version. But a other dorectory is listed as empty. If I look at the server, this seems to be a bind mount. I'm not sure if this is responsible for not displaying the directory content. I will try to find the reason tomorrow.
> 
> Other file managers like Solid Explorer and Material Files can list the content of the directory. I will report if I find more info.

@TranceLove

**Comment by Offerel** [comment]
Additionally hint: when I download a file via SFTP (SCP is not allowed there), the speed seems to be slow. I get around 4MB/s, the same as with Material Files. With Solid Explorer and the same connection and file, i have around 8MB/s. I haven't tested SCP for now.

**Comment by Offerel** [comment]
> Many thx. After testing, my issue with the @ sign is solved in this version. But a other dorectory is listed as empty. If I look at the server, this seems to be a bind mount. I'm not sure if this is responsible for not displaying the directory content. I will try to find the reason tomorrow.
> 
> Other file managers like Solid Explorer and Material Files can list the content of the directory. I will report if I find more info.

I have found more. Its not this special directory. If i open this directory directly after logging in, all is fine. However, when i have accessed a folder with this new version and i go back or up a directory, this appears as empty. All folders appears as empty, when i go back or up one level. Maybe its only a listing-refresh issue?
