### ISSUE TITLE
App crashes when tapping on certain bookmarks

### ISSUE THREAD

**Issue by ferpg81** [TeamAmaze/AmazeFileManager#3804]
## Issue explanation (write below this line)

when tap on a bookmark on internal sd (content://com.android.externalstorage.documents/tree/primary:Android/obb/net.osmand.plus/tracks), app crashes.

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux samsung/a33xnseea/a33x:13/TP1A.220624.014/A336BXXU4CWB2:user/release-keys 13 - 33
* __Device:__ a33x
* __Model:__ SM-A336B
* __Product:__ a33xnseea
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter rootUriString
	at com.amaze.filemanager.utils.OTGUtil.getDocumentFiles(Unknown Source:12)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listDocumentFilesInternal(LoadFilesListTask.java:754)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listDocumentFiles(LoadFilesListTask.java:661)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:167)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:85)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #2867
