### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by milad19s** [TeamAmaze/AmazeFileManager#3806]
crashed 

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ a51
* __Model:__ SM-A515F
* __Product:__ a51nsxx
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.ui.activities.MainActivity}: android.view.InflateException: Binary XML file line #108 in com.amaze.filemanager:layout/main_toolbar: Binary XML file line #108: You must supply a layout_width attribute., theme={InheritanceMap=[id=0x7f120353com.amaze.filemanager:style/pref_accent_light_pink, id=0x7f120317com.amaze.filemanager:style/appCompatLight, id=0x7f1201d1com.amaze.filemanager:style/Theme.AppCompat.Light.NoActionBar, id=0x7f1201cbcom.amaze.filemanager:style/Theme.AppCompat.Light, id=0x7f120054com.amaze.filemanager:style/Base.Theme.AppCompat.Light, id=0x7f120099com.amaze.filemanager:style/Base.V28.Theme.AppCompat.Light, id=0x7f120096com.amaze.filemanager:style/Base.V26.Theme.AppCompat.Light, id=0x7f120094com.amaze.filemanager:style/Base.V23.Theme.AppCompat.Light, id=0x7f120092com.amaze.filemanager:style/Base.V22.Theme.AppCompat.Light, id=0x7f120089com.amaze.filemanager:style/Base.V21.Theme.AppCompat.Light, id=0x7f12009ccom.amaze.filemanager:style/Base.V7.Theme.AppCompat.Light, id=0x7f120103com.amaze.filemanager:style/Platform.AppCompat.Light, id=0x7f12010ecom.amaze.filemanager:style/Platform.V25.AppCompat.Light, id=0x1030241android:style/Theme.Material.Light.NoActionBar, id=0x1030237android:style/Theme.Material.Light, id=0x103000candroid:style/Theme.Light, id=0x1030005android:style/Theme], Themes=[com.amaze.filemanager:style/pref_accent_light_pink, forced, com.amaze.filemanager:style/appCompatBlack, forced, com.amaze.filemanager:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: android.view.InflateException: Binary XML file line #108 in com.amaze.filemanager:layout/main_toolbar: Binary XML file line #108: You must supply a layout_width attribute., theme={InheritanceMap=[id=0x7f120353com.amaze.filemanager:style/pref_accent_light_pink, id=0x7f120317com.amaze.filemanager:style/appCompatLight, id=0x7f1201d1com.amaze.filemanager:style/Theme.AppCompat.Light.NoActionBar, id=0x7f1201cbcom.amaze.filemanager:style/Theme.AppCompat.Light, id=0x7f120054com.amaze.filemanager:style/Base.Theme.AppCompat.Light, id=0x7f120099com.amaze.filemanager:style/Base.V28.Theme.AppCompat.Light, id=0x7f120096com.amaze.filemanager:style/Base.V26.Theme.AppCompat.Light, id=0x7f120094com.amaze.filemanager:style/Base.V23.Theme.AppCompat.Light, id=0x7f120092com.amaze.filemanager:style/Base.V22.Theme.AppCompat.Light, id=0x7f120089com.amaze.filemanager:style/Base.V21.Theme.AppCompat.Light, id=0x7f12009ccom.amaze.filemanager:style/Base.V7.Theme.AppCompat.Light, id=0x7f120103com.amaze.filemanager:style/Platform.AppCompat.Light, id=0x7f12010ecom.amaze.filemanager:style/Platform.V25.AppCompat.Light, id=0x1030241android:style/Theme.Material.Light.NoActionBar, id=0x1030237android:style/Theme.Material.Light, id=0x103000candroid:style/Theme.Light, id=0x1030005android:style/Theme], Themes=[com.amaze.filemanager:style/pref_accent_light_pink, forced, com.amaze.filemanager:style/appCompatBlack, forced, com.amaze.filemanager:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
Caused by: java.lang.UnsupportedOperationException: Binary XML file line #108: You must supply a layout_width attribute., theme={InheritanceMap=[id=0x7f120353com.amaze.filemanager:style/pref_accent_light_pink, id=0x7f120317com.amaze.filemanager:style/appCompatLight, id=0x7f1201d1com.amaze.filemanager:style/Theme.AppCompat.Light.NoActionBar, id=0x7f1201cbcom.amaze.filemanager:style/Theme.AppCompat.Light, id=0x7f120054com.amaze.filemanager:style/Base.Theme.AppCompat.Light, id=0x7f120099com.amaze.filemanager:style/Base.V28.Theme.AppCompat.Light, id=0x7f120096com.amaze.filemanager:style/Base.V26.Theme.AppCompat.Light, id=0x7f120094com.amaze.filemanager:style/Base.V23.Theme.AppCompat.Light, id=0x7f120092com.amaze.filemanager:style/Base.V22.Theme.AppCompat.Light, id=0x7f120089com.amaze.filemanager:style/Base.V21.Theme.AppCompat.Light, id=0x7f12009ccom.amaze.filemanager:style/Base.V7.Theme.AppCompat.Light, id=0x7f120103com.amaze.filemanager:style/Platform.AppCompat.Light, id=0x7f12010ecom.amaze.filemanager:style/Platform.V25.AppCompat.Light, id=0x1030241android:style/Theme.Material.Light.NoActionBar, id=0x1030237android:style/Theme.Material.Light, id=0x103000candroid:style/Theme.Light, id=0x1030005android:style/Theme], Themes=[com.amaze.filemanager:style/pref_accent_light_pink, forced, com.amaze.filemanager:style/appCompatBlack, forced, com.amaze.filemanager:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:839)
	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:8602)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8800)
	at androidx.drawerlayout.widget.DrawerLayout$LayoutParams.<init>(DrawerLayout.java:2319)
	at androidx.drawerlayout.widget.DrawerLayout.generateLayoutParams(DrawerLayout.java:1906)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1147)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:491)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
	at com.amaze.filemanager.ui.activities.MainActivity.onCreate(MainActivity.java:337)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by VishnuSanal** [comment]
dupe #2105
