### ISSUE TITLE
App/ui crash

### ISSUE THREAD

**Issue by queen-marie** [TeamAmaze/AmazeFileManager#3813]
## Exception
* __App Name:__ Bussid File Manager
* __Package:__ com.studio78.bussidfilemanager
* __Version:__ 4.0
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ a32x
* __Model:__ SM-S326DL
* __Product:__ a32xtfn
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service com.studio78.bussidfilemanager.asynchronous.services.ExtractService@e6487ca with Intent { cmp=com.studio78.bussidfilemanager/.asynchronous.services.ExtractService (has extras) }: java.lang.IllegalArgumentException: com.studio78.bussidfilemanager: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5261)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2447)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.IllegalArgumentException: com.studio78.bussidfilemanager: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:491)
	at android.app.PendingIntent.getActivity(PendingIntent.java:477)
	at android.app.PendingIntent.getActivity(PendingIntent.java:441)
	at com.studio78.bussidfilemanager.asynchronous.services.ExtractService.onStartCommand(ExtractService.java:113)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5243)
	... 9 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
@queen-marie Thanks for reporting!

But, that error report is not from the official app.

Get the official version from here

Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases
