### ISSUE TITLE
MainFragment crash when compressing

### ISSUE THREAD

**Issue by Obolrom** [TeamAmaze/AmazeFileManager#3848]
## Issue explanation (write below this line)

Steps to reproduce:
1) Open the amaze app
2) select folder to compress
3) start compressing the folder
4) immediately change screen orientation or minimize the app

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager.debug
* __Version:__ 3.8.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ amber
* __Model:__ 21081111RG
* __Product:__ amber_global
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{a4cbc50} (ca6bb8c9-5af2-4e8b-81b7-f7ccf26cd1d2) is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:952)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:249)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3183)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:680)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:646)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2318)
	at androidx.fragment.app.FragmentManager.lambda$attachController$0$androidx-fragment-app-FragmentManager(FragmentManager.java:2572)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda0.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.java:227)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.java:74)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:338)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1298)
	at android.app.Activity.performSaveInstanceState(Activity.java:2309)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1596)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5956)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5349)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5910)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5828)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8143)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

```
</details>
<hr>

**Comment by Obolrom** [comment]
Duplicated issue: https://github.com/TeamAmaze/AmazeFileManager/issues/3847
