### ISSUE TITLE
Help Crazy Hacker i think uses framework

### ISSUE THREAD

**Issue by EpicI4z1** [TeamAmaze/AmazeFileManager#3857]
## Issue explanation (write below this line)
so dude has hacked me for over a year now, destroyes my lufe took my credit fpr almost 700 down to 420. cpst me roughly $100k- not including losses from lossingy jobs , hacking my doordash account, siphoning money. prettyuch driving me to the brinl of destruction!

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux OnePlus/GN2200/OP515AL1:12/RKQ1.211119.001/d7acd9-22c7e-1296c3:user/release-keys 12 - 31
* __Device:__ OP515AL1
* __Model:__ GN2200
* __Product:__ GN2200
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amaze.filemanager.adapters.AppsRecyclerAdapter.setData(java.util.List, boolean)' on a null object reference
	at com.amaze.filemanager.ui.fragments.AppsListFragment.onOptionsItemSelected(AppsListFragment.java:157)
	at com.amaze.filemanager.ui.activities.MainActivity.onOptionsItemSelected(MainActivity.java:1133)
	at android.app.Activity.onMenuItemSelected(Activity.java:4420)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:328)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:221)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:352)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1235)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3232)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:349)
	at android.app.ActivityThread.main(ActivityThread.java:8241)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```
</details>
<hr>
*

**Comment by EpicI4z1** [comment]
i Currently have it contained i think by ziping all folders at onces and then encryptes the files  and zipped again. seems like hers idk limited with dev block + deny on folderfile. someone wanna give me some pointers i dont know shit about coding

**Comment by VishnuSanal** [comment]
Hi, I don't understand the details you mentioned about you getting hacked, but the crash report present in the report is already report & being tracked with #3050
