### ISSUE TITLE
App/UI crashed when create a unknown Cloud Connection

### ISSUE THREAD

**Issue by ssssy1000** [TeamAmaze/AmazeFileManager#3885]
**Describe the bug**

**To Reproduce**
1. Create Cloud Connection
2. Choose SMB Connection
3. Click USE CUSTOM IP 
4. Input 'test.com' and click CREATE
5. After it loaded, the app crashes

**Expected behavior**
The app crashed when create a unknown Cloud Connection.

**Screenshots**
<img width="200" alt="1689080891109" src="https://github.com/TeamAmaze/AmazeFileManager/assets/98003627/7f6d2ac2-7dc2-4e3e-a689-01646f677806">
<img width="200" alt="1689080891109" src="https://github.com/TeamAmaze/AmazeFileManager/assets/98003627/d9e45c7b-aaa3-4a5e-8d0f-d3b6d6d85b9d">
<img width="200" alt="1689080907052" src="https://github.com/TeamAmaze/AmazeFileManager/assets/98003627/42027c8c-70fb-4d32-9d5d-f49dcaf7e678">
<img width="200" alt="1689080939807" src="https://github.com/TeamAmaze/AmazeFileManager/assets/98003627/6dc00773-9b9d-4eed-a569-9ce797acbfd3">
<img width="200" alt="1689080841290" src="https://github.com/TeamAmaze/AmazeFileManager/assets/98003627/3582b1c3-d8b1-4319-86d6-f2b633f92bc7">
**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android 7.1.1
 - Rooted: No
 - Version: 3.8.5

**Crash Logs**
```
java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=-1
	at java.lang.String.substring(String.java:1931)
	at com.amaze.filemanager.ui.dialogs.SmbConnectDialog.onCreateDialog(SmbConnectDialog.java:268)
	at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:647)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:561)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1698)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:492)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by TranceLove** [comment]
Hopefully fixed by #3661

**Comment by millsmcewan** [comment]
Hello.  Sorry for being dense, but is this meant to be fixed?  It's not working on v3.9 on Samsung Galaxy tab s5e.  Thanks

**Comment by VishnuSanal** [comment]
> Hello. Sorry for being dense, but is this meant to be fixed? It's not working on v3.9 on Samsung Galaxy tab s5e. Thanks


this was not fixed. :(
