### ISSUE TITLE
Unexpected App Crash when Selecting 'Cloud Connection' Option 

### ISSUE THREAD

**Issue by S-Downes** [TeamAmaze/AmazeFileManager#3899]
**Describe the bug**
When selecting the option 'Cloud Connection', the app crashed unexpectedly (menu options for cloud connection such as 'SMB Connection' etc did not appear).  

**To Reproduce**
1. Go to 'folder within mobile's internal storage directory',
2. Click on '+', then 'Cloud Connection',
3. ~3. Scroll down to '....'~,
4. See error.

**Expected behavior**
To see the options in order to create a new cloud connection.

**Smartphone (please complete the following information):**
 - Device: Oppo-A53
 - OS: Android 12
 - Rooted: No
 - Version: 3.8.5

**Additional context**
Crash log output attached:

[App Crash Log_07-08-23.txt](https://github.com/TeamAmaze/AmazeFileManager/files/12290185/App.Crash.Log_07-08-23.txt)

## Issue explanation (write below this line)

App crashed when selecting the 'Cloud Connection' option.

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ OP4EFDL1
* __Model:__ CPH2127
* __Product:__ CPH2127EEA
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ClassCastException: com.amaze.filemanager.ui.fragments.AppsListFragment cannot be cast to com.amaze.filemanager.ui.fragments.TabFragment
	at com.amaze.filemanager.ui.activities.MainActivity$FabActionListener.onActionSelected(MainActivity.java:2378)
	at com.leinardi.android.speeddial.SpeedDialView$1.onActionSelected(SpeedDialView.java:108)
	at com.leinardi.android.speeddial.FabWithLabelView$2.onClick(FabWithLabelView.java:214)
	at android.view.View.performClick(View.java:7488)
	at android.view.View.performClickInternal(View.java:7464)
	at android.view.View.access$3700(View.java:841)
	at android.view.View$PerformClick.run(View.java:28911)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
thanks for reporting, please track with #3785 (duplicate)
