### ISSUE TITLE
App ui crash

### ISSUE THREAD

**Issue by amanrj725** [TeamAmaze/AmazeFileManager#3918]
## Exception
* __App Name:__ File Manager
* __Package:__ com.filemanager.lnapp
* __Version:__ 3.5.97
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ OnePlus8T
* __Model:__ KB2001
* __Product:__ OnePlus8T_IND
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: com.filemanager.lnapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:402)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:485)
	at android.app.PendingIntent.getActivity(PendingIntent.java:471)
	at android.app.PendingIntent.getActivity(PendingIntent.java:435)
	at com.google.firebase.messaging.zzb.zza(com.google.firebase:firebase-messaging@@20.0.0:59)
	at com.google.firebase.messaging.zzd.zza(com.google.firebase:firebase-messaging@@20.0.0:33)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.0.0:60)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.0.0:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

**Comment by VishalNehra** [comment]
Thanks for reporting!

But, that error report is not from the official app.

Get the official version from here

Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases
