### ISSUE TITLE
Adobe?

### ISSUE THREAD

**Issue by XxchainedxX** [TeamAmaze/AmazeFileManager#3926]
## Issue explanation (write below this line)
Can anyone tell me what this is on my Motorola? I was trying to open a random Adobe file that I have never seen on my phone before.

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux motorola/milanf_g/milanf:12/S1SD32.56-64/31f16-3bcca:user/release-keys 12 - 31
* __Device:__ milanf
* __Model:__ moto g stylus 5G (2022)
* __Product:__ milanf_g
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
	at com.amaze.filemanager.ui.fragments.MainFragment.returnIntentResults(MainFragment.java:531)
	at com.amaze.filemanager.ui.ItemPopupMenu.onMenuItemClick(ItemPopupMenu.java:238)
	at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:109)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3216)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4204)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3945)
	at android.widget.DropDownListView.onTouchEvent(DropDownListView.java:116)
	at android.view.View.dispatchTouchEvent(View.java:14601)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3114)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2787)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2572)
	at android.view.View.dispatchPointerEvent(View.java:14884)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6595)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6396)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5874)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5931)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5897)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6062)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5905)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6119)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5878)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5931)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5897)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5905)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5878)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8891)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8807)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8776)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9027)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:266)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:342)
	at android.os.Looper.loopOnce(Looper.java:182)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8089)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
hi, thanks for reaching out. please provide the following details:

- What type of file were you trying to open?
- On which directory was the file located?
- What Android version are you on?

**Comment by VishnuSanal** [comment]
also, dupe #3055
