### ISSUE TITLE
crash when copying files between folders in android/data

### ISSUE THREAD

**Issue by Fern-Leaves** [TeamAmaze/AmazeFileManager#3943]
## Issue explanation
I tried to copy folders from one app's data folder to another app's data folder and each time I've tried to do this this has happened 

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ panther
* __Model:__ Pixel 7
* __Product:__ panther
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.documentfile.provider.DocumentFile.isDirectory()' on a null object reference
	at com.amaze.filemanager.filesystem.HybridFile.isDirectory(HybridFile.java:663)
	at com.amaze.filemanager.filesystem.files.FileUtils.getBaseFileSize(FileUtils.java:213)
	at com.amaze.filemanager.filesystem.files.FileUtils.getTotalBytes(FileUtils.java:207)
	at com.amaze.filemanager.asynchronous.asynctasks.movecopy.PrepareCopyTask.doInBackground(PrepareCopyTask.java:147)
	at com.amaze.filemanager.asynchronous.asynctasks.movecopy.PrepareCopyTask.doInBackground(PrepareCopyTask.java:68)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3816
