### ISSUE TITLE
I'm not sure what's going on 😭 bug@mcwimpy#001

### ISSUE THREAD

**Issue by mcwimpy** [TeamAmaze/AmazeFileManager#3967]
**Describe the bug**

**To Reproduce**
1. Go to 'i did nothing'
2. Click on 'this just jumped at me'
3. Scroll down to 'randomly and out of nowhere'
5. See error

**Expected behavior**
Do not show up, leave me alone.

**Screenshots**
I'll try to make one....

**Smartphone (please complete the following information):**
 - Device: Samsung Tablet S6 lite
 - OS: Robot number 5 is alive, *jk*, android data, *jk* Androi13, OneUI5.1.1
 - Rooted: No
 - Version: 3.8.5

**Additional context**
I love the guru mediation message though, Amiga retro style, which is the only reason I'm going through this ordeal, may it serve you well, and the force be with you!

**Comment by mcwimpy** [comment]
![Screenshot_20231025_000716_Settings](https://github.com/TeamAmaze/AmazeFileManager/assets/11300847/26d8169c-e1e5-4cc5-b8e4-b0d3405cd820)
![Screenshot_20231025_000540_Amaze](https://github.com/TeamAmaze/AmazeFileManager/assets/11300847/b7c935bd-d86a-4b05-a02a-c48ef5e390db)
## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze Dateimanager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ gta4xl
* __Model:__ SM-P615
* __Product:__ gta4xleea
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{2e1821b} (fff02d21-e4da-4ab7-97c7-6b0714c3a44d) is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:952)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:248)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3183)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:680)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:646)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2318)
	at androidx.fragment.app.FragmentManager.lambda$attachController$0(FragmentManager.java:2572)
	at androidx.fragment.app.FragmentManager.$r8$lambda$XfPeDpLzKWrJr916TDyhue4S3eM(Unknown Source:0)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda0.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.java:227)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.java:74)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:338)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1292)
	at android.app.Activity.performSaveInstanceState(Activity.java:2282)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1596)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:6551)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5864)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5824)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5895)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2584)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
</details>
<hr>
