### ISSUE TITLE
`NPE` when granting SAF access and changed to dark mode

### ISSUE THREAD

**Issue by seelchen** [TeamAmaze/AmazeFileManager#3992]
**Describe the bug**
The app theme was "System" theme and the phone in light mode. When granting SAF access in the system's file manager, I changed the phone to dark mode. After clicking on "Allow access" and returning to Amaze, the app crashed.

It doesn't seem to happen when changing dark mode to light mode.

**To Reproduce**
1. Select "System" theme as app theme and have phone in light mode
2. Click on a directory for which Amaze doesn't have access yet
3. Change the phone to dark mode
4. Click on "Allow Access"

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
 - Device: Pixel 7 emulator
 - OS: Android 13
 - Rooted: Yes
 - Version: built from branch `release/4.0`
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.getColor(int)' on a null object reference
	at com.amaze.filemanager.utils.Utils.getColor(Utils.java:152)
	at com.amaze.filemanager.ui.fragments.MainFragment.initNoFileLayout(MainFragment.java:793)
	at com.amaze.filemanager.ui.fragments.MainFragment.reloadListElements(MainFragment.java:958)
	at com.amaze.filemanager.ui.fragments.MainFragment.setListElements(MainFragment.java:819)
	at com.amaze.filemanager.ui.fragments.MainFragment.lambda$loadlist$3$com-amaze-filemanager-ui-fragments-MainFragment(MainFragment.java:691)
	at com.amaze.filemanager.ui.fragments.MainFragment$$ExternalSyntheticLambda3.onAsyncTaskFinished(Unknown Source:8)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:208)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:87)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
thanks for taking the effort to report this bug after stress testing! but, this issue is already reported, please track with #2514
