### ISSUE TITLE
SSH/SFTP connection shows "No File"

### ISSUE THREAD

**Issue by windforain** [TeamAmaze/AmazeFileManager#4018]
**Describe the bug**
In version 3.8.5 (9a11e3e4bf800abf925130f6aec9a3e939e71254), the SSH/SFTP connection to my Alibaba Cloud SFTP Server showed "No file" instead of displaying right files. 
While in version 3.8.4 (0185003458dedbeddf7cf4a3c8a2d9c1dbaccda7), I repeated the same procedure, and got the right result.

**To Reproduce**
1. Create Cloud Connection
2. Choose SCP/SFTP Connection
3. Choose SSH/SFTP Protocol
4. Input the IP Address, Username, and Password
5. Click CREATE
6. It Showed a popup-window "Login Failure: wrong username or password."
7. It Jumped to the "SCP/SFTP connection" Page but Displayed "No file", and Showed the popup-window in Procedure 6 Again. 

**Expected behavior**
Get files on SFTP Server displayed.

**Screenshots**
In version 3.8.5: 
<img src = "https://github.com/TeamAmaze/AmazeFileManager/assets/81569261/35116b75-8ac7-480a-8722-08bb6b71c628" width = "300px"><img src = "https://github.com/TeamAmaze/AmazeFileManager/assets/81569261/e06e4f57-3610-4974-bb90-f819e32cd620" width = "300px"><img src = "https://github.com/TeamAmaze/AmazeFileManager/assets/81569261/cc343494-9b6a-40e4-aa85-e65ac361e5d4" width = "300px">

In **version 3.8.4** with same procedure: 
<img src = "https://github.com/TeamAmaze/AmazeFileManager/assets/81569261/dece05f2-02fa-4864-b469-d329bb0bbcb1" width = "300px"><img src = "https://github.com/TeamAmaze/AmazeFileManager/assets/81569261/43ad25a3-4810-497e-bc4b-debb651ac757" width = "300px">

**Smartphone (please complete the following information):**
 - Device: [houji (Xiaomi 14)]
 - OS: [Linux Android 14 - 34]
 - Rooted: [No]
 - Version: [3.8.5]

**Additional context**
I have tried to enter a wrong password deliberately, and the APP showed the response only in Procedure 6, not in Procedure 7, which is a right response.

And here's the related trace stack: 
```
sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda22@5074f1f
2023-12-18 22:49:11.155 31595-31659 OpenGLRenderer          com.amaze.filemanager.debug          D  endAllActiveAnimators on 0xb400007b8deb8800 (RippleDrawable) with handle 0xb400007b6ff94c20
2023-12-18 22:49:11.268 31595-31658 TrafficStats            com.amaze.filemanager.debug          D  tagSocket(148) with statsTag=0xffffffff, statsUid=-1
2023-12-18 22:49:11.579 31595-31595 WindowOnBackDispatcher  com.amaze.filemanager.debug          W  sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda22@c412cde
2023-12-18 22:49:11.584 31595-31840 c.a.f.d.UtilsHandler    com.amaze.filemanager.debug          E  [AsyncTask #3        ] Error getting auth private key for URI [ssh://root:LW_s3pJ7N4iA-rDyFVuHQZjr_3DoQ-5j7DP-GKXy3Lwe@106.15.75.216:22]androidx.room.EmptyResultSetException: Query returned empty result set: SELECT ssh_key FROM sftp WHERE path = ?
                                                                                                    	at com.amaze.filemanager.database.daos.SftpEntryDao_Impl$14.call(SftpEntryDao_Impl.java:553)
                                                                                                    	at com.amaze.filemanager.database.daos.SftpEntryDao_Impl$14.call(SftpEntryDao_Impl.java:537)
                                                                                                    	at androidx.room.RxRoom$5.subscribe(RxRoom.java:232)
                                                                                                    	at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3603)
                                                                                                    	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                                                    	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2023-12-18 22:49:11.600 31595-31595 Choreographer           com.amaze.filemanager.debug          I  Skipped 54 frames!  The application may be doing too much work on its main thread.
2023-12-18 22:49:11.631 31595-31674 TrafficStats            com.amaze.filemanager.debug          D  tagSocket(143) with statsTag=0xffffffff, statsUid=-1
2023-12-18 22:49:11.656  2424-2458  misight_perf            misight                              E   [902001001, com.amaze.filemanager.debug, 31595, long running]
2023-12-18 22:49:11.658 31595-31595 LeakCanary              com.amaze.filemanager.debug          D  Watching instance of androidx.loader.app.LoaderManagerImpl$LoaderViewModel (androidx.loader.app.LoaderManagerImpl$LoaderViewModel received ViewModel#onCleared() callback) with key d83b2d8b-2dba-4742-8302-4942749db912
2023-12-18 22:49:11.658 31595-31595 LeakCanary              com.amaze.filemanager.debug          D  Watching instance of androidx.lifecycle.SavedStateHandlesVM (androidx.lifecycle.SavedStateHandlesVM received ViewModel#onCleared() callback) with key 97d4ab1c-950b-446f-a3d3-ddbfdc0eaeb6
2023-12-18 22:49:11.658 31595-31595 LeakCanary              com.amaze.filemanager.debug          D  Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key 8ff7cb8c-8fc5-40b7-bb71-0e77bbc3c7be
2023-12-18 22:49:11.658 31595-31595 LeakCanary              com.amaze.filemanager.debug          D  Watching instance of com.amaze.filemanager.ui.dialogs.SftpConnectDialog (com.amaze.filemanager.ui.dialogs.SftpConnectDialog received Fragment#onDestroy() callback) with key 4e4b5ea2-0add-48ed-a544-0ffcc385d091
2023-12-18 22:49:11.666  2424-2458  misight_perf            misight                              E   [902001003, com.amaze.filemanager.debug, 31595, doframe latency due to msg]
2023-12-18 22:49:11.678 31595-31595 HandWritingStubImpl     com.amaze.filemanager.debug          I  refreshLastKeyboardType: 1
2023-12-18 22:49:11.678 31595-31595 HandWritingStubImpl     com.amaze.filemanager.debug          I  getCurrentKeyboardType: 1
2023-12-18 22:49:11.690 31595-31595 HandWritingStubImpl     com.amaze.filemanager.debug          I  refreshLastKeyboardType: 1
2023-12-18 22:49:11.690 31595-31595 HandWritingStubImpl     com.amaze.filemanager.debug          I  getCurrentKeyboardType: 1
2023-12-18 22:49:14.220 31595-31840 c.a.f.d.UtilsHandler    com.amaze.filemanager.debug          E  [AsyncTask #3        ] Error getting auth private key for URI [ssh://root:LW_s3pJ7N4iA-rDyFVuHQZjr_3DoQ-5j7DP-GKXy3Lwe@106.15.75.216:22]androidx.room.EmptyResultSetException: Query returned empty result set: SELECT ssh_key FROM sftp WHERE path = ?
                                                                                                    	at com.amaze.filemanager.database.daos.SftpEntryDao_Impl$14.call(SftpEntryDao_Impl.java:553)
                                                                                                    	at com.amaze.filemanager.database.daos.SftpEntryDao_Impl$14.call(SftpEntryDao_Impl.java:537)
                                                                                                    	at androidx.room.RxRoom$5.subscribe(RxRoom.java:232)
                                                                                                    	at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3603)
                                                                                                    	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                                                    	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2023-12-18 22:49:14.220 31595-31595 Compatibil...geReporter com.amaze.filemanager.debug          D  Compat change id reported: 147798919; UID 10318; state: ENABLED
2023-12-18 22:49:14.257 31595-31671 TrafficStats            com.amaze.filemanager.debug          D  tagSocket(108) with statsTag=0xffffffff, statsUid=-1
2023-12-18 22:49:16.707 31595-31652 lemanager.debug         com.amaze.filemanager.debug          I  This is non sticky GC, maxfree is 33554432 minfree is 8388608
2023-12-18 22:49:16.707 31595-31652 lemanager.debug         com.amaze.filemanager.debug          I  Explicit concurrent copying GC freed 543541(20MB) AllocSpace objects, 11(620KB) LOS objects, 74% free, 11MB/46MB, paused 148us,16us total 48.014ms
2023-12-18 22:49:21.250 31595-31595 AutofillManager         com.amaze.filemanager.debug          W  setSaveUiState(915217516, false) called on existing session 915217516; cancelling it
2023-12-18 22:49:21.292 31595-31595 HandWritingStubImpl     com.amaze.filemanager.debug          I  refreshLastKeyboardType: 1
2023-12-18 22:49:21.292 31595-31595 HandWritingStubImpl     com.amaze.filemanager.debug          I  getCurrentKeyboardType: 1
```

**Comment by VishnuSanal** [comment]
thanks for this descriptive report! @TranceLove would have a word here :)

**Comment by MatheusJCastro** [comment]
Any update on this? The problem persist in version 3.10 (from F-Droid).

**Comment by Fmstrat** [comment]
Also persists in latest version. Unfortunately makes Amaze unusable for our use case.
