### ISSUE TITLE
crash when opening a .7z file 

### ISSUE THREAD

**Issue by rexendevar** [TeamAmaze/AmazeFileManager#4058]
## Issue explanation (write below this line)

attempted to open a .7z file, pressed back button twice when it hung

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ FP5
* __Model:__ FP5
* __Product:__ FP5
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.getColor(int)' on a null object reference
	at androidx.core.content.ContextCompat$Api23Impl$$ExternalSyntheticApiModelOutline1.m(Unknown Source:0)
	at com.amaze.filemanager.utils.Utils.getColor(Utils.java:141)
	at com.amaze.filemanager.ui.fragments.MainFragment.initNoFileLayout(MainFragment.java:713)
	at com.amaze.filemanager.ui.fragments.MainFragment.reloadListElements(MainFragment.java:878)
	at com.amaze.filemanager.ui.fragments.MainFragment.setListElements(MainFragment.java:739)
	at com.amaze.filemanager.ui.fragments.MainFragment.lambda$loadlist$3(MainFragment.java:611)
	at com.amaze.filemanager.ui.fragments.MainFragment.$r8$lambda$9qQv21X8JwPlLXi_cDXfu4p-_VI(Unknown Source:0)
	at com.amaze.filemanager.ui.fragments.MainFragment$$ExternalSyntheticLambda6.onAsyncTaskFinished(Unknown Source:8)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:206)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:85)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #2514

**Comment by VishnuSanal** [comment]
thanks for taking the effort to report this bug! but, this issue is already reported, please track with #2514 :)
