### ISSUE TITLE
Error while relocating zip

### ISSUE THREAD

**Issue by naughty-kitten** [TeamAmaze/AmazeFileManager#4244]
**Describe the bug**

**To Reproduce**

**Expected behavior**
The app gives error when relocating a .zip file from internal storage to sd card in samsung galaxy tab a6 2016 with android 8.1

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux samsung/gtaxlwifixx/gtaxlwifi:8.1.0/M1AJQ/T580XXU4CSA1:user/release-keys 8.1.0 - 27
* __Device:__ gtaxlwifi
* __Model:__ SM-T580
* __Product:__ gtaxlwifixx
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:204)
	at android.os.Handler.<init>(Handler.java:118)
	at android.app.Dialog.<init>(Dialog.java:142)
	at android.app.Dialog.<init>(Dialog.java:194)
	at com.afollestad.materialdialogs.DialogBase.<init>(DialogBase.java:18)
	at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:87)
	at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:2183)
	at com.amaze.filemanager.utils.MainActivityHelper.guideDialogForLEXA(MainActivityHelper.java:321)
	at com.amaze.filemanager.utils.MainActivityHelper.guideDialogForLEXA(MainActivityHelper.java:294)
	at com.amaze.filemanager.utils.MainActivityHelper.checkFolder(MainActivityHelper.java:465)
	at com.amaze.filemanager.asynchronous.asynctasks.movecopy.PreparePasteTask.finishCopying(PreparePasteTask.kt:336)
	at com.amaze.filemanager.asynchronous.asynctasks.movecopy.PreparePasteTask.access$finishCopying(PreparePasteTask.kt:64)
	at com.amaze.filemanager.asynchronous.asynctasks.movecopy.PreparePasteTask$resolveConflict$1.invokeSuspend(PreparePasteTask.kt:320)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a090d91, Dispatchers.Default]

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #4099
