### ISSUE TITLE
Audio player: TransactionTooLargeException: data parcel size 1131268 bytes

### ISSUE THREAD

**Issue by czarnyckm** [TeamAmaze/AmazeFileManager#4268]
**Describe the bug**
Every time when I try to play a song from huge music library with about 5000 songs the TransactionTooLargeException is thrown see below for stactrace

**To Reproduce**
1. Go to Audio files
2. Click on any song to play
3. See error

**Expected behavior**

 ## Exception
* __App Name:__ Amaze File Utilities
* __Package:__ com.amaze.fileutilities
* __Version:__ v1.94
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 15 - 35
* __Device:__ cheetah
* __Model:__ Pixel 7 Pro
* __Product:__ cheetah
* __Device ID:__ ef91f17cc785b4cb3323ef8ca31e11a8354cba3a77741e234bf56096adf36d33
<details><summary><b>Crash log </b></summary>

```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1131268 bytes
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2019)
	at android.app.ContextImpl.startService(ContextImpl.java:1960)
	at android.content.ContextWrapper.startService(ContextWrapper.java:827)
	at android.content.ContextWrapper.startService(ContextWrapper.java:827)
	at com.amaze.fileutilities.utilis.f.r(Extensions.kt:6)
	at com.amaze.fileutilities.audio_player.AudioPlayerService$a.a(AudioPlayerService.kt:38)
	at com.amaze.fileutilities.home_page.ui.files.n0.invoke(MediaFileAdapter.kt:17)
	at l4.s.invokeSuspend(Extensions.kt:53)
	at q8.a.resumeWith(ContinuationImpl.kt:9)
	at g9.h0.run(DispatchedTask.kt:107)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: g9.f0: [n1{Cancelling}@94e566c, Dispatchers.Main.immediate]
Caused by: android.os.TransactionTooLargeException: data parcel size 1131268 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:586)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6430)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1991)
	... 19 more

```
</details>
<hr>

**Comment by kernel0x** [comment]
can be fixed using a library Bundle Saver https://github.com/kernel0x/bundlesaver

**Comment by TranceLove** [comment]
Shouldn't it be reported at https://github.com/TeamAmaze/AmazeFileUtilities instead? 🤔
