### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by GitAlasGo** [TeamAmaze/AmazeFileManager#4278]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 11 - 30
* __Device:__ TECNO-KG5k
* __Model:__ TECNO KG5k
* __Product:__ F062
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String androidx.documentfile.provider.DocumentFile.getName()' on a null object reference
	at com.amaze.filemanager.filesystem.HybridFile.getName(HybridFile.java:484)
	at com.amaze.filemanager.adapters.HiddenAdapter.onBindViewHolder(HiddenAdapter.kt:73)
	at com.amaze.filemanager.adapters.HiddenAdapter.onBindViewHolder(HiddenAdapter.kt:50)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1391)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1128)
	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1841)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5302)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1009)
	at android.view.Choreographer.doCallbacks(Choreographer.java:820)
	at android.view.Choreographer.doFrame(Choreographer.java:743)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:268)
	at android.app.ActivityThread.main(ActivityThread.java:8023)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:635)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3734
