### ISSUE TITLE
Crashes on trying to install APKs on Nougat

### ISSUE THREAD

**Issue by gedling** [TeamAmaze/AmazeFileManager#519]
Might be a nougat issue, might be a LineageOS 14.1 issue. But APKs open fine through default Files but crashes in Amaze. Logs sent.

OnePlus 3, Sultanxda's LineageOS.

**Comment by vishal0071** [comment]
Which device? Also, write this problem while sending stack trace otherwise it can be difficult to find yours.

**Comment by gedling** [comment]
OnePlus 3.  And logs were last night but I'll reproduce now.

**Comment by vishal0071** [comment]
Got it. Your problem will be fixed in upcoming beta.

**Comment by nvllsvm** [comment]
Still happening as of 3.1.2-rc3 (F-Droid)

**Device:** OnePlus 3T
**Android:** 7.1.2
**ROM:** SultanXDA's LineageOS 14.1 20170506
**No GApps**

```
05-12 07:55:29.782  2518  4764 I ActivityManager: Start proc 4909:com.amaze.filemanager/u0a320 for activity com.amaze.filemanager/.activities.MainActivity
05-12 07:55:29.826  4909  4909 W System  : ClassLoader referenced unknown path: /data/app/com.amaze.filemanager-1/lib/arm64
05-12 07:55:29.852  4909  4909 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
05-12 07:55:29.971  4909  4909 D TabFragment: Page Selected: 1
05-12 07:55:30.064  4909  4932 I Adreno  : QUALCOMM build                   : 853a1ff, I9c435c2712
05-12 07:55:30.064  4909  4932 I Adreno  : Build Date                       : 01/10/17
05-12 07:55:30.064  4909  4932 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
05-12 07:55:30.064  4909  4932 I Adreno  : Local Branch                     : 
05-12 07:55:30.064  4909  4932 I Adreno  : Remote Branch                    : 
05-12 07:55:30.064  4909  4932 I Adreno  : Remote Branch                    : 
05-12 07:55:30.064  4909  4932 I Adreno  : Reconstruct Branch               : 
05-12 07:55:30.068  4909  4932 I OpenGLRenderer: Initialized EGL, version 1.4
05-12 07:55:30.068  4909  4932 D OpenGLRenderer: Swap behavior 1
05-12 07:55:30.072  4909  4909 E RecyclerView: No adapter attached; skipping layout
05-12 07:55:30.072  4909  4909 E RecyclerView: No adapter attached; skipping layout
05-12 07:55:30.095  4909  4909 W View    : requestLayout() improperly called by android.widget.FrameLayout{d0a2c5f V.E...... ......ID 0,118-1080,269 #7f100125 app:id/buttonbarframe} during layout: running second layout pass
05-12 07:55:30.095  4909  4909 W View    : requestLayout() improperly called by android.support.v7.widget.Toolbar{75406ac V.E...... ......ID 0,0-1080,118 #7f100069 app:id/action_bar} during layout: running second layout pass
05-12 07:55:30.264  4909  4914 I art     : Do partial code cache collection, code=22KB, data=27KB
05-12 07:55:30.264  4909  4914 I art     : After code cache collection, code=22KB, data=27KB
05-12 07:55:30.265  4909  4914 I art     : Increasing code cache capacity to 128KB
05-12 07:55:30.514  4909  4914 I art     : Do partial code cache collection, code=51KB, data=61KB
05-12 07:55:30.515  4909  4914 I art     : After code cache collection, code=51KB, data=61KB
05-12 07:55:30.515  4909  4914 I art     : Increasing code cache capacity to 256KB
05-12 07:55:35.436  4909  4909 D AndroidRuntime: Shutting down VM
05-12 07:55:35.439  4909  4909 E AndroidRuntime: FATAL EXCEPTION: main
05-12 07:55:35.439  4909  4909 E AndroidRuntime: Process: com.amaze.filemanager, PID: 4909
05-12 07:55:35.439  4909  4909 E AndroidRuntime: android.os.FileUriExposedException: file:///storage/emulated/0/Download/DSub.5.3.5.apk exposed beyond app through Intent.getData()
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1806)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.net.Uri.checkFileUriExposed(Uri.java:2346)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:8981)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:8942)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4229)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4187)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4526)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4494)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at com.amaze.filemanager.utils.Futils.openunknown(Futils.java:446)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at com.amaze.filemanager.utils.Futils$23.onPositive(Futils.java:1328)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:358)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.view.View.performClick(View.java:5637)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22433)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
05-12 07:55:35.439  4909  4909 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
05-12 07:56:04.969  2518  4763 I ActivityManager: Killing 4909:com.amaze.filemanager/u0a320 (adj 902): crash
05-12 07:56:04.970  2518  4763 D ActivityManager: cleanUpApplicationRecord -- 4909
```

**Comment by vishal0071** [comment]
Still facing this issue?

**Comment by nvllsvm** [comment]
Still breaking with 3.2.1.

**Comment by EmmanuelMess** [comment]
This should be fixed now.
