### ISSUE TITLE
Crash with OPEN-DOCUMENT-TREE when opening file

### ISSUE THREAD

**Issue by debughao** [TeamAmaze/AmazeFileManager#538]
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
                                                                           at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
                                                                           at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
                                                                           at android.app.Activity.startActivityForResult(Activity.java:3424)
                                                                           at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                           at android.app.Activity.startActivityForResult(Activity.java:3385)
                                                                           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                           at com.amaze.filemanager.activities.MainActivity.selectItem(MainActivity.java:856)
                                                                           at com.amaze.filemanager.adapters.DrawerAdapter$1.onClick(DrawerAdapter.java:135)
                                                                           at android.view.View.performClick(View.java:4438)
                                                                           at android.view.View$PerformClick.run(View.java:18422)
                                                                           at android.os.Handler.handleCallback(Handler.java:733)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)
                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by vishal0071** [comment]
What Android version do you use?

**Comment by kaas3031** [comment]
Hi same issue has been occur with me installed latest version from FDroid (https://f-droid.org/packages/com.amaze.filemanager/) with following Version 3.2.1 (63) - Added on 2017-09-02
OS is 4.4.2

**Comment by VishalNehra** [comment]
Closing this, probably caused because the document ui wasn't present in the system.
