### ISSUE TITLE
Scrolling through 480 photos crashes app

### ISSUE THREAD

**Issue by EmmanuelMess** [TeamAmaze/AmazeFileManager#642]
I have a folder with ~500 photos, when I use the "bar" on the side to scroll down, halfway down the app simply crashes. Also, I think the app should "teleport" directly to the position, instead of trying to move, loading each file in the way.
Last tested on version [fcfaa00](https://github.com/arpitkh96/AmazeFileManager/commit/fcfaa00e35250db02bcc2059eb4f8595e78e35cb)
```
06-23 11:32:43.541 2783-2783/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.amaze.filemanager, PID: 2783
                                                 java.util.ConcurrentModificationException
                                                     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
                                                     at java.util.HashMap$EntryIterator.next(HashMap.java:824)
                                                     at java.util.HashMap$EntryIterator.next(HashMap.java:824)
                                                     at com.amaze.filemanager.ui.icons.IconHolder$1.processResult(IconHolder.java:104)
                                                     at com.amaze.filemanager.ui.icons.IconHolder$1.handleMessage(IconHolder.java:89)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by vishal0071** [comment]
Please test and report

**Comment by EmmanuelMess** [comment]
It seems to only happen when scrolling with finger. Tested with 4000 images.
