### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by eileenfan** [TeamAmaze/AmazeFileManager#755]
//package name: com.amaze.filemanager
//version: 3.1.1
 java.lang.RuntimeException: An error occured while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 	at java.lang.Thread.run(Thread.java:841)
 Caused by: java.util.ConcurrentModificationException
 	at java.util.AbstractList$FullListIterator.set(AbstractList.java:148)
 	at java.util.Collections.sort(Collections.java:1896)
 	at com.amaze.filemanager.fragments.Main$12.doInBackground(Main.java:1442)
 	at com.amaze.filemanager.fragments.Main$12.doInBackground(Main.java:1439)
 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)

**Comment by vishal0071** [comment]
Why are you posting logs for older version? It's been about a year since that version was released.
