### ISSUE TITLE
RuntimeException: Parcel android.os.Parcel@ad26cb68: Unmarshalling unknown type code 1287874176 at offset 480

### ISSUE THREAD

**Issue by eileenfan** [TeamAmaze/AmazeFileManager#758]
//package name: com.amaze.filemanager
//version: 3.1.1
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@ad26cb68: Unmarshalling unknown type code 1287874176 at offset 480
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@ad26cb68: Unmarshalling unknown type code 1287874176 at offset 480
 	at android.os.Parcel.readValue(Parcel.java:2038)
 	at android.os.Parcel.readListInternal(Parcel.java:2264)
 	at android.os.Parcel.readArrayList(Parcel.java:1661)
 	at android.os.Parcel.readValue(Parcel.java:1992)
 	at android.os.Parcel.readMapInternal(Parcel.java:2255)
 	at android.os.Bundle.unparcel(Bundle.java:223)
 	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1237)
 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:997)
 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
 	at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2041)
 	at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:163)
 	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:332)
 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
 	at com.amaze.filemanager.activities.BaseActivity.onCreate(BaseActivity.java:38)
 	at com.amaze.filemanager.activities.MainActivity.onCreate(MainActivity.java:246)
 	at android.app.Activity.performCreate(Activity.java:5133)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)

**Comment by vishal0071** [comment]
Why are you posting logs for older version? It's been about a year since that version was released.
