### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by eileenfan** [TeamAmaze/AmazeFileManager#763]
//package name: com.amaze.filemanager
//version: 3.1.1
 java.lang.NoSuchMethodError: android.content.Context.getExternalFilesDirs
 	at com.amaze.filemanager.filesystem.FileUtil.getExtSdCardPaths(FileUtil.java:573)
 	at com.amaze.filemanager.filesystem.FileUtil.getExtSdCardFolder(FileUtil.java:628)
 	at com.amaze.filemanager.filesystem.FileUtil.isOnExtSdCard(FileUtil.java:651)
 	at com.amaze.filemanager.utils.MainActivityHelper.checkFolder(MainActivityHelper.java:268)
 	at com.amaze.filemanager.services.asynctasks.CopyFileCheck.showDialog(CopyFileCheck.java:103)
 	at com.amaze.filemanager.services.asynctasks.CopyFileCheck.onPostExecute(CopyFileCheck.java:197)
 	at com.amaze.filemanager.services.asynctasks.CopyFileCheck.onPostExecute(CopyFileCheck.java:33)
 	at android.os.AsyncTask.finish(AsyncTask.java:631)
 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by vishal0071** [comment]
Why are you posting logs for older version? It's been about a year since that version was released.

**Comment by caarmen** [comment]
I think this user may be a bot. It's opened 135 issues in over 32 repositories in recent days, and appears to be opening more issues as I write this comment ☺️ I'm not sure if this violates the accepted usage of github. It's redundant with crash reports on the Play Store (which provide more details actually, than these github issues.)  I reported the account. Not sure if it will result in any action. There are probably good intentions behind it, but one source of crash reports is enough for me ☺️

**Comment by eileenfan** [comment]
@caarmen I'm not a robot, we are reporting crashes based on our testing tools ([Stoat](https://github.com/tingsu/Stoat)). I apologize for the inconvenience brought to you and will try my best to avoid reporting redundant crashes.
