### ISSUE TITLE
Support VIEW_DIRECTORY intent

### ISSUE THREAD

**Issue by PanderMusubi** [TeamAmaze/AmazeFileManager#791]
Please, support VIEW_DIRECTORY intent in order for other apps to find AmazeFileManager as a file manager to use. For more details, see https://github.com/IvanVolosyuk/diskusage/issues/42#event-1272929552

**Comment by vishal0071** [comment]
Please see #640

**Comment by EmmanuelMess** [comment]
@vishal0071 As far as I can tell #640 deals with files, not folders, VIEW_DIRECTORY would open a directory in a file manager, not a file.
@PanderMusubi Can you link some documentation on "org.openintents.action.VIEW_DIRECTORY"?

**Comment by PanderMusubi** [comment]
In this case, I am just the messenger. Sorry, con't help you with this.

**Comment by ildar** [comment]
Indeed search shows no VIEW_DIRECTORY in code.
Please reopen

**Comment by k3b** [comment]
since [i need this feature, too](https://github.com/k3b/APhotoManager/issues/99) here is a summary from my point of view

Feature request:

allow other apps to open the installed filemanager to show all files/subdirectories that are inside a given directory through an intent api:

(note this is slightly different from a file picker or dir picker)

----

Technical details:

* action=android.intent.action.VIEW
* data=file:/path/to/directory/
* mime=vnd.android.document/directory (android api-19 DocumentsContract.Document.MIME_TYPE_DIR already implemented by diskusage)

alternatives used

* data=file:///path/to/directory/
* mime=resource/folder (used by some filemanagers https://github.com/openintents/filemanager/issues/87 )

 
see also https://github.com/syncthing/syncthing-android/issues/838

note: when i open amaze v3.2.1 (fdroid build) on my android-4.4.2 with 

* action=android.intent.action.VIEW
* data=file:/path/to/directory/
* mime= * / *

amaze currently crashes 

----------------------------------------

amaze crash

D/ActivityThread: ACT-NEW_INTENT handled : 0 / NewIntentData{intents=[
	Intent { 
		act=android.intent.action.VIEW 
		dat=file:/storage/sdcard0/copy/neu/ 
		typ= * / * 
		flg=0x13400000 
		cmp=com.amaze.filemanager/.activities.MainActivity }] token=android.os.BinderProxy@42061fd0}
...
W/System.err: java.lang.RuntimeException: Unable to resume activity {com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}: java.lang.StringIndexOutOfBoundsException: length=3; regionStart=0; regionLength=-1
W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2964)
W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2993)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
W/System.err:     at android.os.Looper.loop(Looper.java:193)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5299)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)
W/System.err: Caused by: java.lang.StringIndexOutOfBoundsException: length=3; regionStart=0; regionLength=-1
W/System.err:     at java.lang.String.startEndAndLength(String.java:588)
W/System.err:     at java.lang.String.substring(String.java:1475)
W/System.err:     at com.amaze.filemanager.fragments.ZipViewer.onActivityCreated(ZipViewer.java:223)
W/System.err:     at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2201)
W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1326)
W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
W/System.err:     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
W/System.err:     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
W/System.err:     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
W/System.err:     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
W/System.err:     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
W/System.err:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
W/System.err:     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1174)
W/System.err:     at android.app.Activity.performStart(Activity.java:5274)
W/System.err:     at android.app.Activity.performRestart(Activity.java:5330)
W/System.err:     at android.app.Activity.performResume(Activity.java:5335)
W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2950)
W/System.err: 	... 11 more
W/dalvikvm: threadid=1: calling UncaughtExceptionHandler

**Comment by k3b** [comment]
this is a duplicate of #419

**Comment by vishal0071** [comment]
I've pushed a fix, please test when beta version comes out.

**Comment by k3b** [comment]
will the betta be available at https://androidfilehost.com/?w=files&flid=73973 ? i have no playstore/google-account.

If not i can download the sources and compile myself.

**Comment by PanderMusubi** [comment]
I have installed version 3.2.2 (64) 2018-06-24 via F-Droid app store, but DiskUsage version 3.8.0 (3080) 2017-08-30, see https://github.com/IvanVolosyuk/diskusage/issues/42 , is not finding Amaze as a file manager.

![screenshot_20181126-133436](https://user-images.githubusercontent.com/198964/49296790-7262ba00-f4b9-11e8-91e1-1a32eeb837da.jpg)

This issue needs another attempt to get fixed.

**Comment by VishalNehra** [comment]
Maybe try with latest play store version? v3.3.0 @PanderMusubi

**Comment by PanderMusubi** [comment]
I'm seeing that F-Droid is picking up a new release, but that there is a problem. Shall we get that fixed first? Please see https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.amaze.filemanager.txt

**Comment by PanderMusubi** [comment]
@VishalNehra , just tested with 3.3.0 from Google Play, issue is still there.

(Create another issues for F-droid build problem?)

**Comment by guillaume-d** [comment]
@PanderMusubi Tried to bump #1280, let's see what happens.

**Comment by PanderMusubi** [comment]
Just checked, still same problem with version 3.3.2. Any ideas on how to get this fixed?

**Comment by EmmanuelMess** [comment]
Okay, from reading the code added in 2c14ba516b1e0eb845476ef3a8f930049e250b76 and @k3b's comment, this seems to be the problem: the mime we detect is `resource/folder` but only some apps actually use it, `vnd.android.document/directory` would be the one that would be the one you seem to need.

**Comment by PanderMusubi** [comment]
Any progress regarding this issue so that other apps can use Amaze as file manager?

**Comment by EmmanuelMess** [comment]
@PanderMusubi no, I don't think so.
