### ISSUE TITLE
Amaze file manager closing down on selecting a file on 4.4.2 Samsung Tablet

### ISSUE THREAD

**Issue by shubham1g5** [TeamAmaze/AmazeFileManager#836]
On selecting a file on 4.4.2 Samsung tablet from Amaze file manager, the amaze file manager closes down without crashing and doesn't revert back to my app but instead go back to Android file manager. I am consistently getting `android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud` from Amaze in my logs. Pasting the complete logs here - 

``` W/System.err: android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err:     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:108)
W/System.err:     at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err:     at com.amaze.filemanager.activities.MainActivity.onCreate(MainActivity.java:332)
W/System.err:     at android.app.Activity.performCreate(Activity.java:5451)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:175)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:146)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5602)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)
W/System.err: android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err:     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:108)
W/System.err:     at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err:     at com.amaze.filemanager.activities.MainActivity.refreshDrawer(MainActivity.java:1441)
W/System.err:     at com.amaze.filemanager.activities.MainActivity$3.onPostExecute(MainActivity.java:484)
W/System.err:     at com.amaze.filemanager.utils.AppConfig$1.onPostExecute(AppConfig.java:104)
W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:632)
W/System.err:     at android.os.AsyncTask.access$600(AsyncTask.java:177)
W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:146)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5602)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)
```

This process is working fine with Android 5+ devices, So am I missing something here that I need to implement for pre 5.0 devices ?

**Comment by VishalNehra** [comment]
Logcat is not complete. If possible please provide a complete logcat, or simply report from the FC dialog and mention this issue number in the message.

**Comment by shubham1g5** [comment]
The only other relevant bit I can see is - 

```
 E/DatabaseUtils: Writing exception to parcel
java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
                                                    at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:15031)
                                                    at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2492)
                                                    at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:688)
                                                    at android.content.ContentProvider$Transport.call(ContentProvider.java:325)
                                                    at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:275)
                                                    at android.os.Binder.execTransact(Binder.java:404)
                                                    at dalvik.system.NativeStart.run(Native Method)

```
This might be the culprit but the same logs occur when I choose a file using the Android file manager which returns the file path successfully to my app unlike Amaze.

I am also getting lots of instances of - 

```
E/BufferQueue: [com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity] dequeueBuffer: min undequeued buffer count (1) exceeded (dequeued=2 undequeudCount=0)
```

Also note that Amaze is crashing silently, so can't report the issue from FC dialog.

**Comment by EmmanuelMess** [comment]
Please provide the whole logcat, as a file. What you provided is too general to pinpoint a specific error in a specific line of code in the app.

**Comment by VishalNehra** [comment]
@shubham1g5 the first one you gave is not related to Amaze, and the second one is a dump from system, nothing we can do about. As for the cloud error, that shouldn't prevent you from using Amaze. Please try capturing logcat from any other tool.

**Comment by shubham1g5** [comment]
Sorry for dropping this. Please find the complete verbose logcat [here](https://gist.github.com/shubham1g5/32fabc621fd66e3bbaa8a6c95e9f287a) though I am not able to see any other relevant info in logs.  Also [here](https://drive.google.com/open?id=1PbQBcmeQiyOgQPUD-vMBf85G4aRsdcoV) is a video demonstrating the issue on Amaze (while other file providers work successfully). Let me know if there is anything else I can do that can help debug this. Thanks.
