### ISSUE TITLE
Crash when trying to add new SMB source

### ISSUE THREAD

**Issue by jpage4500** [TeamAmaze/AmazeFileManager#851]
to reproduce:
- start app
- click on "+" button (FAB)
- hit SMB
- app crashed

Testing on S7 running 7.0

NOTE: this is because of the progress spinner was trying to reference holder.txtTitle for the progressbar which is null

**Comment by EmmanuelMess** [comment]
Logcat:
```
12-01 13:50:27.722 com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: com.amaze.filemanager, PID: 16236
                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                               at com.amaze.filemanager.ui.dialogs.SmbSearchDialog$ListViewAdapter.onBindViewHolder(SmbSearchDialog.java:163)
                                                               at com.amaze.filemanager.ui.dialogs.SmbSearchDialog$ListViewAdapter.onBindViewHolder(SmbSearchDialog.java:116)
                                                               at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                               at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                               at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                               at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                               at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                               at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                               at android.view.View.measure(View.java:18804)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                               at android.view.View.measure(View.java:18804)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                               at android.view.View.measure(View.java:18804)
                                                               at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:294)
                                                               at android.view.View.measure(View.java:18804)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                               at android.view.View.measure(View.java:18804)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                               at android.view.View.measure(View.java:18804)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                               at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                               at android.view.View.measure(View.java:18804)
                                                               at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2112)
                                                               at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1228)
                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1464)
                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                               at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                               at android.os.Handler.handleCallback(Handler.java:746)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
```

**Comment by EmmanuelMess** [comment]
Have you fixed in commit 2c8175b40e3e747b4c1bfda265052f20e307f316?

**Comment by jpage4500** [comment]
@EmmanuelMess -- sorry, i tried to restructure my local braches so each fix applies to an issue.. i haven't done many pull requests before but have been an Android dev for many years so hopefully I can help with a few things

**Comment by jpage4500** [comment]
fixed with this PR: https://github.com/TeamAmaze/AmazeFileManager/pull/852
