### ISSUE TITLE
Crash when copying files

### ISSUE THREAD

**Issue by jpage4500** [TeamAmaze/AmazeFileManager#857]
I thought this was the same issue as #785 but my stack traces that I saw were different so I'm opening a new issue (there's a PR for it as well)

To reproduce I:
- copied 2 files from SMB source
- changed to external SD card and hit paste

stack traces (both crashes occurred and were fixed one by one)

```
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime     Process: com.amaze.filemanager, PID: 11141
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime     java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/tree/29A4-1410: flg=0xc3 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }} to activity {com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         at android.app.ActivityThread.-wrap22(ActivityThread.java)
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         at android.os.Handler.dispatchMessage(Handler.java:102)
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         at android.os.Looper.loop(Looper.java:154)
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         at android.app.ActivityThread.main(ActivityThread.java:6642)
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         at java.lang.reflect.Method.invoke(Native Method)
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         at com.amaze.filemanager.activities.MainActivity.onActivityResult(MainActivity.java:1579)
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         at android.app.Activity.dispatchActivityResult(Activity.java:7226)
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
11-30 16:55:54.403    com.amaze.filemanager    11141    -    E    AndroidRuntime         ... 9 more
```

and

```
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime     java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.support.v4.util.Pair.second' on a null object reference
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime         at com.amaze.filemanager.fragments.MainFragment.lambda$loadlist$3(MainFragment.java:1031)
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime         at com.amaze.filemanager.fragments.MainFragment$$Lambda$4.onAsyncTaskFinished(Unknown Source)
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime         at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:215)
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime         at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:65)
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime         at android.os.AsyncTask.finish(AsyncTask.java:660)
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime         at android.os.AsyncTask.-wrap1(AsyncTask.java)
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime         at android.os.Handler.dispatchMessage(Handler.java:102)
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime         at android.os.Looper.loop(Looper.java:154)
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime         at android.app.ActivityThread.main(ActivityThread.java:6642)
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime         at java.lang.reflect.Method.invoke(Native Method)
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
12-01 09:50:12.791    com.amaze.filemanager    26528    -    E    AndroidRuntime         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

and *finally* I also saw this crash which I opened another issue for but might all be related
```
11-30 19:47:49.009    com.amaze.filemanager    27621    -    E    AndroidRuntime     java.util.ConcurrentModificationException
11-30 19:47:49.009    com.amaze.filemanager    27621    -    E    AndroidRuntime         at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
11-30 19:47:49.009    com.amaze.filemanager    27621    -    E    AndroidRuntime         at java.util.HashMap$EntryIterator.next(HashMap.java:891)
11-30 19:47:49.009    com.amaze.filemanager    27621    -    E    AndroidRuntime         at java.util.HashMap$EntryIterator.next(HashMap.java:890)
11-30 19:47:49.009    com.amaze.filemanager    27621    -    E    AndroidRuntime         at com.amaze.filemanager.ui.icons.IconHolder$1.processResult(IconHolder.java:110)
11-30 19:47:49.009    com.amaze.filemanager    27621    -    E    AndroidRuntime         at com.amaze.filemanager.ui.icons.IconHolder$1.handleMessage(IconHolder.java:89)
11-30 19:47:49.009    com.amaze.filemanager    27621    -    E    AndroidRuntime         at android.os.Handler.dispatchMessage(Handler.java:102)
11-30 19:47:49.009    com.amaze.filemanager    27621    -    E    AndroidRuntime         at android.os.Looper.loop(Looper.java:154)
11-30 19:47:49.009    com.amaze.filemanager    27621    -    E    AndroidRuntime         at android.app.ActivityThread.main(ActivityThread.java:6642)
11-30 19:47:49.009    com.amaze.filemanager    27621    -    E    AndroidRuntime         at java.lang.reflect.Method.invoke(Native Method)
11-30 19:47:49.009    com.amaze.filemanager    27621    -    E    AndroidRuntime         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
11-30 19:47:49.009    com.amaze.filemanager    27621    -    E    AndroidRuntime         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by jpage4500** [comment]
fixed with https://github.com/TeamAmaze/AmazeFileManager/pull/853
