### ISSUE TITLE
Crash: Indexoutofbounds

### ISSUE THREAD

**Issue by peribas** [TeamAmaze/AmazeFileManager#900]
Hello.

Thanks for that very nice app. Installed it to my phone that is running android 4.4.4. Amaze crashes when scrolling.

Latest version from F-Droid store.

Crashlog:

> W/AudioService( 2093): stream was not muted by this client
E/AudioService( 2093): Could not get client death handler for stream: 3
--------- beginning of /dev/log/system
I/ActivityManager( 2093): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.amaze.filemanager/.activities.MainActivity} from pid 2346
W/BroadcastQueue( 2093): Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.android.launcher3 (pid=2346, uid=10009) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver
W/BroadcastQueue( 2093): Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.android.launcher3 (uid 10009)
W/BroadcastQueue( 2093): Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.android.launcher3 (uid 10009)
I/libblt_hw( 1675): Library opened (handle = 6, fd = 56)
V/Zygote  (29615): Switching descriptor 32 to /dev/null
V/Zygote  (29615): Switching descriptor 9 to /dev/null
I/ActivityManager( 2093): Start proc com.amaze.filemanager for activity com.amaze.filemanager/.activities.MainActivity: pid=29615 uid=10058 gids={50058, 1028, 1015, 1023, 3003}
E/dalvikvm(29615): Could not find class 'android.graphics.drawable.VectorDrawable', referenced from method com.amaze.filemanager.activities.MainActivity.initFabToSave
W/dalvikvm(29615): VFY: unable to resolve check-cast 183 (Landroid/graphics/drawable/VectorDrawable;) in Lcom/amaze/filemanager/activities/MainActivity;
D/dalvikvm(29615): VFY: replacing opcode 0x1f at 0x001b
I/dalvikvm(29615): Could not find method android.view.Window.setStatusBarColor, referenced from method com.amaze.filemanager.activities.MainActivity.initialiseViews
W/dalvikvm(29615): VFY: unable to resolve virtual method 22186: Landroid/view/Window;.setStatusBarColor (I)V
D/dalvikvm(29615): VFY: replacing opcode 0x6e at 0x028c
I/dalvikvm(29615): Could not find method android.view.Window.setNavigationBarColor, referenced from method com.amaze.filemanager.activities.MainActivity.initialiseViews
W/dalvikvm(29615): VFY: unable to resolve virtual method 22185: Landroid/view/Window;.setNavigationBarColor (I)V
D/dalvikvm(29615): VFY: replacing opcode 0x6e at 0x0295
E/dalvikvm(29615): Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.amaze.filemanager.activities.MainActivity.onCreate
W/dalvikvm(29615): VFY: unable to resolve new-instance 29 (Landroid/app/ActivityManager$TaskDescription;) in Lcom/amaze/filemanager/activities/MainActivity;
D/dalvikvm(29615): VFY: replacing opcode 0x22 at 0x0165
I/dalvikvm(29615): Could not find method android.view.Window.setStatusBarColor, referenced from method com.amaze.filemanager.activities.MainActivity.updateViews
W/dalvikvm(29615): VFY: unable to resolve virtual method 22186: Landroid/view/Window;.setStatusBarColor (I)V
D/dalvikvm(29615): VFY: replacing opcode 0x6e at 0x003a
D/dalvikvm(29615): DexOpt: unable to opt direct call 0x00a6 at 0x187 in Lcom/amaze/filemanager/activities/MainActivity;.onCreate
I/dalvikvm(29615): Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method android.support.v7.view.WindowCallbackWrapper.onProvideKeyboardShortcuts
W/dalvikvm(29615): VFY: unable to resolve interface method 22161: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
D/dalvikvm(29615): VFY: replacing opcode 0x72 at 0x0002
W/dalvikvm(29615): VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
I/dalvikvm(29615): Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
W/dalvikvm(29615): VFY: unable to resolve interface method 22163: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
D/dalvikvm(29615): VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm(29615): Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
W/dalvikvm(29615): VFY: unable to resolve interface method 22167: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
D/dalvikvm(29615): VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm(29615): Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
W/dalvikvm(29615): VFY: unable to resolve virtual method 646: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
D/dalvikvm(29615): VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm(29615): Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
W/dalvikvm(29615): VFY: unable to resolve virtual method 668: Landroid/content/res/TypedArray;.getType (I)I
D/dalvikvm(29615): VFY: replacing opcode 0x6e at 0x0008
I/dalvikvm(29615): Could not find method android.content.Context.getColor, referenced from method com.amaze.filemanager.utils.Utils.getColor
W/dalvikvm(29615): VFY: unable to resolve virtual method 428: Landroid/content/Context;.getColor (I)I
D/dalvikvm(29615): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm(29615): Could not find method android.widget.CheckBox.setButtonTintList, referenced from method com.amaze.filemanager.utils.Utils.setTint
W/dalvikvm(29615): VFY: unable to resolve virtual method 22568: Landroid/widget/CheckBox;.setButtonTintList (Landroid/content/res/ColorStateList;)V
D/dalvikvm(29615): VFY: replacing opcode 0x6e at 0x0034
I/libblt_hw( 1675): Library closed (handle = 8, fd = 48)
I/dalvikvm(29615): Could not find method android.content.Context.getColorStateList, referenced from method android.support.v7.content.res.AppCompatResources.getColorStateList
W/dalvikvm(29615): VFY: unable to resolve virtual method 429: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
D/dalvikvm(29615): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm(29615): Could not find method android.content.res.Resources.getDrawable, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawable
W/dalvikvm(29615): VFY: unable to resolve virtual method 609: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm(29615): VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm(29615): Could not find method android.content.res.Resources.getDrawableForDensity, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawableForDensity
W/dalvikvm(29615): VFY: unable to resolve virtual method 611: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm(29615): VFY: replacing opcode 0x6e at 0x0002
E/dalvikvm(29615): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
W/dalvikvm(29615): VFY: unable to resolve instanceof 179 (Landroid/graphics/drawable/RippleDrawable;) in Landroid/support/v7/widget/AppCompatImageHelper;
D/dalvikvm(29615): VFY: replacing opcode 0x20 at 0x000c
I/dalvikvm(29615): Could not find method android.widget.ImageButton.<init>, referenced from method com.github.clans.fab.FloatingActionButton.<init>
W/dalvikvm(29615): VFY: unable to resolve direct method 22748: Landroid/widget/ImageButton;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
D/dalvikvm(29615): VFY: replacing opcode 0x70 at 0x0003
W/dalvikvm(29615): Unable to resolve superclass of Lcom/github/clans/fab/FloatingActionButton$1; (2668)
W/dalvikvm(29615): Link of class 'Lcom/github/clans/fab/FloatingActionButton$1;' failed
E/dalvikvm(29615): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.github.clans.fab.FloatingActionButton.createFillDrawable
W/dalvikvm(29615): VFY: unable to resolve new-instance 179 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/github/clans/fab/FloatingActionButton;
D/dalvikvm(29615): VFY: replacing opcode 0x22 at 0x0038
E/dalvikvm(29615): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.github.clans.fab.FloatingActionButton.onActionDown
W/dalvikvm(29615): VFY: unable to resolve check-cast 179 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/github/clans/fab/FloatingActionButton;
D/dalvikvm(29615): VFY: replacing opcode 0x1f at 0x001d
E/dalvikvm(29615): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.github.clans.fab.FloatingActionButton.onActionUp
W/dalvikvm(29615): VFY: unable to resolve check-cast 179 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/github/clans/fab/FloatingActionButton;
D/dalvikvm(29615): VFY: replacing opcode 0x1f at 0x001f
I/dalvikvm(29615): Could not find method android.widget.ImageButton.setElevation, referenced from method com.github.clans.fab.FloatingActionButton.setElevation
W/dalvikvm(29615): VFY: unable to resolve virtual method 22766: Landroid/widget/ImageButton;.setElevation (F)V
D/dalvikvm(29615): VFY: replacing opcode 0x6f at 0x000b
I/dalvikvm(29615): Could not find method android.widget.ImageButton.setElevation, referenced from method com.github.clans.fab.FloatingActionButton.setElevationCompat
W/dalvikvm(29615): VFY: unable to resolve virtual method 22766: Landroid/widget/ImageButton;.setElevation (F)V
D/dalvikvm(29615): VFY: replacing opcode 0x6f at 0x0023
W/AudioService( 2093): stream was not muted by this client
E/AudioService( 2093): Could not get client death handler for stream: 3
W/dalvikvm(29615): Unable to resolve superclass of Lcom/github/clans/fab/FloatingActionButton$1; (2668)
W/AudioService( 2093): stream was not muted by this client
E/AudioService( 2093): Could not get client death handler for stream: 3
W/dalvikvm(29615): Link of class 'Lcom/github/clans/fab/FloatingActionButton$1;' failed
D/dalvikvm(29615): DexOpt: unable to opt direct call 0x0425 at 0x4c in Lcom/github/clans/fab/FloatingActionButton;.createFillDrawable
W/dalvikvm(29615): Unable to resolve superclass of Lcom/github/clans/fab/FloatingActionButton$1; (2668)
W/dalvikvm(29615): Link of class 'Lcom/github/clans/fab/FloatingActionButton$1;' failed
D/dalvikvm(29615): DexOpt: unable to opt direct call 0x717b at 0x51 in Lcom/github/clans/fab/FloatingActionButton;.createFillDrawable
E/dalvikvm(29615): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.github.clans.fab.Label.createFillDrawable
W/dalvikvm(29615): VFY: unable to resolve new-instance 179 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/github/clans/fab/Label;
D/dalvikvm(29615): VFY: replacing opcode 0x22 at 0x0028
E/dalvikvm(29615): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.github.clans.fab.Label.onActionDown
W/dalvikvm(29615): VFY: unable to resolve instanceof 179 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/github/clans/fab/Label;
D/dalvikvm(29615): VFY: replacing opcode 0x20 at 0x0029
E/dalvikvm(29615): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.github.clans.fab.Label.onActionUp
W/dalvikvm(29615): VFY: unable to resolve instanceof 179 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/github/clans/fab/Label;
D/dalvikvm(29615): VFY: replacing opcode 0x20 at 0x0024
W/dalvikvm(29615): Unable to resolve superclass of Lcom/github/clans/fab/Label$1; (2668)
W/dalvikvm(29615): Link of class 'Lcom/github/clans/fab/Label$1;' failed
D/dalvikvm(29615): DexOpt: unable to opt direct call 0x0425 at 0x3c in Lcom/github/clans/fab/Label;.createFillDrawable
W/dalvikvm(29615): Unable to resolve superclass of Lcom/github/clans/fab/Label$1; (2668)
W/dalvikvm(29615): Link of class 'Lcom/github/clans/fab/Label$1;' failed
D/dalvikvm(29615): DexOpt: unable to opt direct call 0x72a2 at 0x41 in Lcom/github/clans/fab/Label;.createFillDrawable
I/dalvikvm(29615): Could not find method android.support.v7.widget.Toolbar.setElevation, referenced from method com.amaze.filemanager.ui.views.appbar.AppBar.<init>
W/dalvikvm(29615): VFY: unable to resolve virtual method 20958: Landroid/support/v7/widget/Toolbar;.setElevation (F)V
D/dalvikvm(29615): VFY: replacing opcode 0x6e at 0x0031
I/dalvikvm(29615): Could not find method android.view.ViewAnimationUtils.createCircularReveal, referenced from method com.amaze.filemanager.ui.views.appbar.SearchView.hideSearchView
W/dalvikvm(29615): VFY: unable to resolve static method 21948: Landroid/view/ViewAnimationUtils;.createCircularReveal (Landroid/view/View;IIFF)Landroid/animation/Animator;
D/dalvikvm(29615): VFY: replacing opcode 0x71 at 0x0041
I/dalvikvm(29615): Could not find method android.view.ViewAnimationUtils.createCircularReveal, referenced from method com.amaze.filemanager.ui.views.appbar.SearchView.revealSearchView
W/dalvikvm(29615): VFY: unable to resolve static method 21948: Landroid/view/ViewAnimationUtils;.createCircularReveal (Landroid/view/View;IIFF)Landroid/animation/Animator;
D/dalvikvm(29615): VFY: replacing opcode 0x71 at 0x0049
W/System.err(29615): android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err(29615): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:82)
W/System.err(29615): 	at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err(29615): 	at com.amaze.filemanager.activities.MainActivity.onCreate(MainActivity.java:313)
W/System.err(29615): 	at android.app.Activity.performCreate(Activity.java:6092)
W/System.err(29615): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
W/System.err(29615): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160)
W/System.err(29615): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
W/System.err(29615): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
W/System.err(29615): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
W/System.err(29615): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(29615): 	at android.os.Looper.loop(Looper.java:136)
W/System.err(29615): 	at android.app.ActivityThread.main(ActivityThread.java:5013)
W/System.err(29615): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(29615): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(29615): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
W/System.err(29615): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
W/System.err(29615): 	at dalvik.system.NativeStart.main(Native Method)
I/libblt_hw( 1675): Library opened (handle = 8, fd = 41)
D/libEGL  (29615): loaded /system/lib/egl/libEGL_mali.so
D/libEGL  (29615): loaded /system/lib/egl/libGLESv1_CM_mali.so
D/libEGL  (29615): loaded /system/lib/egl/libGLESv2_mali.so
D/OpenGLRenderer(29615): Enabling debug mode 0
E/cutils  ( 1671): Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
W/ContextImpl(29615): Failed to ensure directory: /storage/sdcard1/Android/data/com.amaze.filemanager/files/external
W/Vold    ( 1671): Returning OperationFailed - no handler for errno 30
W/System.err(29615): android.content.pm.PackageManager$NameNotFoundException: com.filemanager.amazecloud
W/System.err(29615): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:82)
W/System.err(29615): 	at com.amaze.filemanager.fragments.CloudSheetFragment.isCloudProviderAvailable(CloudSheetFragment.java:89)
W/System.err(29615): 	at com.amaze.filemanager.activities.MainActivity.refreshDrawer(MainActivity.java:1422)
W/System.err(29615): 	at com.amaze.filemanager.activities.MainActivity$3.onPostExecute(MainActivity.java:465)
W/System.err(29615): 	at com.amaze.filemanager.utils.AppConfig$1.onPostExecute(AppConfig.java:104)
W/System.err(29615): 	at android.os.AsyncTask.finish(AsyncTask.java:632)
W/System.err(29615): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
W/System.err(29615): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
W/System.err(29615): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(29615): 	at android.os.Looper.loop(Looper.java:136)
W/System.err(29615): 	at android.app.ActivityThread.main(ActivityThread.java:5013)
W/System.err(29615): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(29615): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(29615): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
W/System.err(29615): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
W/System.err(29615): 	at dalvik.system.NativeStart.main(Native Method)
D/dalvikvm(29615): GC_CONCURRENT freed 791K, 10% free 7598K/8424K, paused 3ms+4ms, total 37ms
I/ActivityManager( 2093): Displayed com.amaze.filemanager/.activities.MainActivity: +945ms
D/TabFragment(29615): Page Selected: 1
E/cutils  ( 1671): Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
W/ContextImpl(29615): Failed to ensure directory: /storage/sdcard1/Android/data/com.amaze.filemanager/files/external
W/Vold    ( 1671): Returning OperationFailed - no handler for errno 30
E/cutils  ( 1671): Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
W/ContextImpl(29615): Failed to ensure directory: /storage/sdcard1/Android/data/com.amaze.filemanager/files/external
W/Vold    ( 1671): Returning OperationFailed - no handler for errno 30
E/cutils  ( 1671): Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
W/ContextImpl(29615): Failed to ensure directory: /storage/sdcard1/Android/data/com.amaze.filemanager/files/external
E/cutils  ( 1671): Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
W/ContextImpl(29615): Failed to ensure directory: /storage/sdcard1/Android/data/com.amaze.filemanager/files/external
W/Vold    ( 1671): Returning OperationFailed - no handler for errno 30
W/Vold    ( 1671): Returning OperationFailed - no handler for errno 30
I/libblt_hw( 1675): Library closed (handle = 6, fd = 56)
E/RecyclerView(29615): No adapter attached; skipping layout
E/RecyclerView(29615): No adapter attached; skipping layout
W/View    (29615): requestLayout() improperly called by android.support.v7.widget.Toolbar{41fc57f0 V.E..... ......ID 0,0-480,84 #7f10006a app:id/action_bar} during layout: running second layout pass
W/View    (29615): requestLayout() improperly called by android.view.View{420c3f10 V.ED.... ......I. 0,0-0,0} during layout: running second layout pass
D/dalvikvm(29615): GC_CONCURRENT freed 1063K, 12% free 8492K/9592K, paused 3ms+5ms, total 42ms
E/InputEventReceiver(29615): Exception dispatching input event.
D/AndroidRuntime(29615): Shutting down VM
W/dalvikvm(29615): threadid=1: thread exiting with uncaught exception (group=0x418f6c08)
E/AndroidRuntime(29615): FATAL EXCEPTION: main
E/AndroidRuntime(29615): Process: com.amaze.filemanager, PID: 29615
E/AndroidRuntime(29615): java.lang.ArrayIndexOutOfBoundsException: length=29; index=-1
E/AndroidRuntime(29615): 	at android.text.StaticLayout.calculateEllipsis(StaticLayout.java:785)
E/AndroidRuntime(29615): 	at android.text.StaticLayout.out(StaticLayout.java:704)
E/AndroidRuntime(29615): 	at android.text.StaticLayout.generate(StaticLayout.java:410)
E/AndroidRuntime(29615): 	at android.text.StaticLayout.<init>(StaticLayout.java:140)
E/AndroidRuntime(29615): 	at android.widget.TextView.makeSingleLayout(TextView.java:6175)
E/AndroidRuntime(29615): 	at android.widget.TextView.makeNewLayout(TextView.java:6032)
E/AndroidRuntime(29615): 	at android.widget.TextView.onMeasure(TextView.java:6389)
E/AndroidRuntime(29615): 	at android.view.View.measure(View.java:16504)
E/AndroidRuntime(29615): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
E/AndroidRuntime(29615): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
E/AndroidRuntime(29615): 	at android.view.View.measure(View.java:16504)
E/AndroidRuntime(29615): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
E/AndroidRuntime(29615): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
E/AndroidRuntime(29615): 	at android.view.View.measure(View.java:16504)
E/AndroidRuntime(29615): 	at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:8636)
E/AndroidRuntime(29615): 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1577)
E/AndroidRuntime(29615): 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
E/AndroidRuntime(29615): 	at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1325)
E/AndroidRuntime(29615): 	at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1061)
E/AndroidRuntime(29615): 	at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1695)
E/AndroidRuntime(29615): 	at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2883)
E/AndroidRuntime(29615): 	at android.view.View.dispatchTouchEvent(View.java:7713)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(29615): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
E/AndroidRuntime(29615): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2327)
E/AndroidRuntime(29615): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1569)
E/AndroidRuntime(29615): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2749)
E/AndroidRuntime(29615): 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
E/AndroidRuntime(29615): 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
E/AndroidRuntime(29615): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
E/AndroidRuntime(29615): 	at android.view.View.dispatchPointerEvent(View.java
W/ActivityManager( 2093):   Force finishing activity com.amaze.filemanager/.activities.MainActivity

**Comment by EmmanuelMess** [comment]
Related #899.
