### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Jaymin-Bhadani** [TeamAmaze/AmazeFileManager#989]
Process: com.ab, PID: 24038
         java.lang.RuntimeException: Unable to create application com.ab.utils.application.AppConfig: java.lang.ArrayIndexOutOfBoundsException: length=18; index=18
         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6037)
         at android.app.ActivityThread.-wrap1(Unknown Source:0)
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
         at android.os.Handler.dispatchMessage(Handler.java:105)
         at android.os.Looper.loop(Looper.java:164)
         at android.app.ActivityThread.main(ActivityThread.java:6809)
         at java.lang.reflect.Method.invoke(Native Method)
         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
         Caused by: java.lang.ArrayIndexOutOfBoundsException: length=18; index=18
         at java.util.Arrays$ArrayList.get(Arrays.java:3769)
         at com.ab.utils.color.ColorPreference.getColorByIndex(ColorPreference.java:80)
         at com.ab.utils.color.ColorPreference.loadFromPreferences(ColorPreference.java:92)
         at com.ab.utils.provider.UtilitiesProvider.<init>(UtilitiesProvider.java:22)
        at com.ab.utils.application.AppConfig.onCreate(AppConfig.java:52)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6034)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6809) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by VishalNehra** [comment]
Related PR #940 is in works to fix this.

**Comment by TranceLove** [comment]
Fixed by #940.
